### ISSUE TITLE
SoGO as landing page, redirect to Admin UI with /admin route

### ISSUE THREAD

**Issue by florianpreuss** [mailcow/mailcow-dockerized#3044] opened 2019-10-14 21:32 UTC
Hey Guys,
would it be possible to set SoGO as landing page, when accessing mail.some-domain.com?
How to do this? And could I set the route /admin to redirect to the Admin UI? 
Some time ago i tested it with web server configurations, but i hat issueses when loading css of the page.

**Comment by mkuron** [comment] 2019-10-15 04:51
Duplicate of #3015, #2352, #2222, #786, #393, #403.

**Closed as completed by mkuron** 2019-10-15 04:51 UTC
