### ISSUE TITLE
SOGo creating/saving draft messages indefinitely 

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#1381] opened 2018-05-12 03:59 UTC
Hi,

I been facing a problem with SOGo for the last days and I've noticed that SOGo is consuming a lot of CPU usage in my server and sometimes even overload, I didn't know what was happening until today that I noticed that my mailbox size was about to reach its limit, so I start to delete many mails in Inbox folder as I found, but the size never decrease, so I start to check the other folders and I found a lot of messages in Drafts and still creating (see image attached).

My last option was to update to the latest Mailcow version but the problem persists.

Is anyone facing this problem too? What do you think is happening, any ideas to solve this? 

![image](https://user-images.githubusercontent.com/205403/39953323-a0dfbdd0-5566-11e8-8584-2c96bfedee92.png)

**Comment by mkuron** [comment] 2018-05-12 06:50
Duplicate of #1203, #1310 and #1342. please check existing issues before creating a new one.

**Closed as completed by mkuron** 2018-05-12 06:50 UTC

**Comment by axd** [comment] 2018-05-12 21:55
@mkuron my bad. I did the search on open issues, all those that you mentioned are closed and doesn't have any real solution, I'll wait to someone finds the solution for this matter. 

Regards.
