### ISSUE TITLE
Error: too many recipients from issue - How to Fix

### ISSUE THREAD

**Issue by xoraingroup** [mailcow/mailcow-dockerized#3807] opened 2020-10-15 08:41 UTC
Hi,

 When we are sending bulk emails, we get following error.

Error: too many recipients from x.x.x.x  

x.x.x.x is sender ip.

Do you know how to fix this via configuration?

Thanks

**Comment by xoraingroup** [comment] 2020-10-16 13:15
Ok thank you for putting it invalid. I have to crawl internet to find out why. Its just single email not mailing list that i got this error with.

**Comment by xoraingroup** [comment] 2020-10-16 13:15
If its really invalid, i will close it.

**Comment by andryyy** [comment] 2020-10-16 13:20
Please read the issue template instead of deleting it... :/

**Comment by xoraingroup** [comment] 2020-10-16 19:29
Ok, but i selected blank issue, because i believe its neither a bug nor a feature. Sort of a question if it could be solved.

**Comment by MAGICCC** [comment] 2020-10-16 20:29
Sounds not like a mailcow issue, instead the server you are trying to mail to is blocking it because you are sending mails with too many recipients.
But the best would be too explain us to what mailserver you are sending and how many recipients you have in your mails

**Comment by dragoangel** [comment] 2020-10-17 03:20
Hi @xoraingroup,
Mailcow has a community forum and active telegram channel to get (and provide) help. Check https://github.com/mailcow/mailcow-dockerized#cowmunity

About your issue, did you send one email with more then 20 recipients and up to thousands recipients in it? If yes - this not a mailcow issue, but limitations of mail server where you are trying to deliver this email as MAGICCC said. Servers on web can have many limitations and it something you can't control, but can adapt to. If you want to not get bad IP or domain reputation you better stop practicing such stuff and send for each user dedicated email.

**Comment by xoraingroup** [comment] 2020-10-19 08:02
Thank you very much for response. Actually they were single single emails not multi recipient emails. I cannot reproduce this, I am checking if i can reproduce it again and then will attach the logs here. Thank you for information. Will join the community as well :))

**Comment by xoraingroup** [comment] 2021-04-30 21:38
Ok, so I have found a way of reproducing it. 

Try to create some async app (python or nodejs based) that sends 300+ mails parallel from single machine through mailcow. 

You will see errors from the mailcow will return error after some time. Too many Recipients from ip x.x.x.x (the ip from which the mails are sent). Seems to me some rate limiting by mailcow.

Any idea how to whitelist this ip in mailcow deployment.

**Comment by andryyy** [comment] 2021-04-30 21:50
There are some limits configured in Postfix. Mostly the default limits.

I don't like to help with mass-sending problems. I don't want to assume anything, but I have seen a lot in the past years... It's scary how few mailops actually have the correct agreement from their recipients. I decided not to give support to these kind of questions. :)

It's not a bug though, so I will close it. This would also be better placed in the forum! :)

**Closed as completed by andryyy** 2021-04-30 21:50 UTC
