### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by Proggressiver** [mailcow/mailcow-dockerized#794] opened 2017-12-01 22:23 UTC
Hi,
I have problem with docker-compose.
Error:
`Pulling redis-mailcow (redis:alpine)...
alpine: Pulling from library/redis
ERROR: no matching manifest for linux/amd64 in the manifest list entries`
And I don't know what to do.

Sorry I don't speak English :(

**Comment by mkuron** [comment] 2017-12-01 22:36
Duplicate of https://github.com/docker-library/redis/issues/115 . Something on Docker Hub is currently broken, please try again in a few hours.

**Closed as completed** 2017-12-01 22:36 UTC
