### ISSUE TITLE
docker rspamd container crash after VM move to another platform

### ISSUE THREAD

**Issue by premax** [mailcow/mailcow-dockerized#5531] opened 2023-11-14 13:01 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
After moving VM from AMD to INTEL platform, docker container rspamd v1.92 is crashing and restarting.
Deleting *.hs and *.hsmp files does not help.
Downgrade rspamd from v1.92 to v1.90 fixes the issue.
```

### Logs:

```plain text
mailcowdockerized-rspamd-mailcow-1 | 2023-11-14 12:28:16 #1(main) <56ccd7>; re_cache; rspamd_re_cache_init: loaded hyperscan engine with cpu tune 'generic' and features ''
mailcowdockerized-rspamd-mailcow-1 | 2023-11-14 12:28:16 #1(main) <56ccd7>; re_cache; rspamd_re_cache_load_hyperscan: fatal error: cannot allocate scratch for /var/lib/rspamd//98616ebfe6f338dcd927111eb13a127358b1df4c6ac7c2240d4022ee5cdf3201.hs: -6
```

### Steps to reproduce:

```plain text
1. Run mailcow on VM using AMD platform
2. Migrate VM to INTEL platform
```

### Which branch are you using?

master

### Operating System:

Ubuntu 20.04.6 LTS

### Server/VM specifications:

16G/4 cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

24.0.7

### docker-compose version or docker compose version:

v2.21.0

### mailcow version:

2023-10a

### Reverse proxy:

Traefik

### Logs of git diff:

```plain text
diff --git a/docker-compose.yml b/docker-compose.yml
index 8d84e3a7..f73912e6 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -77,7 +77,7 @@ services:
             - clamd

     rspamd-mailcow:
-      image: mailcow/rspamd:1.92
+      image: mailcow/rspamd:1.90
```

### Logs of iptables -L -vn:

```plain text
-
```

### Logs of ip6tables -L -vn:

```plain text
-
```

### Logs of iptables -L -vn -t nat:

```plain text
-
```

### Logs of ip6tables -L -vn -t nat:

```plain text
-
```

### DNS check:

```plain text
104.18.32.7
172.64.155.249
```

**Comment by DerLinkman** [comment] 2023-11-15 13:32
Duplicate of: https://github.com/mailcow/mailcow-dockerized/issues/4893

**Closed as not planned by DerLinkman** 2023-11-15 13:32 UTC
Labels: bug
