### ISSUE TITLE
SRV DNS from Installation doku and check on website differ

### ISSUE THREAD

**Issue by Drasek** [mailcow/mailcow-dockerized#1384] opened 2018-05-14 12:26 UTC
The installation doku (https://mailcow.github.io/mailcow-dockerized-docs/prerequesite-dns/) tells me to use different DNS names than the check on the website, after installation, which ones are the right ones?

Installation page:

_imap._tcp          IN SRV     0 1 143   mail.example.org.
_imaps._tcp         IN SRV     0 1 993   mail.example.org.
_pop3._tcp          IN SRV     0 1 110   mail.example.org.
_pop3s._tcp         IN SRV     0 1 995   mail.example.org.
_submission._tcp    IN SRV     0 1 587   mail.example.org.
_smtps._tcp         IN SRV     0 1 465   mail.example.org.
_sieve._tcp         IN SRV     0 1 4190  mail.example.org.
_autodiscover._tcp  IN SRV     0 1 443   mail.example.org.
_carddavs._tcp      IN SRV     0 1 443   mail.example.org.
_carddavs._tcp      IN TXT     "path=/SOGo/dav/"
_caldavs._tcp       IN SRV     0 1 443   mail.example.org.
_caldavs._tcp       IN TXT     "path=/SOGo/dav/"

Check in mailcow webinterface:

.in-addr.arpa | PTR | mail.bleib-neugierig.de |  
-- | -- | -- | --
_25._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  
_443._tcp.mail.bleib-neugierig.de | TLSA | 3 1 1 4b52e6ee4dcad5ffb62d3f93233827d9ed6a04f562913277b6741505f7ff0752 |  
_110._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  
_143._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  
_465._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  
_587._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  
_993._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  
_995._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  
_4190._tcp.mail.bleib-neugierig.de | TLSA | 111: Connection refused |  

Thank you very much!

**Comment by mkuron** [comment] 2018-05-14 18:07
Connection refused: Duplicate of #1346. It seems like Mailcow cannot connect to itself, which is due to a misconfiguration on your server.

Names: don't confuse SRV with TLSA records. SRV are not needed by default and TLSA are derived from your certificate, so they cannot be in the docs.

**Closed as completed by mkuron** 2018-05-14 18:07 UTC
