### ISSUE TITLE
sieve crashes dovecot

### ISSUE THREAD

**Issue by flo1212** [mailcow/mailcow-dockerized#5303] opened 2023-07-02 10:19 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
in a user account is in the path /var/lib/docker/volumes/mailcowdockerized_vmail-vol-1/_data/domain.de/user.name/sieve
two files:
sogo.sieve
USER.sieve

Contents:
-------------------------------------------------- ------------------------------------------------
# USER management script
#
# This script includes the various active sieve scripts
# it is AUTOMATICALLY GENERATED. DO NOT EDIT MANUALLY!
#
# For more information, see http://wiki.kolab.org/KEP:14#USER
#

require ["include"];

include :personal "sogo";
-------------------------------------------------- ------------------------------------------------

When restarting dovecot there is this error:
mailcowdockerized-dovecot-mailcow-1 | sievec: Fatal: failed to compile sieve script '/var/vmail/domain.de/user.name/sieve/USER.sieve'

The Dovecot container then no longer has a network and the mail functions are disrupted

The user uses a KDE Sieve editor.
```

### Logs:

```plain text
mailcowdockerized-dovecot-mailcow-1 | sievec: Fatal: failed to compile sieve script '/var/vmail/domain.de/user.name/sieve/USER.sieve'
```

### Steps to reproduce:

```plain text
We do not know how the USER.sieve was created
```

### Which branch are you using?

master

### Operating System:

Debian 11

### Server/VM specifications:

32 GB RAM, 8 Cores

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

24.0.2

### docker-compose version or docker compose version:

v2.7.0

### mailcow version:

2023-05a

### Reverse proxy:

Nginx

### Logs of git diff:

```plain text
nothing
```

### Logs of iptables -L -vn:

```plain text
nothing
```

### Logs of ip6tables -L -vn:

```plain text
nothing
```

### Logs of iptables -L -vn -t nat:

```plain text
nothing
```

### Logs of ip6tables -L -vn -t nat:

```plain text
nothing
```

### DNS check:

```plain text
nothing
```

**Comment by flo1212** [comment] 2023-07-02 15:06
The problem could be reproduced on a test server. The user has with this Sieve Editor
https://software.manjaro.org/package/pim-sieve-editor
uploaded a rules file.
A section of the rule file then creates an additional file USER.sieve when uploading. This file is responsible for the crash.

This area creates the USER.sieve within the rules file

##################

if anyof (address :regex ["to", "cc"] "status.*@yyy\\.net", address :regex ["to", "cc"] "status.*@xxx\\.com" ) {
     if not body :contains "ERROR: Non-zero exit code!" {
       addflag "\\Seen";
       addflag "$label3";
     } else {
       addflag "$label1";
     }
  
     fileinto :create "INBOX/status";
}

##################

**But the real bug is that every user can crash the dovecot container if such or other incompatible Sieve scripts are created.
Mailcow must be able to catch this problem!**

**Comment by xfy777** [comment] 2024-01-09 03:43
Seconding this, this happens quite literally every day randomly for us.

**Comment by dylanjamesdev** [comment] 2024-01-15 08:12
This also happens to me, the container does not restart even with the restart always flag. We have not changed any Sieve scripts.

**Comment by DerLinkman** [comment] 2024-07-11 14:24
Duplicate of https://github.com/mailcow/mailcow-dockerized/issues/4770

**Closed as not planned by DerLinkman** 2024-07-11 14:24 UTC
Labels: bug, investigating
