### ISSUE TITLE
Latest python 3 updates break update.sh

### ISSUE THREAD

**Issue by purejava** [mailcow/mailcow-dockerized#4387] opened 2021-12-16 07:42 UTC
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [x] I understand that not following or deleting the below instructions will result in immediate closure and/or deletion of my issue.
- [x] I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [x] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

## Summary
As my mailcow server runs on Arch linux, I get the latest software packages available.

Installing recent python 3 package updates breaks `update.sh`.

## Logs
```
root@plawetzki ~ # cd /opt/mailcow-dockerized                            
root@plawetzki mailcow-dockerized # ./update.sh 
Checking internet connection... OK
Checking for newer update script...
remote: Enumerating objects: 56, done.
remote: Counting objects: 100% (49/49), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 28 (delta 19), reused 6 (delta 5), pack-reused 0
Unpacking objects: 100% (28/28), 5.24 KiB | 167.00 KiB/s, done.
From https://github.com/mailcow/mailcow-dockerized
   e1db347d..e2b4b6f6  master     -> origin/master
   9c5fd914..3a949269  staging    -> origin/staging
Updated 0 paths from 746631df
Are you sure you want to update mailcow: dockerized? All containers will be stopped. [y/N] y
Great! Native IPv6 NAT is active.
Validating docker-compose stack configuration...
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/bin/docker-compose", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 919, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 518, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for docker-compose

Oh no, something went wrong. Please check the error message above.
```
These are the packages that were updated lastly:
```
[2021-12-13T13:17:07+0100] [ALPM] upgraded python (3.9.9-1 -> 3.10.1-1)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-appdirs (1.4.4-3 -> 1.4.4-6)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-attrs (21.2.0-1 -> 21.2.0-3)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-ply (3.11-8 -> 3.11-10)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-pycparser (2.21-1 -> 2.21-3)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-cffi (1.15.0-1 -> 1.15.0-3)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-six (1.16.0-1 -> 1.16.0-4)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-bcrypt (3.2.0-3 -> 3.2.0-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-msgpack (1.0.2-2 -> 1.0.2-4)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-urllib3 (1.26.7-2 -> 1.26.7-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-chardet (4.0.0-3 -> 4.0.0-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-idna (3.3-1 -> 3.3-3)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-requests (2.26.0-2 -> 2.26.0-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-cachecontrol (1:0.12.6-1 -> 1:0.12.6-4)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-cached-property (1.5.2-3 -> 1.5.2-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-click (8.0.3-1 -> 8.0.3-3)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-colorama (0.4.4-4 -> 0.4.4-6)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-contextlib2 (0.6.0.post1-3 -> 0.6.0.post1-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-cryptography (35.0.0-1 -> 36.0.0-1)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-distlib (0.3.3-2 -> 0.3.3-4)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-more-itertools (8.10.0-1 -> 8.10.0-4)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-ordered-set (4.0.2-3 -> 4.0.2-6)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-pyparsing (2.4.7-3 -> 2.4.7-6)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-packaging (20.9-2 -> 20.9-6)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-setuptools (1:57.4.0-2 -> 1:57.4.0-6)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-distro (1.6.0-2 -> 1.6.0-4)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-websocket-client (0.59.0-1 -> 0.59.0-3)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-docker-pycreds (0.4.0-7 -> 0.4.0-9)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-pynacl (1.4.0-3 -> 1.4.0-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-paramiko (2.7.2-3 -> 2.7.2-5)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-docker (5.0.3-1 -> 5.0.3-3)
[2021-12-13T13:17:07+0100] [ALPM] upgraded python-dockerpty (0.4.1-8 -> 0.4.1-9)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-docopt (0.6.2-9 -> 0.6.2-11)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-dotenv (0.19.2-1 -> 0.19.2-3)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-webencodings (0.5.1-7 -> 0.5.1-9)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-html5lib (1.1-9 -> 1.1-11)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-zipp (3.6.0-1 -> 3.6.0-3)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-importlib-metadata (4.8.1-1 -> 4.8.1-3)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-pyrsistent (0.18.0-1 -> 0.18.0-3)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-jsonschema (3.2.0-4 -> 3.2.0-6)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-tomli (1.2.2-2 -> 1.2.2-4)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-pep517 (0.12.0-2 -> 0.12.0-4)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-progress (1.6-2 -> 1.6-5)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-retrying (1.3.3-10 -> 1.3.3-13)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-resolvelib (0.5.5-2 -> 0.5.5-4)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-toml (0.10.2-3 -> 0.10.2-5)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-pyopenssl (21.0.0-2 -> 21.0.0-5)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-pip (20.3.4-2 -> 20.3.4-4)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-texttable (1.6.4-1 -> 1.6.4-3)
[2021-12-13T13:17:08+0100] [ALPM] upgraded python-yaml (5.4.1.1-2 -> 5.4.1.1-4)
```
## Workaround
Downgrading the python packages to their prior versions makes `update.sh` work again.

## System information

| Question | Answer |
| --- | --- |
| My operating system | Arch linux rolling release |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 16 GB, 4 VCPU |
| Docker Version (`docker version`) | 1:20.10.11-1 (Arch linux) |
| Docker-Compose Version (`docker-compose version`) | 1.29.2-1 (Arch linux) |
| Reverse proxy (custom solution) | No |

**Comment by andryyy** [comment] 2021-12-16 07:53
That’s not a bug in mailcow.

**Comment by purejava** [comment] 2021-12-16 08:06
Well, you'll have `update.sh` stop working as soon as Ubuntu or other distros update their python 3 packages to the versions mentioned above. This will take some time of course, but it will happen.

> That’s not a bug in mailcow.

Why not?
You don't limit the use of mailcow to Ubuntu or other distros that use non-recent versions of software packages and mailcow does not work with current python updates, so I'd recommend to look into this.

**Comment by andryyy** [comment] 2021-12-16 11:51
What is wrong with you?

**Comment by andryyy** [comment] 2021-12-16 11:52
When docker compose stops working on your distro I couldn’t care less.

**Comment by purejava** [comment] 2021-12-16 12:59
> What is wrong with you?

The answer is simple: nothing.
However, with the rough tone here, I will refrain from supporting this project any further.

**Comment by chriscroome** [comment] 2021-12-16 13:32
> you'll have update.sh stop working as soon as Ubuntu or other distros update their python 3 packages to the versions mentioned above. 

There hasn't been a `docker-compose` version 1.x release since May, it looks to me that all the development is going into the Go based version 2.x, see [the releases](https://github.com/docker/compose/releases), my guess is that [Docker Compose version 2.x will be supported by Mailcow](https://github.com/mailcow/mailcow-dockerized/issues/4315) long before any of the tested distros update Python to a version that doesn't work with version 1.x.

**Comment by shiz0** [comment] 2021-12-16 13:34
> Why not? You don't limit the use of mailcow to Ubuntu or other distros that use non-recent versions of software packages and mailcow does not work with current python updates, so I'd recommend to look into this.

Please take a look here:
https://mailcow.github.io/mailcow-dockerized-docs/prerequisite-system/
> We recommend using any distribution listed as supported by Docker CE (check https://docs.docker.com/install/). We test on CentOS 7, Debian 10/11 and Ubuntu 18.04/20.04.

So... basically you are running an unsupported/untested/not recommended configuration. Which is of course your choice to do, but you should expect things to go wrong.
And while it is true, that this MIGHT (there are combinations with versions of other things [Compose!] which may play a role here) occur in other distros as well at some point, I second the opinion that, right now, this is not a bug in mailcow.
Closing.

**Closed as completed by shiz0** 2021-12-16 13:34 UTC
Labels: bug, not-a-bug

**Comment by HorayNarea** [comment] 2021-12-16 17:30
@purejava you need to rebuild docker-compose against python3.10 then it _should_ work:

Download the old [1.29.2 PKGBUILD](https://raw.githubusercontent.com/archlinux/svntogit-community/3238717c2141016a014d0df9e5558f5ddf85d72f/trunk/PKGBUILD), run `makepkg -i` and see if update.sh works now

**Comment by plexxman** [comment] 2021-12-21 21:35
@HorayNarea Thanks for the solution, it worked perfectly for me. Rebuilding docker-compose with makepkg solves the issue.
