### ISSUE TITLE
SOGo change base url

### ISSUE THREAD

**Issue by oncul** [mailcow/mailcow-dockerized#1274] opened 2018-04-16 14:42 UTC
Hi, how can i change /SOGo base url. I modified site.conf but i think i need to modify Sogo HTML files. I newbie on docker

```
In login page js line
var ApplicationBaseURL = '/SOGo/so/';
```

**Comment by mritzmann** [comment] 2018-04-16 14:50
does that help? https://github.com/mailcow/mailcow-dockerized/issues/393

**Comment by mkuron** [comment] 2018-04-16 16:27
Duplicate of #393

**Closed as completed by mkuron** 2018-04-16 16:27 UTC

**Comment by maverick85** [comment] 2020-02-05 18:37
how can a post be duplicate of self?
