### ISSUE TITLE
Different hostnames inside mailcow

### ISSUE THREAD

**Issue by vain90** [mailcow/mailcow-dockerized#2019] opened 2018-11-16 17:47 UTC
I wish I had the option to give multiple hostnames for different purposes.
Three purposes come straight to me:

I'd like a distinction between normal mail hostname, client configuration hostname, and the system mail hostname.

**Mail hostname:**
Used as the real server hostname. Need to be RFC conform (e.g. mail.xyz.de or mx01.xyz.de)

**Client configuration hostname:**
Used to set the hostname in the autoconfig.php and mobileconfig.php (e.g. imap.xyz.de and smtp.xyz.de)

**System mail hostname:**
Used to determine with which domain system mails are sent.
Sure, you can also enter this manually each time in the from field.
But I think it would be more elegant if this was predefined according to your needs.

**Comment by mkuron** [comment] 2018-11-16 18:54
Duplicate of #1723. A number of related tickets can be found in #528.

**Closed as completed by mkuron** 2018-11-16 18:54 UTC
