### ISSUE TITLE
Duplicate of  #6143

### ISSUE THREAD

**Issue by davidschoefberger** [mailcow/mailcow-dockerized#6148] opened 2024-11-08 18:01 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [x] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
How can #6143 not be a bug? After the upgrade mailcow was not working properly and manual intervention is required. Please elaborate on that.
```

### Logs:

```plain text
See #6143
```

### Steps to reproduce:

```plain text
See #6143
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

See #6143

### Server/VM specifications:

See #6143

### Is Apparmor, SELinux or similar active?

See #6143

### Virtualization technology:

See #6143

### Docker version:

See #6143

### docker-compose version or docker compose version:

See #6143

### mailcow version:

See #6143

### Reverse proxy:

See #6143

### Logs of git diff:

```plain text
See #6143
```

### Logs of iptables -L -vn:

```plain text
See #6143
```

### Logs of ip6tables -L -vn:

```plain text
See #6143
```

### Logs of iptables -L -vn -t nat:

```plain text
See #6143
```

### Logs of ip6tables -L -vn -t nat:

```plain text
See #6143
```

### DNS check:

```plain text
See #6143
```

**Comment by FreddleSpl0it** [comment] 2024-11-09 09:02
Back when Spamhaus decided to provide their blocklist only with a valid DQS key, there was some confusion about how to implement this in mailcow. Here are some relevant commits:

- [Commit 03b7a8d](https://github.com/mailcow/mailcow-dockerized/commit/03b7a8d639adad2d380b235955c93c7e508d5e2e)
- [Commit 9f39af4](https://github.com/mailcow/mailcow-dockerized/commit/9f39af46aa9952d192cb1aaea47a3785eb088fc7)
- [Commit c45684b](https://github.com/mailcow/mailcow-dockerized/commit/c45684b986fbe2f11a492ba44a82351acb097fed)
- [Commit 0f33797](https://github.com/mailcow/mailcow-dockerized/commit/0f337971ff12b89805bb58b14b858c74e8fdb7dd)

With [this commit](https://github.com/mailcow/mailcow-dockerized/commit/03b7a8d639adad2d380b235955c93c7e508d5e2e), a broken `data/conf/dns_blocklists.cf` file was generated back then due to incorrect indentation. After adding [this commit](https://github.com/mailcow/mailcow-dockerized/commit/c53bf85480697c24912214bf74a1718a73052a06), Postfix started throwing parsing errors because of the malformed `data/conf/dns_blocklists.cf`.

Since this file can be edited by users, we can't automatically delete it at container startup. Users experiencing this issue will need to delete the file manually. It’s not difficult and has been noted in our [release notes](https://github.com/mailcow/mailcow-dockerized/releases/tag/2024-11).

So bug was caused by the generation of a broken `data/conf/dns_blocklists.cf` file, but this issue has already been fixed in [this commit](https://github.com/mailcow/mailcow-dockerized/commit/c45684b986fbe2f11a492ba44a82351acb097fed).

**Closed as completed by FreddleSpl0it** 2024-11-09 09:02 UTC
Labels: bug
