### ISSUE TITLE
DMARC reporting uses wrong date

### ISSUE THREAD

**Issue by snhrdt** [mailcow/mailcow-dockerized#4811] opened 2022-10-22 21:10 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

I found a little oddity with DMARC reporting in rspamd in mailcow; I enabled DMARC reporting today, let everything run for a couple of hours and was wondering that no reports are being sent out.

The reason seems to be that the date that rspamd-mailcow is using for the DMARC report is not the current date, but two days ago. I verified this by getting into the running container and invoking rspamadm manually.

### Logs

```bash
Output of the command described below:


root@rspamd:/# date
Sat Oct 22 22:47:46 CEST 2022
root@rspamd:/# rspamadm dmarc_report               
No reports for 20221020
```

Of course, I am not surprised that there is no data for 2 days ago (20221020) since I only enabled DMARC reporting today (20221022).

Invoking dmarc_report with today date works without any issues:
```
root@rspamd:/# rspamadm dmarc_report 20221022
previous last report date is 1666306800
Process date 20221022
cannot resolve _dmarc.gutscheinmailer24.de: no records with this name
process reporting domain gutscheinmailer24.de: nil
Cannot process reports for domain gutscheinmailer24.de; invalid dmarc record
cannot resolve _dmarc.dealeffect.de: no records with this name
process reporting domain dealeffect.de: nil
Cannot process reports for domain dealeffect.de; invalid dmarc record
got DMARC record: v=DMARC1; p=none; sp=quarantine; rua=mailto:mailauth-reports@google.com, tld_flag=false, processed={[p] = none, [sp] = quarantine, [rua] = mailto:mailauth-reports@google.com}
process reporting domain gmail.com: {[pct] = 100, [adkim] = r, [aspf] = r, [p] = none, [sp] = quarantine, [rua] = {[1] = mailauth-reports@google.com}}
got xml: <?xml version="1.0" encoding="UTF-8" ?>
<feedback>
  <report_metadata>
```

(data cut for anonymity reasons)

### Steps to reproduce

1. `docker compose exec rspamd-mailcow bash`
2. `rspamadm dmarc_report --help`
3. `# Read the help text displayed - dmarc_report should use the current date by default`
4. `rspamadm dmarc_report`
5. `# See that the command outputs "No reports for $SOME_DATE". This date is two days ago, not today as it should be`
6. `rspamadm dmarc_report $YYYYMMDD`
7. `# See that dmarc_report works as it should if you pass in today's date in YYYYMMDD format - although this should be its default behaviour`

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 22.04 |
| Is Apparmor, SELinux or similar active? | No. |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | None |
| Server/VM specifications (Memory, CPU Cores) | 128 GB, 6C/12T |
| Docker version (`docker version`) | 20.10.14 |
| docker-compose version (`docker-compose version`) | v2.10.2 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-09a |
| Reverse proxy (custom solution) | dockerized nginx |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
Problem is not network related
```

ip6tables -L -vn:
```
Problem is not network related
```

iptables -L -vn -t nat:
```
Problem is not network related
```

ip6tables -L -vn -t nat:
```
Problem is not network related
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
Problem is not DNS related
```

**Comment by snhrdt** [comment] 2022-10-22 21:18
My current workaround is to attach `date +%Y%m%d` to the ofelia command in `docker-compose.override.yml` like this:

```
---
version: '2.1'

services:
  rspamd-mailcow:
    environment:
      - MASTER=${MASTER:-y}
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.rspamd_dmarc_reporting.schedule: "@hourly"
      ofelia.job-exec.rspamd_dmarc_reporting.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/bin/rspamadm dmarc_report `date +%Y%m%d` > /var/lib/rspamd/dmarc_reports_last_log 2>&1 || exit 0\""
  ofelia-mailcow:
    depends_on:
      - rspamd-mailcow
```

Let's see whether this works.

**Comment by snhrdt** [comment] 2022-10-23 13:53
**Update:** The 2-day gap between current date and DMARC reporting date continues.
```
root@node ~/mailcowdockerized # docker compose exec rspamd-mailcow date -r /var/lib/rspamd/dmarc_reports_last_log
Sun Oct 23 15:00:01 CEST 2022
root@node ~/mailcowdockerized # docker compose exec rspamd-mailcow cat /var/lib/rspamd/dmarc_reports_last_log
No reports for 20221021
```

The workaround I described above does *not* work, unfortunately. Apparently, the date is not parsed dynamically. I will now create a cronjob on the host, calling
```
docker compose exec rspamd-mailcow rspamadm dmarc_report $(/bin/date +%Y%m%d)
```

Still, I would be interested in understanding and fixing the original issue and executing the DMARC reporting from within mailcow.

**Comment by MAGICCC** [comment] 2022-10-23 16:37
Indeed the `rspamadm dmarc_report` doesn't report the right date, but since it's rspamd I suppose we may rise a ticket there?

**Comment by snhrdt** [comment] 2022-10-23 21:29
@MAGICCC I am not sure whether this behavior originates with the upstream package or is due to some local config; I would also suggest to correct inherited issues in a transparent manner until they are fixed upstream.

**Comment by MAGICCC** [comment] 2022-10-24 16:04
I guess not, I have the same issue. Will dig deeper when I have some time

**Comment by dragoangel** [comment] 2022-10-26 12:36
Yep, I think it should be reported to Vsevolod, till the fix as a workaround we can pass the current `date +%Y%m%d` in docker-compose.override.yaml where this command triggered by cron.

**Comment by MAGICCC** [comment] 2022-11-02 17:30
I was testing with rspamd 3.3 and there it's fine.
```
root@rspamd:/# date
Wed Nov  2 18:23:01 CET 2022
root@rspamd:/# rspamadm dmarc_report
No reports for 20221101
```

Yes it's not the actual day, but it makes sense to use the last day because the current day is not over yet

**Comment by snhrdt** [comment] 2022-11-02 19:54
Well, the man page says it should be the current day, not yesterday or the
day before yesterday. Either the tool works incorrectly, or the man page
needs to be updated.

Apart from that: If you have a high-volume mail server, you might want to
send out dmarc reports more often than once per day - and then it is a lot
better to have "current day" as the default reporting date.

**Comment by dragoangel** [comment] 2022-11-02 20:53
> Apart from that: If you have a high-volume mail server, you might want to
send out dmarc reports more often than once per day - and then it is a lot
better to have "current day" as the default reporting date.

This one in most cases not needed. But if you run it for example `every 12h` it not change anything. Rspamd read records from redis and mark them as reported, next time it will not send report for them again.

> **Update:** The 2-day gap between current date and DMARC reporting date continues.

This one is interesting, did you try read ofelia logs after adjusting `ofelia.job-exec.rspamd_dmarc_reporting.command`? Maybe it's just not run the schedule properly? Because it can't be "not parsed dynamically". ``` echo `date +%Y%m%d` ``` - is a bash, it can't be "static" when it's command 😅

**Comment by wmtech-1** [comment] 2022-11-08 08:43
This is not a bug in Mailcow, but a slight documentation issue caused by wrong documentation at Rspamd.

DMARC reporting is a relatively new feature in Rspamd and there are discussions on how to clarify the reporting run (e.g. adding options for --today and --yesterday). Their documentation that running "dmarc_report" processes the report for the current date is wrong. It produces the report for 2 days before today. This is intentional because most people run the report once daily and the last full day should be processed. However, some people run the report exactly at midnight (where not all mail from the seconds before may be processed), so they decided to choose "2 days" before today as the target period just to be sure.

So for Mailcow users that means you should run the dmarc reports not exactly at midnight ("every 24h" does not run at midnight) and add the option to process the day before today in the report. Changing the Ofelia job line in docker-compose.override.yml to 

       ofelia.job-exec.rspamd_dmarc_reporting.command: "/bin/bash -c \"[[ $${MASTER} == y ]] && /usr/bin/rspamadm dmarc_report $(date --date yesterday '+%Y%m%d') > /var/lib/rspamd/dmarc_reports_last_log 2>&1 || exit 0\""

and running that "@every 24h" is perfectly okay. Maybe Mailcow wants to change its documentation.

If you have a large mail volume and want to run the dmarc reporting more than once a day, you can run it with
`/usr/bin/rspamadm dmarc_report $(date '+%Y%m%d')` to process the current day, but you have to make sure that the first run on each day also processes the last report from the day before, so it needs to be started twice, one time with `$(date --date yesterday '+%Y%m%d')` and then with `$(date '+%Y%m%d')`.

Hope this helps. ;-)

**Comment by dragoangel** [comment] 2022-11-08 10:26
Hi @wmtech-1 thanks for the details, can you check if the text is clear enough (and has no grammar errors)? Same for code samples.

Created PR for EN version of docs: https://github.com/mailcow/mailcow-dockerized-docs/pull/493

After your reply, @DerLinkman can translate it to Deutsch I think 😊

**Comment by dragoangel** [comment] 2022-11-08 10:34
@snhrdt can you check if https://github.com/mailcow/mailcow-dockerized-docs/blob/c36786057544de0597e614ae49ab0bd289fa6f40/docs/post_installation/firststeps-dmarc_reporting.en.md works as desired please?

**Comment by wmtech-1** [comment] 2022-11-08 13:34
We run this In production for a long time now. It works as expected.

**Comment by dragoangel** [comment] 2022-11-08 13:45
> We run this In production for a long time now. It works as expected.

I mean text of PR in the link above 😊

**Comment by dragoangel** [comment] 2022-11-08 13:49
Resolved by #493

**Closed as completed** 2022-11-08 13:50 UTC
Labels: bug

**Comment by snhrdt** [comment] 2022-11-08 14:11
Can do so tonight, after business hours.

Thanks @wmtech-1 for the very detailed response - it makes a lot of sense
what you write.

**Comment by MAGICCC** [comment] 2022-11-08 14:17
Indeed thanks

**Comment by snhrdt** [comment] 2022-11-17 22:14
> @snhrdt can you check if https://github.com/mailcow/mailcow-dockerized-docs/blob/c36786057544de0597e614ae49ab0bd289fa6f40/docs/post_installation/firststeps-dmarc_reporting.en.md works as desired please?

Hey @dragoangel - that works as expected, as @wmtech-1 correctly states. Sorry for the late answer.
