### ISSUE TITLE
Quarantine notifications no longer sent with 2022-08(a)

### ISSUE THREAD

**Issue by tmkis2** [mailcow/mailcow-dockerized#4743] opened 2022-09-04 21:13 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

Quarantine Mails still works but no notification is sent to users mailbox regardless of setting it to 1 hour, 24 hours or something else

### Logs

```bash
don't know which logs to check for this
```

### Steps to reproduce

Enable Quarantine notifications to 1 hour - get some quarantined messages - wait

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 LTS |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8 GB RAM/4 Cores |
| Docker version (`docker version`) | 20.10.17 |
| docker-compose version (`docker-compose version`) | v2.10.2 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-08a |
| Reverse proxy (custom solution) | NO |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
diff --git a/create_cold_standby.sh b/create_cold_standby.sh
index 924339af..9d7bb0ed 100755
--- a/create_cold_standby.sh
+++ b/create_cold_standby.sh
@@ -2,6 +2,6 @@
 
 export REMOTE_SSH_KEY=/root/.ssh/id_rsa
 export REMOTE_SSH_PORT=22
-export REMOTE_SSH_HOST=my.remote.host
+export REMOTE_SSH_HOST=5.180.192.196
 
 /opt/mailcow-dockerized/helper-scripts/_cold-standby.sh
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index a445b60c..1f3a565d 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,7 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks
 
 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = mail.tmkis.com
+submission_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
+smtps_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
diff --git a/data/conf/rspamd/custom/global_mime_from_whitelist.map b/data/conf/rspamd/custom/global_mime_from_whitelist.map
index 3c872889..844c6b2a 100644
--- a/data/conf/rspamd/custom/global_mime_from_whitelist.map
+++ b/data/conf/rspamd/custom/global_mime_from_whitelist.map
@@ -1 +1,2 @@
-# /.+example\.com/i
+# /.+example\.com/i^M
+/.+tmkis\.email/i
diff --git a/data/conf/rspamd/local.d/multimap.conf b/data/conf/rspamd/local.d/multimap.conf
index 17ada99e..1792e622 100644
--- a/data/conf/rspamd/local.d/multimap.conf
+++ b/data/conf/rspamd/local.d/multimap.conf
@@ -179,3 +179,4 @@ BAD_SUBJECT_00 {
   score = 6.0;
   symbols_set = ["BAD_SUBJECT_00"];
 }
+
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index 1d6a9d3f..557250c8 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -5,7 +5,7 @@
         PrivateDAndTViewer
     );
 
-    WOWorkersCount = "20";
+    WOWorkersCount = "80";
     SOGoACLsSendEMailNotifications = YES;
     SOGoAppointmentSendEMailNotifications = YES;
     SOGoDraftsFolderName = "Drafts";
@@ -37,7 +37,7 @@
     WOPort = "0.0.0.0:20000";
     SOGoMemcachedHost = "memcached";
 
-    SOGoLanguage = English;
+    SOGoLanguage = German;
     SOGoMailAuxiliaryUserAccountsEnabled = YES;
     SOGoMailCustomFromEnabled = YES;
     SOGoMailingMechanism = smtp;
@@ -60,7 +60,7 @@
     WONoDetach = YES;
 
     SOGoIMAPAclConformsToIMAPExt = Yes;
-    SOGoPageTitle = "SOGo Groupware";
+    SOGoPageTitle = "TMKIS Groupware";
     SOGoFirstDayOfWeek = "1";
 
     SOGoSieveFolderEncoding = "UTF-8";
@@ -92,3 +92,4 @@
   //WODontZipResponse = YES;
     WOLogFile = "/dev/sogo_log";
 }
+
diff --git a/data/web/autoconfig.php b/data/web/autoconfig.php
index 95952df0..b1fc2bd8 100644
--- a/data/web/autoconfig.php
+++ b/data/web/autoconfig.php
@@ -29,8 +29,8 @@ header('Content-Type: application/xml');
 <clientConfig version="1.1">
     <emailProvider id="<?=$mailcow_hostname; ?>">
       <domain>%EMAILDOMAIN%</domain>
-      <displayName>A mailcow mail server</displayName>
-      <displayShortName>mail server</displayShortName>
+      <displayName>TMKIS Mail-Server</displayName>
+      <displayShortName>Mail-Server</displayShortName>
 
       <incomingServer type="imap">
          <hostname><?=$autodiscover_config['imap']['server']; ?></hostname>
diff --git a/docker-compose.yml b/docker-compose.yml
index 9fbfef59..5f4e6251 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -580,36 +580,6 @@ services:
           aliases:
             - ofelia
 
-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
-
 networks:
   mailcow-network:
     driver: bridge
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
Chain INPUT (policy ACCEPT 113K packets, 44M bytes)
 pkts bytes target     prot opt in     out     source               destination         
1310K 2484M MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  22M  146G MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  22M  146G DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  22M  146G DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  20M  146G ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 599K   43M DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0           
1593K  603M ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0           
 567K   41M ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 156K packets, 12M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.4           tcp dpt:8983
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.9           tcp dpt:3306
 1826  109K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:443
  346 19720 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:80
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345
    1    52 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190
  288 17200 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995
 2606  164K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993
  767 47085 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143
   49  2860 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110
  234 13000 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:587
 3269  194K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:465
 2157  125K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:25

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
1593K  603M DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
  33M  157G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
2707K 1188M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  33M  157G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination      
```

ip6tables -L -vn:
```
Chain INPUT (policy ACCEPT 17077 packets, 1189K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 569K  126M MAILCOW    all      *      *       ::/0                 ::/0                

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
3899K 2291M MAILCOW    all      *      *       ::/0                 ::/0                
3900K 2291M DOCKER-ISOLATION-STAGE-1  all      *      *       ::/0                 ::/0                
2715K 1573M ACCEPT     all      *      br-mailcow  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
 180K   14M DOCKER     all      *      br-mailcow  ::/0                 ::/0                
1006K  704M ACCEPT     all      br-mailcow !br-mailcow  ::/0                 ::/0                
 145K   11M ACCEPT     all      br-mailcow br-mailcow  ::/0                 ::/0                
    0     0 ACCEPT     all      *      docker0  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all      *      docker0  ::/0                 ::/0                
    0     0 ACCEPT     all      docker0 !docker0  ::/0                 ::/0                
    0     0 ACCEPT     all      docker0 docker0  ::/0                 ::/0                

Chain OUTPUT (policy ACCEPT 15737 packets, 1228K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
 7321  793K ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::e  tcp dpt:443
   69  5520 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::e  tcp dpt:80
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:4190
  966 76728 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:995
 3918  323K ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:993
  296 23943 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:143
   47  3948 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:110
   79  6332 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:587
  968 76480 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:465
  900 72000 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:25

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
1006K  704M DOCKER-ISOLATION-STAGE-2  all      br-mailcow !br-mailcow  ::/0                 ::/0                
    0     0 DOCKER-ISOLATION-STAGE-2  all      docker0 !docker0  ::/0                 ::/0                
7157K 5556M RETURN     all      *      *       ::/0                 ::/0                

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      br-mailcow  ::/0                 ::/0                
    0     0 DROP       all      *      docker0  ::/0                 ::/0                
1987K 2516M RETURN     all      *      *       ::/0                 ::/0                

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination         
```

iptables -L -vn -t nat:
```
Chain PREROUTING (policy ACCEPT 617K packets, 40M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 119K 6830K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 14774 packets, 846K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 28 packets, 2089 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 227K packets, 16M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 544K   45M MASQUERADE  all  --  *      !br-mailcow  172.22.1.0/24        0.0.0.0/0           
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.4           172.22.1.4           tcp dpt:8983
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.249         172.22.1.249         tcp dpt:6379
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.9           172.22.1.9           tcp dpt:3306
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:80
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:12345
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:4190
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:995
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:993
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:143
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:110
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:587
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:465
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:25

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    3   180 RETURN     all  --  br-mailcow *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:18983 to:172.22.1.4:8983
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:7654 to:172.22.1.249:6379
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.9:3306
 1830  110K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.22.1.11:443
  346 19720 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.22.1.11:80
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.250:12345
    1    52 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.250:4190
  288 17200 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.250:995
 2619  165K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.250:993
  767 47085 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.250:143
   49  2860 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.250:110
  251 13864 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.253:587
 3280  195K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.253:465
 2170  125K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.253:25
```

ip6tables -L -vn -t nat:
```
Chain PREROUTING (policy ACCEPT 158K packets, 14M bytes)
 pkts bytes target     prot opt in     out     source               destination         
55918 5252K DOCKER     all      *      *       ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 23 packets, 4017 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 3 packets, 240 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all      *      *       ::/0                !::1                  ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 45538 packets, 3858K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 178K   18M MASQUERADE  all      *      !br-mailcow  fd4d:6169:6c63:6f77::/64  ::/0                
    0     0 MASQUERADE  all      *      !docker0  fd00:dead:beef:c0::/80  ::/0                
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::e  fd4d:6169:6c63:6f77::e  tcp dpt:443
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::e  fd4d:6169:6c63:6f77::e  tcp dpt:80
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:4190
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:995
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:993
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:143
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:110
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:587
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:465
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:25

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
  624 49920 RETURN     all      br-mailcow *       ::/0                 ::/0                
    0     0 RETURN     all      docker0 *       ::/0                 ::/0                
 7322  792K DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:443 to:[fd4d:6169:6c63:6f77::e]:443
   69  5520 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:80 to:[fd4d:6169:6c63:6f77::e]:80
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:4190 to:[fd4d:6169:6c63:6f77::f]:4190
  967 76808 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:995 to:[fd4d:6169:6c63:6f77::f]:995
 3923  323K DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:993 to:[fd4d:6169:6c63:6f77::f]:993
  296 23943 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:143 to:[fd4d:6169:6c63:6f77::f]:143
   47  3948 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:110 to:[fd4d:6169:6c63:6f77::f]:110
   79  6332 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:587 to:[fd4d:6169:6c63:6f77::10]:587
  969 76560 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:465 to:[fd4d:6169:6c63:6f77::10]:465
  901 72080 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:25 to:[fd4d:6169:6c63:6f77::10]:25
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
151.101.129.69
151.101.1.69
151.101.65.69
151.101.193.69
```

**Comment by erichk4** [comment] 2022-09-05 09:04
same here, sending quarantine mail notifications stopped after upgrade to 2022-08(a)

**Update:**
maybe related to quarantine_notify.pid:

ofelia logs:
mailcowdockerized-ofelia-mailcow-1  | 2022-09-03T21:32:55.573+02:00 [32m common.go:125 ▶ NOTICE[0m [Job "dovecot_quarantine" (f9251ecfa21b)] StdOut: **/tmp/quarantine_notify.pid already exists, exiting**
mailcowdockerized-ofelia-mailcow-1  | 2022-09-03T21:32:55.573+02:00 [32m common.go:125 ▶ NOTICE[0m [Job "dovecot_quarantine" (f9251ecfa21b)] Finished in "558.809894ms", failed: false, skipped: false, error: none

in quarantine_notify.py ~#22
```
pidfile = "/tmp/quarantine_notify.pid"

if os.path.isfile(pidfile):
  print("%s already exists, exiting" % (pidfile))
  sys.exit()
```

so quarantine_notify.py never fully runs...

**Update II:**
restarted dovecot and then the ofelia container, quarantine_notify.pid file is gone...

mailcowdockerized-ofelia-mailcow-1  | 2022-09-06T15:28:49.014+02:00  common.go:125 ▶ NOTICE [Job "dovecot_quarantine" (37449573657f)] Started - /bin/bash -c "[[ ${MASTER} == y ]] && /usr/local/bin/gosu vmail /usr/local/bin/quarantine_notify.py || exit 0"

but after the first run of quarantine_notify.py the quarantine_notify.pid file is not deleted... 

**Update III:**

found this error is the ofelia-log:

mailcowdockerized-ofelia-mailcow-1  | 2022-09-06T09:32:55.227+02:00 [31m common.go:121 ▶ ERROR[0m [Job "dovecot_quarantine" (ddea2612b22b)] StdOut: 1273 (HY000): Unknown collation: 'utf8mb4_0900_ai_ci' - trying again...

followed by thousand's of this lines:
mailcowdockerized-ofelia-mailcow-1  | Character set 'utf8' unsupported - trying again...

maybe: https://stackoverflow.com/questions/73244027/character-set-utf8-unsupported-in-python-mysql-connector

**Comment by erichk4** [comment] 2022-09-08 14:01
sorry, still not working with latest Amoogust Update 2022 Revision B...

**ofelia-log:**
mailcowdockerized-ofelia-mailcow-1  | 2022-09-08T15:49:57.667+02:00 [32m common.go:125 ▶ NOTICE[0m [Job "dovecot_quarantine" (b7be5efa6c49)] StdOut: /tmp/quarantine_notify.pid already exists, exiting
mailcowdockerized-ofelia-mailcow-1  | 2022-09-08T15:49:57.667+02:00 [32m common.go:125 ▶ NOTICE[0m [Job "dovecot_quarantine" (b7be5efa6c49)] Finished in "646.59802ms", failed: false, skipped: false, error: none

**pip3 show mysql-connector-python**
Name: mysql-connector-python
**Version: 8.0.30**
Summary: MySQL driver written in Python
Home-page: http://dev.mysql.com/doc/connector-python/en/index.html
-> **https://stackoverflow.com/questions/73244027/character-set-utf8-unsupported-in-python-mysql-connector**
-> **https://downloads.mysql.com/docs/connector-python-relnotes-en.pdf**

**Comment by tom666-debug** [comment] 2022-09-08 17:22
Confirmed, same here with version 2022-08a and 2022-08b as well

**Comment by tmkis2** [comment] 2022-09-08 17:42
Confirmed: Still **doesn't** work in 2022-08b

**Comment by joundso** [comment] 2022-09-13 20:09
Confirmed: Same here on 20.04.5 LTS, mailcow 2022-08b.

**Comment by MAGICCC** [comment] 2022-09-14 16:51
We could downgrade mysql-connector-python to 8.0.29, but I dont like having to pinpoint such release
We could also upgrade mariadb I guess - didnt test it yet
We could also install mariadb pip package and use this to connect to a mariadb server - works too on my side

Will dig a bit deeper on this

@DerLinkman any suggestion which part we should use?

**Comment by DerLinkman** [comment] 2022-09-14 17:02
Does it come from mariadb? Or the connector in general?

**Comment by MAGICCC** [comment] 2022-09-14 17:10
Basicly the current latest release of mysql-connector-python is aliasing utf8 to utf8mb4 which the mariadb doesn't handle at the moment. I am not sure if an update to a newer mariadb will solve this issue. If we downgrade the connector the alias is not there and we can connect to the DB. If we upgrade the DB we may  can connect (need to check newer changelogs first).
If we use the [mariadb connector](https://pypi.org/project/mariadb/) we don't need to set a charset, but the image will be a bit bigger because of the dependencies we need [to install](https://mariadb.com/docs/connect/programming-languages/c/install/#connector-c-install-repo-configure-cs)

**Comment by DerLinkman** [comment] 2022-09-14 17:14
We should consider a update to mariadb:10.6 anyway in the near future so i would say we´ll try this. With a lot of tests of course.

**Comment by DerLinkman** [comment] 2022-09-14 17:56
I´ll try a update on my test maschine tomorrow but i doubt that it will work flawlessly.

**Comment by DerLinkman** [comment] 2022-09-15 11:24
@MAGICCC if you take a look at the init-db.inc.php https://github.com/mailcow/mailcow-dockerized/blob/master/data/web/inc/init_db.inc.php you can see that the tables are already using utf8mb4 as the default char set.

**Comment by MAGICCC** [comment] 2022-09-15 18:36
Indeed @DerLinkman..
That's why I just gave it a second shot with the latest mysql-connector-python package and when using following line in `quarantine_notify.py` the script can connect to the DB and fetches the mails
```diff
- cnx = mysql.connector.connect(unix_socket = '/var/run/mysqld/mysqld.sock', user=os.environ.get('DBUSER'), passwd=os.environ.get('DBPASS'), database=os.environ.get('DBNAME'), charset="utf8")
+ cnx = mysql.connector.connect(unix_socket = '/var/run/mysqld/mysqld.sock', user=os.environ.get('DBUSER'), passwd=os.environ.get('DBPASS'), database=os.environ.get('DBNAME'), charset="utf8mb4", collation="utf8mb4_general_ci")
```

Would be nice if you can check it on your side too

**Comment by DerLinkman** [comment] 2022-09-19 12:22
Yes that works perfectly. Can you create a PR about that?

**Comment by DerLinkman** [comment] 2022-09-19 12:25
> We should consider a update to mariadb:10.6 anyway in the near future so i would say we´ll try this. With a lot of tests of course.

Currently testing this. Right now it looks good.

**Comment by DerLinkman** [comment] 2022-09-19 12:33
> > We should consider a update to mariadb:10.6 anyway in the near future so i would say we´ll try this. With a lot of tests of course.
> 
> Currently testing this. Right now it looks good.

Would apprectiate it if you could also test it (update mariadb:10.5 to 10.6 in docker-compose.yml)

**Comment by MAGICCC** [comment] 2022-09-19 17:34
Done, tested it with mariadb:10.6

**Comment by DerLinkman** [comment] 2022-09-19 17:34
Ok 10.6 works for you flawlessly? I mean especially the upgrade process.

**Comment by MAGICCC** [comment] 2022-09-19 17:38
Yes, I pulled the image, did a compose down and a up -d and it upgraded fine. We should test it with some users if they have some test boxes too

**Comment by DerLinkman** [comment] 2022-09-19 17:39
Yeah definately. Probably doing this inside of nightly maybe.

**Comment by MrHappy** [comment] 2022-09-26 10:11
Is there any update on this? :)

**Comment by expertaz-zz** [comment] 2022-09-26 12:38
Confirmed: Same here on Debian 11 Bullseye, mailcow 2022-08b.

**Comment by DerLinkman** [comment] 2022-09-26 16:39
Will be fixed in 2022-09 (probably tomorrow)

**Comment by MAGICCC** [comment] 2022-09-27 15:54
Fixed in https://github.com/mailcow/mailcow-dockerized/releases/tag/2022-09

**Closed as completed by MAGICCC** 2022-09-27 15:54 UTC
Labels: bug, investigating
