### ISSUE TITLE
./generate_config.sh -> tr: write error: Broken pipe

### ISSUE THREAD

**Issue by tonyblue2** [mailcow/mailcow-dockerized#3514] opened 2020-05-03 06:05 UTC
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

After I start "./generate_config.sh" I get the error message "tr: write error: Broken pipe"

**Docker container logs of affected containers**:

./generate_config.sh
Press enter to confirm the detected value ‘[value]’ where applicable or enter a custom value.
Mail server hostname (FQDN) - this is not your mail domain, but your mail servers hostname: testmail.ddnss.de
Timezone [Europe/Berlin]:
tr: write error: Broken pipe
tr: write error
tr: write error: Broken pipe
tr: write error

**Reproduction of said bug**:

I installed mailcow in a new Ubuntu 18.04 LTS Installation. It runs in a proxmox LXC Container.

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04 LTS |
| Is Apparmor, SELinux or similar active? | I dont know |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | It is a Proxmox LXC container unprivileged |
| Server/VM specifications (Memory, CPU Cores) | 4.0 GiB Ram, 2 Cores |
| Docker Version (`docker version`) | 19.03.8 |
| Docker-Compose Version (`docker-compose version`) | 1.25.5 |
| Reverse proxy (custom solution) | yes |

- Output of `git diff origin/master`, any other changes to the code? If so, **please post them**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

**Comment by andryyy** [comment] 2020-05-03 07:15
Probably no rights accessing /dev/urandom, but it will not work on LXC properly anyway. 

![image](https://user-images.githubusercontent.com/2972950/80908241-9e254780-8d1e-11ea-9c24-6648d25d07b4.png)

**Comment by MAGICCC** [comment] 2020-05-03 11:24
Dupe of https://community.mailcow.email/d/97-generate-configsh-tr-write-error-broken-pipe

**Closed as completed by MAGICCC** 2020-05-03 11:24 UTC
