### ISSUE TITLE
update password database mailcowUI error

### ISSUE THREAD

**Issue by NetIds** [mailcow/mailcow-dockerized#1535] opened 2018-07-03 10:10 UTC
When i add an SSHA512 password from an other server and replace it into the database table "mailbox", I can not login anymore on the Mailcow UI, but I can login into SOGo with the password from the other server.

Also when I save an SSHA265 password, it is the same, i can login into SOGo but not into MailcowUI

Can someone help me out to fix this issue?

**Comment by mkuron** [comment] 2018-07-03 16:06
Duplicate of #1481. Please check existing issues before creating a new one.

**Closed as completed by mkuron** 2018-07-03 16:06 UTC
