### ISSUE TITLE
dockerhub has wrong link to documentation

### ISSUE THREAD

**Issue by JayBigGuy10** [mailcow/mailcow-dockerized#2306] opened 2019-02-12 05:05 UTC
https://hub.docker.com/r/mailcow/dovecot contains a link to the wiki which returns a 404

**Comment by MAGICCC** [comment] 2019-02-12 09:16
Dupe of https://github.com/mailcow/mailcow-dockerized/issues/1980

**Closed as completed by MAGICCC** 2019-02-12 09:16 UTC
Labels: duplicate
