### ISSUE TITLE
Incoming sync as normal incoming mail (with absence message)

### ISSUE THREAD

**Issue by Xadagain** [mailcow/mailcow-dockerized#1240] opened 2018-04-05 11:57 UTC
We want tu run our mailcow completly behind another mailserver.

All outgoing mails are going over a relay-host.

But incoming mails (with the sync feature) are not been registered as incoming mail. So when we set an absence message in Sogo, the absence message is never being sended. The mails are also not checked from raspmd.

Is there a way tu turn on spam checks and absence messages for mails from sync jobs?

Otherwise i have to try an exterior fetchmail docker-deamon wich sends mails with smtp to mailcow.

**Comment by mkuron** [comment] 2018-04-05 16:14
Duplicate of #220. there is currently no workaround.

**Closed as completed by mkuron** 2018-04-05 16:14 UTC
