### ISSUE TITLE
Docker images in different architectures

### ISSUE THREAD

**Issue by jacarvajalsoto** [mailcow/mailcow-dockerized#4520] opened 2022-03-25 10:54 UTC
### Summary

I'm not sure if this is a bug report, feature request or support. I was trying to install mailcow, when I lunched the docker-compose I started to get the following issue in several images:

` standard_init_linux.go:228: exec user process caused: exec format error`

Through little digging, I found out that the problem is that the several images are only available on Linux/amd64 I'm trying to install this in Linux/aarch64. The I tried to solve this by installing the server natively but I saw that there were close tickets about this topic about no good reason for having a native version. Well, here you have one. 

The other solution of course is to build the images on several architectures too. 

,

### Motivation

I want to run mail server in a different machine that Linux/amd64

**Comment by mkuron** [comment] 2022-03-25 22:15
Duplicate of #879. We don‘t currently support other architectures because none of the core developers currently need it and we don‘t want to ship something that we don‘t continuously test and use in production. Also, SOGo tends to be a bit tricky to build and it doesn‘t provide pre-built non-amd64 packages.

**Closed as completed by mkuron** 2022-03-25 22:16 UTC
Labels: enhancement
