### ISSUE TITLE
Error when starting mailcow in docker swarm

### ISSUE THREAD

**Issue by measwel** [mailcow/mailcow-dockerized#1222] opened 2018-03-31 15:30 UTC
The starup fails with: property oom_score_adj is not allowed
What could be causing this error?

**Comment by MAGICCC** [comment] 2018-03-31 15:34
Duplicate of #1221

**Comment by measwel** [comment] 2018-03-31 17:49
Thank you. Deleting the line helped. Now I am facing:
enble_ipv6 Additional property enable_ipv6 is not allowed
and
rpc error: code = Unknown desc = update out of sequence

**Comment by mkuron** [comment] 2018-03-31 21:12
That one is here: https://github.com/mailcow/mailcow-dockerized/blob/1534c5aa76510ef0a13a29d56ace491169dfa6f4/docker-compose.yml#L399

If you turn it off (or disable the ipv6nat container), and your host has an IPv6 connection, your Mailcow will be an open relay, which is dangerous. So be careful.

**Closed as completed** 2018-04-17 21:17 UTC
