### ISSUE TITLE
Multiple servers for backup / high availability?

### ISSUE THREAD

**Issue by nickian** [mailcow/mailcow-dockerized#1967] opened 2018-10-30 01:24 UTC
What is the best way to ensure reliability with multiple servers? If my primary mail server goes down, how can I be sure that mail will still get through and not bounce? Can this be solved by just having two MailCow servers with the same accounts set up and having a second priority mx record in DNS? Or is there a more ideal way to keep two servers in sync?

Thanks!

**Comment by mkuron** [comment] 2018-10-30 06:29
Most people don‘t need a backup MX since mail will not hard-bounce as long as you get a failed server back online within three days. Mail servers will just attempt to deliver messages again once your server is back up.

If you want to make sure that your users always have access to their mail, you‘d need a high availability setup. That‘s a duplicate of #241. there are some notes about it in different issue tickets, but so far it‘s not easy, officially supported or well documented.

**Closed as completed by mkuron** 2018-10-30 06:29 UTC

**Comment by nickian** [comment] 2018-10-30 06:54
Thanks, @mkuron. Is 3 days really a universal standard, or does that just depend on the sending server's configuration?

Am I understanding how MX records work correctly when I imagine that I second priority MX record is used when the first one fails?

**Comment by mkuron** [comment] 2018-10-30 07:11
I think the standard only says something unspecific like "several days". But all servers I know tend to do it for three days or more. For me that's enough, so I don't use a backup MX.

Yes, MXes are used in order of increasing priority values.

**Comment by dofl** [comment] 2019-06-08 13:28
> Thanks, @mkuron. Is 3 days really a universal standard, or does that just depend on the sending server's configuration?
> 
> Am I understanding how MX records work correctly when I imagine that I second priority MX record is used when the first one fails?

See https://github.com/mailcow/mailcow-dockerized/pull/2693 for more information and a change in default setting on the number of day Mailcow should retry sending e-mail to a host that is unreachable.
