### ISSUE TITLE
IPv6 Issue - Unable to renew SSL - IPv6 0000:0000:0000:0000:0000:0000:0000:0000

### ISSUE THREAD

**Issue by daygle** [mailcow/mailcow-dockerized#4167] opened 2021-07-01 00:20 UTC
Is anyone else getting the same messages with the current release?

acme-mailcow_1       | Thu Jul  1 10:13:36 AEST 2021 - OK: [hidden], 0000:0000:0000:0000:0000:0000:0000:0000
acme-mailcow_1       | Thu Jul  1 10:13:37 AEST 2021 - Found AAAA record for autodiscover.[hidden].net: [hidden] - skipping A record check
acme-mailcow_1       | Thu Jul  1 10:13:37 AEST 2021 - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autodiscover.[hidden].net (DNS returned [hidden])
acme-mailcow_1       | Thu Jul  1 10:13:37 AEST 2021 - Found AAAA record for autoconfig.[hidden].net: [hidden] - skipping A record check
acme-mailcow_1       | Thu Jul  1 10:13:37 AEST 2021 - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autoconfig.[hidden].net (DNS returned [hidden])
acme-mailcow_1       | Thu Jul  1 10:13:37 AEST 2021 - Found AAAA record for mail.[hidden].net: [hidden] - skipping A record check
acme-mailcow_1       | Thu Jul  1 10:13:37 AEST 2021 - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname mail.[hidden].net (DNS returned [hidden])

I am unable to renew ssl certificates because of this error, not sure why this has happened? It's worked in the past, maybe the new release has caused this?

Oh I'm using Ubuntu 21.04 too, maybe mailcow isn't compatible?

Why is it thinking my iPv6 address is 0000:0000:0000:0000:0000:0000:0000:0000?

**Comment by lvdd1** [comment] 2021-07-01 14:48
Yes, I have the same issue. 
I have confirmed that my Debian system has matching ipv6 addresses on the wan interface as well as the DNS entry. Since the ACME container in mailcow skips requesting a valid certificate for the A-Record if it finds an AAAA record, I ended up having no certificate for a specific name. My quick-fix was to remove the AAAA record for that specific name in DNS and only go with ipv4 for now. 
Somehow the ACME container doesn't properly read the ipv6 address from the system its running on.

**Comment by daygle** [comment] 2021-07-01 14:55
Thanks @lvdd1 - yes, it appears your having the same issue as I am, I suspect everyone is.

Let's hope it is fixed soon.

**Comment by pieterhouwen** [comment] 2021-07-09 13:55
Bump, this is a big issue as ipv4 alone also won't allow it. This has to do with the DNS server that is being used I reckon

**Comment by pieterhouwen** [comment] 2021-07-09 17:52
Temporary workaround can be setting this in your mailcow.conf:

```
# Skip IPv4 check in ACME container - y/n

SKIP_IP_CHECK=y

# Skip HTTP verification in ACME container - y/n

SKIP_HTTP_VERIFICATION=y
```

after that docker-compose down && docker-compose up -d will renew the cert

**Comment by andryyy** [comment] 2021-07-09 20:02
What am I doing different that it works fine on dozens of different setups with v4, v6 and dual stack?

Why is everything always a big issue and a huge problem for **everyone**? That’s such a crazy assumption. Is it impossible that the mistake maaaaay be is in your network?

DNS is probably returning an AAAA while your setup has no v6 link in Docker.

Also rtf template. Don’t delete and ignore it. I will close it until the proper format is used. It is really, really annoying. Nobody has any information about your setup, what firewall you use, what network connection is setup in which way. If you tested IPv6 in a container etc.

Start with using the template and provider all information. Also post tests like “docker-compose exec acme-mailcow curl ip6.mailcow.email” etc.

**Closed by andryyy** 2021-07-09 20:02 UTC

**Comment by lvdd1** [comment] 2021-07-12 18:34
Sorry @andryyy, but I have to disagree. I just looked through the ACME logs and found the time when it started to fail:

```
25/06/2021, 20:34:49 | gonzo.twodomain.net - Confirmed AAAA record with IP 2a03:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
25/06/2021, 20:34:49 | gonzo.twodomain.net - Found AAAA record for autoconfig.twodomain.net: 2a03:xxxx:xx:xxx::1 - skipping A record check

25/06/2021, 20:34:49 | gonzo.twodomain.net - Confirmed AAAA record with IP 2a03:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx
-- | --
25/06/2021, 20:34:49 | gonzo.twodomain.net - Found AAAA record for autodiscover.twodomain.net: 2a03:xxxx:xx:xxx::1 - skipping A record check
25/06/2021, 20:34:49 | gonzo.twodomain.net - No A or AAAA record found for hostname autoconfig.onedomain.de
25/06/2021, 20:34:49 | gonzo.twodomain.net - No A or AAAA record found for hostname autodiscover.onedomain.de
25/06/2021, 20:34:48 | gonzo.twodomain.net - OK: 202.xx.xx.xx, 2a03:xxxx:xx:xxx::1
25/06/2021, 20:34:48 | gonzo.twodomain.net - Detecting IP addresses...
```

After that I performed an update with update.sh and from that moment on I started to see the following messages:

```
25/06/2021, 20:42:59 | gonzo.twodomain.net - Found AAAA record for autoconfig.twodomain.net: 2a03:xxxx:xx:xxx::1 - skipping A record check
-- | --
25/06/2021, 20:42:58 | gonzo.twodomain.net - Cannot match your IP 0000:0000:0000:0000:0000:0000:0000:0000 against hostname autodiscover.twodomain.net (DNS returned 2a03:4000:0056:0bfa:0000:0000:0000:0001)
25/06/2021, 20:42:58 | gonzo.twodomain.net - Found AAAA record for autodiscover.twodomain.net: 2a03:xxxx:xx:xxx::1 - skipping A record check
25/06/2021, 20:42:58 | gonzo.twodomain.net - No A or AAAA record found for hostname autoconfig.onedomain.de
25/06/2021, 20:42:58 | gonzo.twodomain.net - No A or AAAA record found for hostname autodiscover.onedomain.de
25/06/2021, 20:42:57 | gonzo.twodomain.net - OK: 202.xx.xxx.xx, 0000:0000:0000:0000:0000:0000:0000:0000
25/06/2021, 20:42:37 | gonzo.twodomain.net - Detecting IP addresses...
25/06/2021, 20:42:37 | gonzo.twodomain.net - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
25/06/2021, 20:42:37 | gonzo.twodomain.net - Using existing domain rsa key /var/lib/acme/acme/key.pem
25/06/2021, 20:42:37 | gonzo.twodomain.net - Initializing, please wait...
25/06/2021, 20:42:37 | gonzo.twodomain.net - OK
```

Since it worked before, I have to assume my network config is correct as it is. That means nothing in my config has changed to my knowledge.

_DNS is probably returning an AAAA while your setup has no v6 link in Docker._
I don't know what that means - can you point me to the documentation? And then again, everything worked before so, I am not sure I need to know what this means....

_Also rtf template. Don’t delete and ignore it._
What template? What does that mean? I would use one if you made it clear what you are referring to. 

I understand the problem that there is probably not enough information for you to provide help. I would be glad to provide some, if you wouldn't just assume that people know what you're talking about and have the same insight into your product as you do.
So, a few more pointers would maybe make me feel more welcome and understood

**Comment by andryyy** [comment] 2021-07-12 19:05
The minimum is not to delete the issue template. 

If it worked before and is broken now does absolutely not indicate that nothing changed. I guarantee something did indeed change. 

I have no clue about your setup as all information is missing. :/

You did even ignore the command above (curl…).

**Comment by lvdd1** [comment] 2021-07-12 19:25
Yeah, right - I ignored executing the command above. It gives an error message, which would have given you the perfect opportunity to tell me I have a non-compliant environment or something the like.
You have ignored my question regarding the template. Just to let you know, I never saw a template as I was just participating in an existing thread and only  would have seen the template when creating a new issue in the tracker. But you failed to explain this since you just expect everybody to know these things.
Looks like it is hard for you to explain things and you seem to have lost all patience to actually give support to non-developers with less knowledge than you. That's sad, as I kind of like the concept of the system you have created. But it is obvious you have created it just for experts of your caliber.

Don't bother wasting any more time with this  - I won't either
