### ISSUE TITLE
log rotate

### ISSUE THREAD

**Issue by daemon-byte** [mailcow/mailcow-dockerized#1945] opened 2018-10-25 14:08 UTC
I'm still trying to learn docker so I apologise if this seems a silly question but do the logs rotate in the instances? The reason I ask is before I had the mail log rotate each day, zip if older than 2 and save for a month. That way if I was looking for something on a specific day I just had to grep the day's file. I tried grepping on docker-compose logs dovecot-mailcow and it was giving me hits from back in August when I set things up. If every time I need to grep a logfile I have to either guess on lines with tail or start from the very beginning that's going to get very slow and intense very quickly. So I was wondering if there was a way of trimming off the log files.

**Comment by mritzmann** [comment] 2018-10-25 14:50
Maybe this will help you: https://docs.docker.com/config/containers/logging/configure/

I log my docker log output to syslog:

```shell
$ cat /etc/docker/daemon.json
{
  "log-driver": "syslog",
  "log-opts": {
    "syslog-address": "udp://127.0.0.1:514"
  }
}
```

**Comment by mkuron** [comment] 2018-10-25 16:12
Duplicate of #518. See my comment in that issue for how to limit the number and maximum size of logfiles (without switching to syslog as suggested by @mritzmann). Any time you do `docker-compose down`, logs are cleared completely.

**Closed as completed by mkuron** 2018-10-25 16:12 UTC
