### ISSUE TITLE
Autoconfig/autodiscover with multiple domains

### ISSUE THREAD

**Issue by alexandernst** [mailcow/mailcow-dockerized#1164] opened 2018-03-14 00:44 UTC
Is it possible to make mailcow reply with the autoconfig of the same domain that is requesting said config?

For example, I have `foo.com` and `bar.com` (the `PTR` of my server is `abc.com`).

Currently, whenever a user from any of the two domains tries to auto-configure a mail account, mailcow returns the domain `mail.abc.com`. Is it possible to make mailcow return `mail.foo.com` for the users of `foo.com` that are trying to auto-configure their accounts, and `mail.bar.com` for the users of `bar.com` that are trying to auto-configure their accounts?

**Comment by mkuron** [comment] 2018-03-14 06:21
Duplicate of #528

**Closed as completed by mkuron** 2018-03-14 06:21 UTC
