### ISSUE TITLE
Changing E-Mail Forwarding from SOGo broken

### ISSUE THREAD

**Issue by tmkis2** [mailcow/mailcow-dockerized#4742] opened 2022-09-04 21:09 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

After updating to 2022-08a I tried to change email forwarders within SOGo and got this error message when trying to save the changes: 
<img width="330" alt="Bildschirmfoto 2022-09-04 um 20 01 32" src="https://user-images.githubusercontent.com/52584155/188333295-f2437d89-6a7b-4dc9-a58e-1f91490efbcc.png">

### Logs

```bash
Sep  4 20:03:07 0c87c1bc8c39 sogod [58673]: <0x0x55f44da072e0[SOGoSieveManager]> failure. Attempting with a renewed password (no authname supported)
Sep  4 20:03:07 0c87c1bc8c39 sogod [58673]: [ERROR] <0x55f44da1a690[SOGoMailAccount]:0> no IMAP4 password available
Sep  4 20:03:07 0c87c1bc8c39 sogod [58673]: <0x0x55f44da072e0[SOGoSieveManager]> Could not login 'thomas@domain.tld' on Sieve server: <0x0x55f44db32d60[NGSieveClient]: socket=<NGActiveSocket[0x0x55f44da04ec0]: mode=rw address=<0x0x55f44da04f30[NGInternetSocketAddress]: host=0c87c1bc8c39 port=56304> connectedTo=<0x0x55f44da12e90[NGInternetSocketAddress]: host=dovecot port=4190>>>: (null)
Sep  4 20:03:07 0c87c1bc8c39 sogod [58673]: 2a02:908:1992:4020:e1ba:24a6:7f8a:3f6d "POST /SOGo/so/thomas@domain.tld/Preferences/save HTTP/1.0" 503 46/5238 1.799 - - 0 - 12
```

### Steps to reproduce

Login to SOGo and go to Settings -> E-Mail -> Forwarders
Change them and try to save the changes.

### System information

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 20.04 LTS |
| Is Apparmor, SELinux or similar active? | NO |
| Virtualization technology (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 8 GB RAM/4 Cores |
| Docker version (`docker version`) | 20.10.17 |
| docker-compose version (`docker-compose version`) | v2.10.2 |
| mailcow version (```git describe --tags `git rev-list --tags --max-count=1` ```) | 2022-08a |
| Reverse proxy (custom solution) | NO |

Output of `git diff origin/master`, any other changes to the code? If so, **please post them**:
```
diff --git a/create_cold_standby.sh b/create_cold_standby.sh
index 924339af..9d7bb0ed 100755
--- a/create_cold_standby.sh
+++ b/create_cold_standby.sh
@@ -2,6 +2,6 @@
 
 export REMOTE_SSH_KEY=/root/.ssh/id_rsa
 export REMOTE_SSH_PORT=22
-export REMOTE_SSH_HOST=my.remote.host
+export REMOTE_SSH_HOST=5.180.192.196
 
 /opt/mailcow-dockerized/helper-scripts/_cold-standby.sh
diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index a445b60c..1f3a565d 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -198,3 +198,7 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks
 
 # DO NOT EDIT ANYTHING BELOW #
 # User overrides #
+
+myhostname = mail.tmkis.com
+submission_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
+smtps_smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3
diff --git a/data/conf/rspamd/custom/global_mime_from_whitelist.map b/data/conf/rspamd/custom/global_mime_from_whitelist.map
index 3c872889..844c6b2a 100644
--- a/data/conf/rspamd/custom/global_mime_from_whitelist.map
+++ b/data/conf/rspamd/custom/global_mime_from_whitelist.map
@@ -1 +1,2 @@
-# /.+example\.com/i
+# /.+example\.com/i^M
+/.+tmkis\.email/i
diff --git a/data/conf/rspamd/local.d/multimap.conf b/data/conf/rspamd/local.d/multimap.conf
index 17ada99e..1792e622 100644
--- a/data/conf/rspamd/local.d/multimap.conf
+++ b/data/conf/rspamd/local.d/multimap.conf
@@ -179,3 +179,4 @@ BAD_SUBJECT_00 {
   score = 6.0;
   symbols_set = ["BAD_SUBJECT_00"];
 }
+
diff --git a/data/conf/sogo/sogo.conf b/data/conf/sogo/sogo.conf
index 1d6a9d3f..557250c8 100644
--- a/data/conf/sogo/sogo.conf
+++ b/data/conf/sogo/sogo.conf
@@ -5,7 +5,7 @@
         PrivateDAndTViewer
     );
 
-    WOWorkersCount = "20";
+    WOWorkersCount = "80";
     SOGoACLsSendEMailNotifications = YES;
     SOGoAppointmentSendEMailNotifications = YES;
     SOGoDraftsFolderName = "Drafts";
@@ -37,7 +37,7 @@
     WOPort = "0.0.0.0:20000";
     SOGoMemcachedHost = "memcached";
 
-    SOGoLanguage = English;
+    SOGoLanguage = German;
     SOGoMailAuxiliaryUserAccountsEnabled = YES;
     SOGoMailCustomFromEnabled = YES;
     SOGoMailingMechanism = smtp;
@@ -60,7 +60,7 @@
     WONoDetach = YES;
 
     SOGoIMAPAclConformsToIMAPExt = Yes;
-    SOGoPageTitle = "SOGo Groupware";
+    SOGoPageTitle = "TMKIS Groupware";
     SOGoFirstDayOfWeek = "1";
 
     SOGoSieveFolderEncoding = "UTF-8";
@@ -92,3 +92,4 @@
   //WODontZipResponse = YES;
     WOLogFile = "/dev/sogo_log";
 }
+
diff --git a/data/web/autoconfig.php b/data/web/autoconfig.php
index 95952df0..b1fc2bd8 100644
--- a/data/web/autoconfig.php
+++ b/data/web/autoconfig.php
@@ -29,8 +29,8 @@ header('Content-Type: application/xml');
 <clientConfig version="1.1">
     <emailProvider id="<?=$mailcow_hostname; ?>">
       <domain>%EMAILDOMAIN%</domain>
-      <displayName>A mailcow mail server</displayName>
-      <displayShortName>mail server</displayShortName>
+      <displayName>TMKIS Mail-Server</displayName>
+      <displayShortName>Mail-Server</displayShortName>
 
       <incomingServer type="imap">
          <hostname><?=$autodiscover_config['imap']['server']; ?></hostname>
diff --git a/docker-compose.yml b/docker-compose.yml
index 9fbfef59..5f4e6251 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -580,36 +580,6 @@ services:
           aliases:
             - ofelia
 
-    ipv6nat-mailcow:
-      depends_on:
-        - unbound-mailcow
-        - mysql-mailcow
-        - redis-mailcow
-        - clamd-mailcow
-        - rspamd-mailcow
-        - php-fpm-mailcow
-        - sogo-mailcow
-        - dovecot-mailcow
-        - postfix-mailcow
-        - memcached-mailcow
-        - nginx-mailcow
-        - acme-mailcow
-        - netfilter-mailcow
-        - watchdog-mailcow
-        - dockerapi-mailcow
-        - solr-mailcow
-      environment:
-        - TZ=${TZ}
-      image: robbertkl/ipv6nat
-      security_opt:
-        - label=disable
-      restart: always
-      privileged: true
-      network_mode: "host"
-      volumes:
-        - /var/run/docker.sock:/var/run/docker.sock:ro
-        - /lib/modules:/lib/modules:ro
-
 networks:
   mailcow-network:
     driver: bridge
```

All third-party firewalls and custom iptables rules are unsupported. **Please check the Docker docs about how to use Docker with your own ruleset**. Nevertheless, iptabels output can help us to help you:
iptables -L -vn:
```
Chain INPUT (policy ACCEPT 113K packets, 44M bytes)
 pkts bytes target     prot opt in     out     source               destination         
1310K 2484M MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
  22M  146G MAILCOW    all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  22M  146G DOCKER-USER  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  22M  146G DOCKER-ISOLATION-STAGE-1  all  --  *      *       0.0.0.0/0            0.0.0.0/0           
  20M  146G ACCEPT     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
 599K   43M DOCKER     all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0           
1593K  603M ACCEPT     all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0           
 567K   41M ACCEPT     all  --  br-mailcow br-mailcow  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0            ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
    0     0 ACCEPT     all  --  docker0 docker0  0.0.0.0/0            0.0.0.0/0           

Chain OUTPUT (policy ACCEPT 156K packets, 12M bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.4           tcp dpt:8983
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.249         tcp dpt:6379
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.9           tcp dpt:3306
 1826  109K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:443
  346 19720 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.11          tcp dpt:80
    0     0 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:12345
    1    52 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:4190
  288 17200 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:995
 2606  164K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:993
  767 47085 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:143
   49  2860 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.250         tcp dpt:110
  234 13000 ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:587
 3269  194K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:465
 2157  125K ACCEPT     tcp  --  !br-mailcow br-mailcow  0.0.0.0/0            172.22.1.253         tcp dpt:25

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
1593K  603M DOCKER-ISOLATION-STAGE-2  all  --  br-mailcow !br-mailcow  0.0.0.0/0            0.0.0.0/0           
    0     0 DOCKER-ISOLATION-STAGE-2  all  --  docker0 !docker0  0.0.0.0/0            0.0.0.0/0           
  33M  157G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all  --  *      br-mailcow  0.0.0.0/0            0.0.0.0/0           
    0     0 DROP       all  --  *      docker0  0.0.0.0/0            0.0.0.0/0           
2707K 1188M RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain DOCKER-USER (1 references)
 pkts bytes target     prot opt in     out     source               destination         
  33M  157G RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0           

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination      
```

ip6tables -L -vn:
```
Chain INPUT (policy ACCEPT 17077 packets, 1189K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 569K  126M MAILCOW    all      *      *       ::/0                 ::/0                

Chain FORWARD (policy DROP 0 packets, 0 bytes)
 pkts bytes target     prot opt in     out     source               destination         
3899K 2291M MAILCOW    all      *      *       ::/0                 ::/0                
3900K 2291M DOCKER-ISOLATION-STAGE-1  all      *      *       ::/0                 ::/0                
2715K 1573M ACCEPT     all      *      br-mailcow  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
 180K   14M DOCKER     all      *      br-mailcow  ::/0                 ::/0                
1006K  704M ACCEPT     all      br-mailcow !br-mailcow  ::/0                 ::/0                
 145K   11M ACCEPT     all      br-mailcow br-mailcow  ::/0                 ::/0                
    0     0 ACCEPT     all      *      docker0  ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
    0     0 DOCKER     all      *      docker0  ::/0                 ::/0                
    0     0 ACCEPT     all      docker0 !docker0  ::/0                 ::/0                
    0     0 ACCEPT     all      docker0 docker0  ::/0                 ::/0                

Chain OUTPUT (policy ACCEPT 15737 packets, 1228K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
 7321  793K ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::e  tcp dpt:443
   69  5520 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::e  tcp dpt:80
    0     0 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:4190
  966 76728 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:995
 3918  323K ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:993
  296 23943 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:143
   47  3948 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::f  tcp dpt:110
   79  6332 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:587
  968 76480 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:465
  900 72000 ACCEPT     tcp      !br-mailcow br-mailcow  ::/0                 fd4d:6169:6c63:6f77::10  tcp dpt:25

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
 pkts bytes target     prot opt in     out     source               destination         
1006K  704M DOCKER-ISOLATION-STAGE-2  all      br-mailcow !br-mailcow  ::/0                 ::/0                
    0     0 DOCKER-ISOLATION-STAGE-2  all      docker0 !docker0  ::/0                 ::/0                
7157K 5556M RETURN     all      *      *       ::/0                 ::/0                

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DROP       all      *      br-mailcow  ::/0                 ::/0                
    0     0 DROP       all      *      docker0  ::/0                 ::/0                
1987K 2516M RETURN     all      *      *       ::/0                 ::/0                

Chain MAILCOW (2 references)
 pkts bytes target     prot opt in     out     source               destination         
```

iptables -L -vn -t nat:
```
Chain PREROUTING (policy ACCEPT 617K packets, 40M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 119K 6830K DOCKER     all  --  *      *       0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 14774 packets, 846K bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 28 packets, 2089 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all  --  *      *       0.0.0.0/0           !127.0.0.0/8          ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 227K packets, 16M bytes)
 pkts bytes target     prot opt in     out     source               destination         
 544K   45M MASQUERADE  all  --  *      !br-mailcow  172.22.1.0/24        0.0.0.0/0           
    0     0 MASQUERADE  all  --  *      !docker0  172.17.0.0/16        0.0.0.0/0           
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.4           172.22.1.4           tcp dpt:8983
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.249         172.22.1.249         tcp dpt:6379
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.9           172.22.1.9           tcp dpt:3306
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:443
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.11          172.22.1.11          tcp dpt:80
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:12345
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:4190
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:995
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:993
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:143
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.250         172.22.1.250         tcp dpt:110
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:587
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:465
    0     0 MASQUERADE  tcp  --  *      *       172.22.1.253         172.22.1.253         tcp dpt:25

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
    3   180 RETURN     all  --  br-mailcow *       0.0.0.0/0            0.0.0.0/0           
    0     0 RETURN     all  --  docker0 *       0.0.0.0/0            0.0.0.0/0           
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:18983 to:172.22.1.4:8983
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:7654 to:172.22.1.249:6379
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:13306 to:172.22.1.9:3306
 1830  110K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:443 to:172.22.1.11:443
  346 19720 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:80 to:172.22.1.11:80
    0     0 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            127.0.0.1            tcp dpt:19991 to:172.22.1.250:12345
    1    52 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:4190 to:172.22.1.250:4190
  288 17200 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:995 to:172.22.1.250:995
 2619  165K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:993 to:172.22.1.250:993
  767 47085 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:143 to:172.22.1.250:143
   49  2860 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:110 to:172.22.1.250:110
  251 13864 DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:587 to:172.22.1.253:587
 3280  195K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:465 to:172.22.1.253:465
 2170  125K DNAT       tcp  --  !br-mailcow *       0.0.0.0/0            0.0.0.0/0            tcp dpt:25 to:172.22.1.253:25
```

ip6tables -L -vn -t nat:
```
Chain PREROUTING (policy ACCEPT 158K packets, 14M bytes)
 pkts bytes target     prot opt in     out     source               destination         
55918 5252K DOCKER     all      *      *       ::/0                 ::/0                 ADDRTYPE match dst-type LOCAL

Chain INPUT (policy ACCEPT 23 packets, 4017 bytes)
 pkts bytes target     prot opt in     out     source               destination         

Chain OUTPUT (policy ACCEPT 3 packets, 240 bytes)
 pkts bytes target     prot opt in     out     source               destination         
    0     0 DOCKER     all      *      *       ::/0                !::1                  ADDRTYPE match dst-type LOCAL

Chain POSTROUTING (policy ACCEPT 45538 packets, 3858K bytes)
 pkts bytes target     prot opt in     out     source               destination         
 178K   18M MASQUERADE  all      *      !br-mailcow  fd4d:6169:6c63:6f77::/64  ::/0                
    0     0 MASQUERADE  all      *      !docker0  fd00:dead:beef:c0::/80  ::/0                
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::e  fd4d:6169:6c63:6f77::e  tcp dpt:443
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::e  fd4d:6169:6c63:6f77::e  tcp dpt:80
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:4190
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:995
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:993
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:143
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::f  fd4d:6169:6c63:6f77::f  tcp dpt:110
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:587
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:465
    0     0 MASQUERADE  tcp      *      *       fd4d:6169:6c63:6f77::10  fd4d:6169:6c63:6f77::10  tcp dpt:25

Chain DOCKER (2 references)
 pkts bytes target     prot opt in     out     source               destination         
  624 49920 RETURN     all      br-mailcow *       ::/0                 ::/0                
    0     0 RETURN     all      docker0 *       ::/0                 ::/0                
 7322  792K DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:443 to:[fd4d:6169:6c63:6f77::e]:443
   69  5520 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:80 to:[fd4d:6169:6c63:6f77::e]:80
    0     0 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:4190 to:[fd4d:6169:6c63:6f77::f]:4190
  967 76808 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:995 to:[fd4d:6169:6c63:6f77::f]:995
 3923  323K DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:993 to:[fd4d:6169:6c63:6f77::f]:993
  296 23943 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:143 to:[fd4d:6169:6c63:6f77::f]:143
   47  3948 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:110 to:[fd4d:6169:6c63:6f77::f]:110
   79  6332 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:587 to:[fd4d:6169:6c63:6f77::10]:587
  969 76560 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:465 to:[fd4d:6169:6c63:6f77::10]:465
  901 72080 DNAT       tcp      !br-mailcow *       ::/0                 ::/0                 tcp dpt:25 to:[fd4d:6169:6c63:6f77::10]:25
```

DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output:
```
151.101.129.69
151.101.1.69
151.101.65.69
151.101.193.69
```

**Comment by FreddleSpl0it** [comment] 2022-09-05 07:27
The problem came with the update of the SOGo container. The mailcow/sogo:1.109 container works fine. I'll take a look to see what's causing it

**Comment by FreddleSpl0it** [comment] 2022-09-05 10:04
At this point, i dont relly know if the SOGo container is the problem here. On a freshly installed mailcow i cant reproduce the problem anymore. The bug just disappeared. Maybe it was fixed by a simple docker-compose down && docker-compose up -d. can someone else perhaps say something about this?

@tmkis2 maybe you can switch back to mailcow/sogo:1.110 and see if the bug returns?

**Comment by tmkis2** [comment] 2022-09-05 10:55
@FreddleSpl0it I did! Switched back to sogo:1.110 and after adding another forwarder in SoGO the error above returned.

You may look on it on the my server directly. I posted admin credentials in the ticket.

**Comment by DerLinkman** [comment] 2022-09-05 13:22
Hi,

can you check what´s in the file: sogo_trusted_ip.conf in your data/conf/dovecot Folder?

**Comment by tmkis2** [comment] 2022-09-05 13:36
```
# Autogenerated by mailcow
remote 172.22.1.248 {
  disable_plaintext_auth = no
}

remote fd4d:6169:6c63:6f77::a {
  disable_plaintext_auth = no
}

```

**Comment by ro78** [comment] 2022-09-05 13:54
After the same upgrade, my filtering rules (to move specific emails to specific folders) didn't worked anymore. After trying to edit the rule and save it (without any change), it worked again. Maybe it can help the team to understand what has changed.

**Comment by tmkis2** [comment] 2022-09-06 10:43
Addition: SOGo is also unable to send any mails. Authentication failure is the error after trying to compose a new mail via SOGo after the update.

**Comment by RoStNet** [comment] 2022-09-07 09:25
Same behavior after the update to 2022-08a.
But for me the problem occurs only when I access SOGo via mailcow ui.

If the login is done directly via SOGo "https://host/sogo", sending mails and changing settings works.

**Comment by FreddleSpl0it** [comment] 2022-09-08 09:23
I was able to fix the sogo bugs with @andryyy help. here is the fix [https://github.com/mailcow/mailcow-dockerized/tree/fix/sogo](https://github.com/mailcow/mailcow-dockerized/tree/fix/sogo). Maybe some one can test this. On my test machine its working.

Docker images are not on our docker hub yet, so everyone testing has to build the dovecot and sogo images

i don't know yet when i can merge the fix into the master branch

**Comment by tmkis2** [comment] 2022-09-08 13:42
Works for me now! Thank you very much!

**Closed as completed** 2022-09-08 15:42 UTC
Labels: bug
