### ISSUE TITLE
[Question]Add Another Domain for Webmail

### ISSUE THREAD

**Issue by ClepToManix** [mailcow/mailcow-dockerized#1654] opened 2018-08-10 16:29 UTC
Hello,

i finally set up my mailserver correctly :) now i have to other domains to get working with my mail server. DNS Records, SPF, DKIM und DMARC are setted up for those two domain and i would like to access my mailserver (mail.domain1.tld) via mail.domain2.tld and mail.domain3.tld. I may have to setup one A-Record for each domain and point my mailservers ip adress, but what i have to do with my webserver? is it dangerous to customize the sites-available in nginx?

**Comment by mkuron** [comment] 2018-08-10 17:14
> i would like to access my mailserver (mail.domain1.tld) via mail.domain2.tld and mail.domain3.tld

Mailcow will still use mail.domain1.tld in some places (duplicate of #528). So while you won't get clear separation between the three domains, people will be able to access any of them and reach the mail server.

> I may have to setup one A-Record for each domain and point my mailservers ip adress, but what i have to do with my webserver?

You don't have to do anything with the web server. It accepts requests under any domain name, you just need to create an appropriate A record. You will need to create appropriate SSL certificates by adding the domains to ADDITIONAL_SAN in mailcow.conf.

> is it dangerous to customize the sites-available in nginx?

It's not recommended. The safest way to do it is to add extra files to data/conf/nginx though.

**Closed as completed by mkuron** 2018-08-10 17:14 UTC
