### ISSUE TITLE
Restarting mailcow suddenly shows warning "OomKillDisable" after upgrade from 2022-11b to 2022-11b

### ISSUE THREAD

**Issue by Choppel** [mailcow/mailcow-dockerized#4902] opened 2022-12-19 16:45 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```text
We updated a mailcow on 2022-12-15 (to version 2022-11b) and during the restart of the containers there were no warnings or errors. Today (2022-12-19) we updated the same mailcow and suddenly there is the following warning/error when we restart the mailcow: "dockerapi-mailcow Your kernel does not support OomKillDisable. OomKillDisable discarded."
I tested this on 3 different mailcows after it appeared on the first with the same results.
Everything works as expected though. So this seems to be an inconvenience rather than a major bug.
```

### Logs:

```text
-
```

### Steps to reproduce:

```text
1.) Take a mailcow prior to 2022-11b and restart it. There shouldn't be errors during the start of the containers.
2.) Update it to 2022-11b. There should be a yellow warning like "dockerapi-mailcow Your kernel does not support OomKillDisable. OomKillDisable discarded"
```

### Which branch are you using?

master

### Operating System:

Debian 11 Bullseye

### Server/VM specifications:

6GB

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

20.10.22

### docker-compose version or docker compose version:

v2.14.1

### mailcow version:

2022-11b

### Reverse proxy:

Nginx

### Logs of git diff:

```text
-
```

### Logs of iptables -L -vn:

```text
-
```

### Logs of ip6tables -L -vn:

```text
-
```

### Logs of iptables -L -vn -t nat:

```text
-
```

### Logs of ip6tables -L -vn -t nat:

```text
-
```

### DNS check:

```text
-
```

**Comment by RobMeerwijk** [comment] 2022-12-21 22:06
I get the same warning on both my mailcow instances since last release (2022-11b)

**Comment by DerLinkman** [comment] 2022-12-24 12:08
Yes, known. It seems that this was introduced with Debian 11.6

We´re currently investigating if we can replace OomKillDisable within the DockerApi

**Comment by MAGICCC** [comment] 2022-12-24 13:01
Also with Ubuntu 22.04.1 LTS (5.15.0-56-generic)

**Comment by omexlu** [comment] 2022-12-24 16:04
> Also with Ubuntu 22.04.1 LTS (5.15.0-56-generic)

Equally, however, everything works as intended on 20.04.

**Comment by daygle** [comment] 2022-12-27 06:07
> Yes, known. It seems that this was introduced with Debian 11.6
> 
> We´re currently investigating if we can replace OomKillDisable within the DockerApi

Thanks @DerLinkman. Same issue with myself and Ubuntu 22.04.1 LTS.

Do we know what (if anything) that this impacts with mailcow?

**Comment by omexlu** [comment] 2022-12-27 06:51
> > Yes, known. It seems that this was introduced with Debian 11.6
> > We´re currently investigating if we can replace OomKillDisable within the DockerApi
> 
> Thanks @DerLinkman. Same issue with myself and Ubuntu 22.04.1 LTS.
> 
> Do we know what (if anything) that this impacts with mailcow?

I like to know that to, but it seems to not impact anything?

**Comment by maltokyo** [comment] 2022-12-27 12:03
I have the same issue after upgrading to Debian 11.6.  It did not happen before the upgrade.

**Comment by DerLinkman** [comment] 2022-12-27 12:10
This message seems not to break anything. We're currently investigating this message and implement a fix to remove this warning if we have some clear ideas.

**Comment by DerLinkman** [comment] 2023-01-10 09:07
Will be fixed in 2023-01

**Closed as completed by DerLinkman** 2023-01-10 09:07 UTC
Labels: bug, investigating, confirmed
