### ISSUE TITLE
Alias tagged mail - In subject - not working

### ISSUE THREAD

**Issue by skupfer** [mailcow/mailcow-dockerized#851] opened 2018-01-01 01:13 UTC
Let us assume I create an alias for my mailbox main@domain.tld which will be alias@domain.tld. This alias is attached to the given mailbox through the admin configuration panel.

If I send an email to alias@domain.tld I receive it properly in my main@domain.tld mailbox. The configuration for this mailbox says "Set handling for tagged mail: In subject" but this does not applies to mails received via the alias+tag (i.e. alias+tag@domain.tld) adress and they are stored in a subfolder (tag) instead...

Consistency here would be great!

best regards and a happy new year!

**Comment by mkuron** [comment] 2018-01-01 08:26
Duplicate of #408. Consistency would be great indeed, but is impossible to achieve here. As an alias may have multiple targets which may have different tag handling set, the mail system wouldn’t know what to do.

**Closed as completed by mkuron** 2018-01-01 08:26 UTC
