### ISSUE TITLE
After latest update (15.07.2020) SOGo and ActiveSync is broken

### ISSUE THREAD

**Issue by ufo56** [mailcow/mailcow-dockerized#3657] opened 2020-07-15 00:48 UTC
**Prior to placing the issue, please check following:** *(fill out each checkbox with an `X` once done)*
- [X] I understand, that not following or deleting the below instructions, will result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

**Description of the bug**:

  I hadn't updated mailcow for few months, today i decided to do so...
After update ActiveSync stoped working, did not update sent mails anymore on outlook. iPhone could no longer connect at all with mailbox. If i try to open mailbox on SOGo i only get empty mailbox.

**Docker container logs of affected containers**:

Trying to create new folder on SOGo and connect with iPhone
https://pastebin.com/raw/WyyuB0vG

**Reproduction of said bug**:

**System information**:

| Question | Answer |
| --- | --- |
| My operating system | Debian 9.11 |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc - **LXC and OpenVZ are not supported** | KVM |
| Server/VM specifications (Memory, CPU Cores) | 2 core, 4gb ram, 20gb ssd |
| Docker Version (`docker version`) | 19.03.2 |
| Docker-Compose Version (`docker-compose version`) | 1.26.2 |
| Reverse proxy (custom solution) | No custom solution |

- Output of `git diff origin/master`, any other changes to the code? If so, **No changes on code**.
- All third-party firewalls and custom iptables rules are unsupported. *Please check the Docker docs about how to use Docker with your own ruleset*. Nevertheless, iptabels output can help us to help you: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat`.
- DNS problems? Please run `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and post the output.

docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254
151.101.1.69
151.101.65.69
151.101.129.69
151.101.193.69

**Comment by andryyy** [comment] 2020-07-15 04:54
Hi, sorry, can't reproduce it. 

The git diff output is still important.

**Comment by ufo56** [comment] 2020-07-15 07:03
> Hi, sorry, can't reproduce it.
> 
> The git diff output is still important.

```
:/mailcow/mailcow-dockerized# git diff origin/master
:/mailcow/mailcow-dockerized#

```

**Comment by andryyy** [comment] 2020-07-15 07:10
Try an update.sh, I don't know what's happening.

**Comment by ufo56** [comment] 2020-07-15 07:19
https://pastebin.com/raw/mgzxkbSR

Found similar problem from community forum

https://community.mailcow.email/d/232-sogo-no-mailbox-selected

**Comment by andryyy** [comment] 2020-07-15 07:22
That does not help me replicate it. I don't have this problem on any managed service or mailcow in support.

**Comment by ufo56** [comment] 2020-07-15 07:39
I tried to make new mailbox on different domain. Same error...

```
dovecot-mailcow_1    | Jul 15 07:37:41 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 0 secs): user=<test@fuck-the-eye.eu>, rip=172.22.1.1, lip=172.22.1.250
dovecot-mailcow_1    | Jul 15 07:37:41 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 0 secs): user=<test@fuck-the-eye.eu>, rip=172.22.1.1, lip=172.22.1.250
dovecot-mailcow_1    | Jul 15 07:37:41 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 0 secs): user=<test@fuck-the-eye.eu>, rip=172.22.1.1, lip=172.22.1.250
dovecot-mailcow_1    | Jul 15 07:37:41 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 0 secs): user=<test@fuck-the-eye.eu>, rip=172.22.1.1, lip=172.22.1.250
dovecot-mailcow_1    | Jul 15 07:37:44 mail dovecot: lmtp(686): Connect from 172.22.1.1
dovecot-mailcow_1    | Jul 15 07:37:44 mail dovecot: lmtp(test@fuck-the-eye.eu)<686><2sx8JUiyDl+uAgAAG53Gig>: sieve: msgid=unspecified: stored mail into mailbox 'INBOX'
```

**Comment by andryyy** [comment] 2020-07-15 07:44
It is the same system, so it will happen in every domain there, I guess.

You can join the Telegram channel and write @diekuh a message. I can check it remote, if you like.

**Comment by andryyy** [comment] 2020-07-15 20:30
It was fixed by removing the old, unnamed bridges in mailcow. It masquerades incorrectly inside the mailcow network, all connections from inside the mailcow environment seem to be coming from the gw address 172.22.1.1 (**not** talking about external access to mailcow!).

I added a check and fix to the update.sh script.

**Closed as completed by andryyy** 2020-07-15 20:30 UTC

**Comment by ufo56** [comment] 2020-07-16 18:59
Thank you for helping me out!

**Comment by PatrickDeZordo** [comment] 2023-08-20 18:53
Good evening, we are facing the same issue..

Direct IMAP-Email-Access is possible for all users.
Email connections via Activesync are not possible.
If someone is logging in Sogo Webmail no mails are shown.
Clients already reset the EAS cache.

we are seeing just a lot of errors like this in "memory logs" :

`**imap-login: Disconnected: Connection closed (auth failed, 1 attempts in 0 secs): user=<mail@mail.com>, rip=172.22.1.1, lip=172.22.1.250**`

How to change the "right-IP" 172.22.1.1?

Can you please assist us?
Thank you very much.

**Comment by PatrickDeZordo** [comment] 2023-08-21 07:20
> How to change the "right-IP" 172.22.1.1?

# **SOLVED WITH THE FOLLOWING STEPS**

Just to help others, the issue is related to an **"old faulty brigde"** in iptables..

If you have any problems connecting via EAS (ActiveSync) and SOGo-Webmail, check out your **SOGo-logs** for lines like this:
`[74]: <0x5589b8adb280[SOGoMailAccount]:0> renewing imap4 password`
`[74]: [ERROR] <0x5589b8adb280[SOGoMailAccount]:0> no IMAP4 password available`
`[74]: [ERROR] <0x5589b8adb280[SOGoMailAccount]:0> Could not connect IMAP4`

..and check out your **Dovecot-logs** for lines like this (note the **"rip=172.22.1.1"**)
`imap-login: Disconnected: Connection closed (auth failed, 1 attempts in 0 secs): user=<mail@mail.com>, rip=172.22.1.1, lip=172.22.1.250`

..then (maybe) you are hitting by the same issue - go ahead!

Checking with `iptables -L -vn -t nat --line-numbers` shows:

> Chain POSTROUTING (policy ACCEPT 3133 packets, 195K bytes)
num   pkts bytes target     prot opt in     out     source               destination
1    48415 3779K MASQUERADE  0    --  *      !br-mailcow  172.22.1.0/24        0.0.0.0/0
2       51  3560 MASQUERADE  0    --  *      !docker0  172.17.0.0/16        0.0.0.0/0
**3    38181 2556K MASQUERADE  0    --  *      !br-a985bc74309d  172.22.1.0/24        0.0.0.0/0**
4        0     0 MASQUERADE  6    --  *      *       172.22.1.251         172.22.1.251         tcp dpt:443
5        0     0 MASQUERADE  6    --  *      *       172.22.1.251         172.22.1.251         tcp dpt:80
6        0     0 MASQUERADE  6    --  *      *       172.22.1.4           172.22.1.4           tcp dpt:12345
7        0     0 MASQUERADE  6    --  *      *       172.22.1.4           172.22.1.4           tcp dpt:4190
8        0     0 MASQUERADE  6    --  *      *       172.22.1.4           172.22.1.4           tcp dpt:995
9        0     0 MASQUERADE  6    --  *      *       172.22.1.4           172.22.1.4           tcp dpt:993
10       0     0 MASQUERADE  6    --  *      *       172.22.1.4           172.22.1.4           tcp dpt:143
11       0     0 MASQUERADE  6    --  *      *       172.22.1.4           172.22.1.4           tcp dpt:110
12       0     0 MASQUERADE  6    --  *      *       172.22.1.6           172.22.1.6           tcp dpt:587
13       0     0 MASQUERADE  6    --  *      *       172.22.1.6           172.22.1.6           tcp dpt:465
14       0     0 MASQUERADE  6    --  *      *       172.22.1.6           172.22.1.6           tcp dpt:25
15       0     0 MASQUERADE  6    --  *      *       172.17.0.2           172.17.0.2           tcp dpt:9443
16       0     0 MASQUERADE  6    --  *      *       172.17.0.2           172.17.0.2           tcp dpt:8000
17       0     0 MASQUERADE  6    --  *      *       172.22.1.249         172.22.1.249         tcp dpt:6379
18       0     0 MASQUERADE  6    --  *      *       172.22.1.6           172.22.1.6           tcp dpt:8983
19       0     0 MASQUERADE  6    --  *      *       172.22.1.8           172.22.1.8           tcp dpt:3306
20       0     0 MASQUERADE  6    --  *      *       172.22.1.10          172.22.1.10          tcp dpt:443
21       0     0 MASQUERADE  6    --  *      *       172.22.1.10          172.22.1.10          tcp dpt:80
22       0     0 MASQUERADE  6    --  *      *       172.22.1.253         172.22.1.253         tcp dpt:587
23       0     0 MASQUERADE  6    --  *      *       172.22.1.253         172.22.1.253         tcp dpt:465
24       0     0 MASQUERADE  6    --  *      *       172.22.1.250         172.22.1.250         tcp dpt:12345
25       0     0 MASQUERADE  6    --  *      *       172.22.1.253         172.22.1.253         tcp dpt:25
26       0     0 MASQUERADE  6    --  *      *       172.22.1.250         172.22.1.250         tcp dpt:4190
27       0     0 MASQUERADE  6    --  *      *       172.22.1.250         172.22.1.250         tcp dpt:995
28       0     0 MASQUERADE  6    --  *      *       172.22.1.250         172.22.1.250         tcp dpt:993
29       0     0 MASQUERADE  6    --  *      *       172.22.1.250         172.22.1.250         tcp dpt:143
30       0     0 MASQUERADE  6    --  *      *       172.22.1.250         172.22.1.250         tcp dpt:110

**This following line (3) is causing the issues, it is masquerading all traffic, regardless of the right IN-interface:**
> **3    38181 2556K MASQUERADE  0    --  *      !br-a985bc74309d  172.22.1.0/24        0.0.0.0/0**

`br-a985bc74309d `is maybe an old docker bridge..?

Delete the line "3" in POSTROUTING chain with the command:
`iptables -t nat -D POSTROUTING 3`

Things now start working again!

**Comment by njalva** [comment] 2024-03-09 22:37
Mismo problema
