### ISSUE TITLE
MySQL needs to run on another server

### ISSUE THREAD

**Issue by ostus2011** [mailcow/mailcow-dockerized#5437] opened 2023-10-02 21:25 UTC
### Summary

I need to move the mySQL server to a different server than the one where mailcown is located. Is it possible to move mySQL to another server? In the file: /opt/mailcow-dockerized/mailcow.conf I have data for the database. However, no IP address appears. 

### Motivation

It would be very helpful if mysql could run independently and in case of failure to be able to connect to a given mysql server again quickly and easily. Of course, only when the IP address variable is provided. First, an attempt should be made to access the database, and if it fails, a new one should be created.

**Comment by MAGICCC** [comment] 2023-10-04 10:39
Dupe of https://github.com/mailcow/mailcow-dockerized/issues/5395 https://github.com/mailcow/mailcow-dockerized/issues/1774 https://github.com/mailcow/mailcow-dockerized/pull/190 https://github.com/mailcow/mailcow-dockerized/issues/456

**Closed as completed by MAGICCC** 2023-10-04 10:39 UTC
Labels: enhancement
