### ISSUE TITLE
"no mailbox selected" on fresh install

### ISSUE THREAD

**Issue by fibaxx** [mailcow/mailcow-dockerized#3342] opened 2020-02-20 19:29 UTC
Please **try** to answer all questions. If you cannot, don't just delete it. If you completely ignore or remove the whole template, **your issue will be closed** with a label "missing information".
Many awesome mailcow supporters don't bother to reply to an issue, when crucial information is missing. Especially when it could have been answered by using this issue template. We need as much information as possible. Please post all logs, do not copy that one line you think may be interesting. Copy the whole bunch and remove sensible information. Thank you!

**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?

I have done the following steps to install mailcow on a fresh server:
=> installed docker from https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
=> downloaded docker compose with `curl -L https://github.com/docker/compose/releases/download/$(curl -Ls https://www.servercow.de/docker-compose/latest.php)/docker-compose-$(uname -s)-$(uname -m) > /usr/local/bin/docker-compose`
=> downloaded mailcow with `git clone https://github.com/mailcow/mailcow-dockerized`
=> generated config with `./generate_config.sh` and prepared mailcow with `docker-compose pull` followed by `docker-compose up -d`

After that i added domain and mailbox. On SOGo, when i login with the new created mailbox, i see the message "no mailbox selected". In the SOGo log are the following messages:

2/20/2020, 8:12:38 PM | notice | [70]: 192.168.1.2 "POST /SOGo/so/mail@domain.com/Mail/unseenCount HTTP/1.0" 200 21/31 0.009 - - 0
-- | -- | --
2/20/2020, 8:12:38 PM | notice | [70]: [ERROR] <0x561f39d90010[SOGoMailAccount]:0> Could not connect IMAP4
2/20/2020, 8:12:38 PM | notice | <0x0x561f39ebb100[NGImap4Client]:  login=mail@domain.com(pwd)  address=<0x0x561f39dd92b0[NGInternetSocketAddress]: host=172.22.1.250  port=993>>
2/20/2020, 8:12:38 PM | notice |  
2/20/2020, 8:12:38 PM | notice |  
2/20/2020, 8:12:38 PM | notice | //mail@domain.com@172.22.1.250/
2/20/2020, 8:12:38 PM | notice | user=mail@domain.com, pwd=yes
2/20/2020, 8:12:38 PM | notice | [70]: [ERROR] <0x0x561f3988e450[NGImap4ConnectionManager]> IMAP4 login failed:
2/20/2020, 8:12:38 PM | notice | [70]: <0x561f39d90010[SOGoMailAccount]:0> renewing imap4 password
2/20/2020, 8:12:38 PM | notice | <0x0x561f39f153a0[NGImap4Client]:  login=mail@domain.com(pwd)  address=<0x0x561f39eeef60[NGInternetSocketAddress]: host=172.22.1.250  port=993>>

The Dovecot log is empty. All containers are shown as green. I tried the installation 2 times with the same result.

**Reproduction of said bug**: How *exactly* do you reproduce the bug?

Do a fresh install of mailcow, create the first mailbox and login to SOGo.

__I have tried or I do...__ *(fill out each checkbox with a `X` if applicable)*
- [X] In case of WebUI issue, I have tried clearing the browser cache and the issue persists.
- [ ] I do run mailcow on a Synology, QNAP or any other sort of NAS.

**System information**

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system | Ubuntu 18.04. |
| Is Apparmor, SELinux or similar active? | No |
| Virtualization technlogy (KVM, VMware, Xen, etc) | KVM |
| Server/VM specifications (Memory, CPU Cores) | 2GB, 2 Cores |
| Docker Version (`docker version`) | 19.03.6 |
| Docker-Compose Version (`docker-compose version`) | 1.25.4 |
| Reverse proxy (custom solution) | No |

Further notes:
 - Output of `git diff origin/master`, any other changes to the code? If so, please post them.
 - All third-party firewalls and custom iptables rules are unsupported. Please check the Docker docs about how to use Docker with your own ruleset. Nevertheless, iptabels output can help _us_ to help _you_: `iptables -L -vn`, `ip6tables -L -vn`, `iptables -L -vn -t nat` and `ip6tables -L -vn -t nat `
 - Check `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @172.22.1.254` (set the IP accordingly, if you changed the internal mailcow network) and `docker exec -it $(docker ps -qf name=acme-mailcow) dig +short stackoverflow.com @1.1.1.1` - output? Timeout?
 
 General logs:
- Please take a look at the [official documentation](https://mailcow.github.io/mailcow-dockerized-docs/debug-logs/).

Thank you for help.

**Comment by shiz0** [comment] 2020-03-02 11:14
maybe similiar to #3352

**Comment by shiz0** [comment] 2020-03-02 13:37
I just tried to reproduce this on Ubuntu Server 18.04 LTS, but unfortunately couldn't.
Everything worked as expected.
Closing this, as it seems to be a support case, rather than an issue.
Maybe you missed something during setup? It may help if you observe the logs.
From within /opt/mailcow-dockerized, call:
docker-compose logs -tf --tail="50" | grep "error\|warning\|Error\|Warning\|ERROR\|WARNING"

Also, feel free to join our community support channel on Telegram: https://t.me/mailcow

**Closed as completed by shiz0** 2020-03-02 13:37 UTC
Labels: support

**Comment by blacksocket** [comment] 2022-04-09 10:15
I have the same issue on Ubuntu Server 18.04 LTS and 20.04 LTS:
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Mail queue health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Clamd health level: 87% (13/15), health trend: -2
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Postfix health level: 50% (4/8), health trend: -4
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Dovecot health level: 17% (2/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Primary certificate expiry check health level: 43% (3/7), health trend: -4
watchdog-mailcow_1   | Sat Apr 9 12:10:50 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:01 CEST 2022 Unbound health level: 40% (2/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:11:11 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:26 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:27 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:33 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:41 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:43 CEST 2022 Postfix health level: 13% (1/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:11:47 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:47 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:47 CEST 2022 Dovecot health level: 0% (0/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:11:48 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:48 CEST 2022 Dovecot hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.001 sec. response time|time=0.001260s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000084s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | Sat Apr 9 12:11:58 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:11:58 CEST 2022 Mail queue health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:11:58 CEST 2022 Dovecot health level: 17% (2/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:12:00 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:01 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:05 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:06 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:09 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:09 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:13 CEST 2022 Unbound health level: 0% (0/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:12:14 CEST 2022 Clamd health level: 73% (11/15), health trend: -2
watchdog-mailcow_1   | Sat Apr 9 12:12:14 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:14 CEST 2022 Unbound hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | Sat Apr 9 12:12:24 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:12:24 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:24 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:25 CEST 2022 Postfix health level: 0% (0/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:12:26 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:26 CEST 2022 Postfix hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | connect to address 172.22.1.253 and port 589: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000123s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.253 and port 589: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000046s;;;0.000000
watchdog-mailcow_1   | SMTP OK - 0.048 sec. response time|time=0.047927s;;;0.000000
watchdog-mailcow_1   | SMTP UNKNOWN - Cannot read EHLO response via TLS.
watchdog-mailcow_1   | SMTP OK - 0.029 sec. response time|time=0.028536s;;;0.000000
watchdog-mailcow_1   | SMTP UNKNOWN - Cannot read EHLO response via TLS.
watchdog-mailcow_1   | Sat Apr 9 12:12:36 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:12:36 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:36 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:37 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:37 CEST 2022 Postfix health level: 63% (5/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:12:38 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:46 CEST 2022 Rspamd health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:50 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:12:51 CEST 2022 Unbound health level: 40% (2/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:13:00 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:00 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:00 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:01 CEST 2022 Dovecot health level: 0% (0/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:13:02 CEST 2022 Dovecot hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.001 sec. response time|time=0.001260s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000084s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000082s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 24: Connection refused
watchdog-mailcow_1   | SMTP CRITICAL - 0.000 sec. response time|time=0.000064s;;;0.000000
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 993: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 143: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 10001: Connection refused
watchdog-mailcow_1   | connect to address 172.22.1.250 and port 4190: Connection refused
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Container is running for less than 360 seconds, skipping action...
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 ACME health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Mail queue health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Redis health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:12 CEST 2022 Dovecot health level: 17% (2/12), health trend: -10
watchdog-mailcow_1   | Sat Apr 9 12:13:22 CEST 2022 SOGo health level: 100% (3/3), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:23 CEST 2022 Nginx health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:30 CEST 2022 MySQL/MariaDB health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:34 CEST 2022 Dovecot replication health level: 100% (20/20), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:39 CEST 2022 Postfix health level: 25% (2/8), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:13:41 CEST 2022 Ratelimit health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:45 CEST 2022 Olefy health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:47 CEST 2022 PHP-FPM health level: 100% (5/5), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:53 CEST 2022 Fail2ban health level: 100% (1/1), health trend: 0
watchdog-mailcow_1   | Sat Apr 9 12:13:53 CEST 2022 Unbound health level: 0% (0/5), health trend: -3
watchdog-mailcow_1   | Sat Apr 9 12:13:54 CEST 2022 Unbound hit error limit
watchdog-mailcow_1   |
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
watchdog-mailcow_1   | CRITICAL - Plugin timed out while executing system call
watchdog-mailcow_1   | DNSSEC failure
unbound-mailcow_1    | [1649498850] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498850] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
unbound-mailcow_1    | [1649498850] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498851] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:9f::42 port 53
unbound-mailcow_1    | [1649498851] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:dc3::35 port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:a8::e port 53
unbound-mailcow_1    | [1649498853] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2d::d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:1::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:503:c27::2:30 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:12::d0d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2d::d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:12::d0d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2d::d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:503:c27::2:30 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:1::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:200::b port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:dc3::35 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fd::1 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:12::d0d port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:1::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:503:c27::2:30 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:7fe::53 port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2::c port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | [1649498854] libunbound[9:0] error: udp connect failed: Address not available for 2001:500:2f::f port 53
unbound-mailcow_1    | Receiving root hints...
######################################################################## 100.0%
