### ISSUE TITLE
Acme-Mailcow will not find DNS records (unbound dns resolver in misconfigured docker)

### ISSUE THREAD

**Issue by colevan94** [mailcow/mailcow-dockerized#3260] opened 2020-01-08 17:01 UTC
**Prior to placing the issue, please check following:** *(fill out each checkbox with a `X` once done)*
- [X ] I understand that not following below instructions might result in immediate closing and deletion of my issue.
- [X ] I have understood that answers are voluntary and community-driven, and not commercial support.
- [X ] I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

---

**Description of the bug**: What kind of issue have you *exactly* come across?
Acme-Mailcow is seeming to have an issue finding my DNS A records although I have verified they are set up correctly and available.

My issue is...
I have a dockerized mailcow installation I have changed any of the default configurations.
**System information**
jake@ubuntu_mail:/opt/mailcow-dockerized$ sudo docker-compose logs -f --tail=100 acme-mailcow
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
Attaching to mailcowdockerized_acme-mailcow_1
acme-mailcow_1       | Wed Jan  8 16:37:14 UTC 2020 - Waiting for Docker API...OK
acme-mailcow_1       | Wed Jan  8 16:37:14 UTC 2020 - Waiting for database... Uptime: 6  Threads: 8  Questions: 113  Slow queries: 0  Opens: 40  Flush tables: 1  Open tables: 28  Queries per second avg: 18.833
acme-mailcow_1       | OK
acme-mailcow_1       | Wed Jan  8 16:37:14 UTC 2020 - Waiting for Nginx... OK
acme-mailcow_1       | Wed Jan  8 16:37:16 UTC 2020 - Waiting for domain table... OK
acme-mailcow_1       | Wed Jan  8 16:37:16 UTC 2020 - Initializing, please wait... 
acme-mailcow_1       | Wed Jan  8 16:37:16 UTC 2020 - Using existing domain rsa key /var/lib/acme/acme/key.pem
acme-mailcow_1       | Wed Jan  8 16:37:16 UTC 2020 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
acme-mailcow_1       | Wed Jan  8 16:37:16 UTC 2020 - Detecting IP addresses... OK
acme-mailcow_1       | Wed Jan  8 16:37:44 UTC 2020 - No A or AAAA record found for hostname autodiscover.XXXXXXXXXXXX.com
acme-mailcow_1       | Wed Jan  8 16:37:44 UTC 2020 - No A or AAAA record found for hostname autoconfig.XXXXXXXXXXXX.com
acme-mailcow_1       | Wed Jan  8 16:37:44 UTC 2020 - No A or AAAA record found for hostname autodiscover.XXXXX.xyz
acme-mailcow_1       | Wed Jan  8 16:37:44 UTC 2020 - No A or AAAA record found for hostname autoconfig.XXXXX.xyz
acme-mailcow_1       | Wed Jan  8 16:37:48 UTC 2020 - No A or AAAA record found for hostname autodiscover.XXXXXXXXX.associates
acme-mailcow_1       | Wed Jan  8 16:37:48 UTC 2020 - No A or AAAA record found for hostname autoconfig.XXXXXXXXXX.associates
acme-mailcow_1       | Wed Jan  8 16:37:48 UTC 2020 - No A or AAAA record found for hostname mail.XXXXX.xyz
acme-mailcow_1       | Wed Jan  8 16:37:48 UTC 2020 - Cannot validate any hostnames, skipping Let's Encrypt for 1 hour.
acme-mailcow_1       | Wed Jan  8 16:37:48 UTC 2020 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
acme-mailcow_1       | OK

Further information (where applicable):

| Question | Answer |
| --- | --- |
| My operating system Ubuntu 18.04.1 LTS
| Is Apparmor, SELinux or similar active? Not that I am aware of
| Virtualization technlogy (KVM, VMware, Xen, etc) This is run on a hardware rack, (dockerized mailcow)
| Server/VM specifications (Memory, CPU Cores) 16GB DDR4, 6 Core 6 Thread 3.6 Ghz Intel CPU
| Docker Version (`docker version`) 18.09
| Docker-Compose Version (`docker-compose version`) 1.24.1
| Reverse proxy (custom solution) There is no reverse proxy

Further notes:
no changes to the mailcow code
 
 General logs:
I can post the general logs --tail=100 but there is a lot of ip domain info to black out etc. I would promptly send in a message to someone who could help if that will work.

**Comment by Adorfer** [comment] 2020-01-08 17:12
does this "No A or AAAA record found for hostname autodiscover.XXXXXXXXXXXX.com" affirm when you look from a nother host? 
in other words: It the DNS record technically existant?

if yes, then your mailcow-unbound is probably not working. 
Potentially it blew so many requests upstream during startup that the hoster/provider is mitigating/blocking DNS-requests from the host for at least some period of time. 
Please check your hosters's status for your account for conditions.

**Comment by colevan94** [comment] 2020-01-08 17:25
When I check DNS from another host, the records are always found correctly, or if I dig from the box mailcow is running on I find the records just fine,

Also, who are you referring to as hoster/provider, if you mean of DNS servers, I provide my own name servers running bind

**Comment by colevan94** [comment] 2020-01-08 17:35
I will also note that this installation has been working fine for almost a year up until what seemed like the most recent update, however I don't exactly know because I noticed the problem when my cert expired today and it wouldn't fetch a new one.

**Comment by andryyy** [comment] 2020-01-08 18:04
Query a name against root dns servers. Or just dig google.com from within acme-mailcow for example. 

`docker-compose exec acme-mailcow dig google.com @unbound`

Querying against Google DNS or simply querying against anything when NOT inside a container does not indicate it will work inside the container and against root dns. You cannot say "works on my host" and compare it with how it works inside the container.

Non resolving issues are mostly firewall problems (local or in front of mailcow).
Ratelimits are also possible, not sure though. 

Checked ufw and firewalld?

**Comment by colevan94** [comment] 2020-01-08 18:14
Ahh, thank you for that @andryyy I was wondering how that was done.. output from the follow, :sudo docker-compose exec acme-mailcow dig google.com @unbound

mail:/opt/mailcow-dockerized$ sudo docker-compose exec acme-mailcow dig google.com @unbound
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.

; <<>> DiG 9.14.7 <<>> google.com @unbound
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 34952
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;google.com.			IN	A

;; ANSWER SECTION:
google.com.		300	IN	A	64.233.177.101
google.com.		300	IN	A	64.233.177.139
google.com.		300	IN	A	64.233.177.113
google.com.		300	IN	A	64.233.177.102
google.com.		300	IN	A	64.233.177.138
google.com.		300	IN	A	64.233.177.100

;; Query time: 2827 msec
;; SERVER: fd4d:6169:6c63:6f77::a#53(fd4d:6169:6c63:6f77::a)
;; WHEN: Wed Jan 08 18:10:31 UTC 2020
;; MSG SIZE  rcvd: 135


&&& I checked UFW and Firewalld are not running

**Comment by colevan94** [comment] 2020-01-08 18:25
Also this is the output, when I try to dig my mailcow hostname from inside the container:
 sudo docker-compose exec acme-mailcow dig mail.XXXXX.xyz @unbound
WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.

; <<>> DiG 9.14.7 <<>> mail.XXXXX.xyz @unbound
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 35611
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;mail.XXXXX.xyz.			IN	A

;; Query time: 2 msec
;; SERVER: 172.22.1.254#53(172.22.1.254)
;; WHEN: Wed Jan 08 18:15:06 UTC 2020
;; MSG SIZE  rcvd: 43

**Comment by andryyy** [comment] 2020-01-08 19:28
That's actually good. :)

Can you grant me access via info@servercow.de ? Would like to debug it.

**Comment by andryyy** [comment] 2020-01-08 19:28
Oh, wait, SERVFAIL.

Can you check wether DNSSEC is broken on your domain? Just mail me the hostname.

**Comment by colevan94** [comment] 2020-01-08 19:59
I just emailed the hostname to info@servercow.de

**Closed as completed** 2020-03-02 02:44 UTC

**Comment by Kinark** [comment] 2020-03-22 19:08
Having exactly the same issue here. Dig works, but mailcow cannot find hostnames :/

**Comment by andryyy** [comment] 2020-03-22 19:18
`dig xyz @unbund` works?

**Comment by Kinark** [comment] 2020-03-22 19:29
@andryyy Nope, it doesn't seem so :(
![image](https://user-images.githubusercontent.com/17537081/77258607-552b9f00-6c5a-11ea-9eb4-e83d88b07a4b.png)

**Comment by Conan179** [comment] 2020-03-22 19:31
you have to replace xyz with a correct addrese;) e.g. google.de

**Comment by Kinark** [comment] 2020-03-22 19:33
Oops, sorry. But no, it doesn't work either:
![image](https://user-images.githubusercontent.com/17537081/77258660-d7b45e80-6c5a-11ea-9cac-0722b3429343.png)

**Comment by andryyy** [comment] 2020-03-22 19:34
Then sometimes is wrong with your network. Could be a firewall, local netfilter issues etc.

Not a bug in mailcow, sorry. :(

Try the Telegram channel for help.

**Comment by Kinark** [comment] 2020-03-22 19:36
@andryyy Oh, that's unfortunate (or not lol). Could you help me a little and explain what @unbound means?

**Comment by Kinark** [comment] 2020-03-22 19:37
Ignore meeeee, I got it :)

**Comment by andryyy** [comment] 2020-03-22 20:14
\o/ Please join the Telegram channel, we can help you there much better. Or the community. :)

**Comment by Kinark** [comment] 2020-03-22 20:15
@andryyy Of course, will do it now!
