### ISSUE TITLE
Please use Github releases and tags

### ISSUE THREAD

**Issue by greenmoss** [mailcow/mailcow-dockerized#2902] opened 2019-09-02 16:30 UTC
**Is your feature request related to a problem? Please describe.**
No problems; this project is great! Kudos to you all for developing it!

**Describe the solution you'd like**
It would be useful if the Github page included releases and tags. Right now there are zero releases and tags.

<img width="762" alt="Screen Shot 2019-09-02 at 12 29 22 PM" src="https://user-images.githubusercontent.com/134408/64126827-53ad8e80-cd7d-11e9-8d23-d2e9d310cd88.png">

**Additional context**
This allows me to "watch" the project for releases, so I can download whatever is deemed "stable".

**Comment by mkuron** [comment] 2019-09-02 17:27
Duplicate of #971. The dev branch mentioned there isn‘t used anymore though. Please see there why a release model doesn‘t work for us, but we certainly understand why you would want there to be releases. Basically, the current master is considered stable if there haven’t been any new commits for a few hours...

**Comment by andryyy** [comment] 2019-09-02 17:28
Things work a bit different with us, but they usually work. 😄

**Closed as completed by mkuron** 2019-09-02 17:27 UTC

**Comment by greenmoss** [comment] 2019-09-02 19:02
Ah sorry. I searched open GH issues for "release", but not closed issues. Sorry for the spam!
