### ISSUE TITLE
Update policy new docker containers

### ISSUE THREAD

**Issue by xetorixik** [mailcow/mailcow-dockerized#1290] opened 2018-04-19 16:38 UTC
Is there a fixed moment (say once a month for example) when new docker containers are pushed from dev branch to the master branch?

**Comment by MAGICCC** [comment] 2018-04-19 16:41
Sadly, there isn't a proper 'release cycle'

**Comment by mkuron** [comment] 2018-04-19 16:41
No. Also, duplicate of #971.

**Closed as completed by mkuron** 2018-04-19 16:41 UTC

**Comment by xetorixik** [comment] 2018-04-19 16:53
Cristal clear. 
Couldn't find #971 as in didn't searched on "release model"
Perhaps it is an idea to include it in the documentation. To prevent "same" follow-up questions.
Thanks everyone for the replies.

**Comment by andryyy** [comment] 2018-04-19 16:58
We should add it. :-) You can push that to the docs, if you like to.

**Comment by xetorixik** [comment] 2018-04-19 17:44
@andryyy Consider it done.
