### ISSUE TITLE
specific hostnames for autoconfig / autodiscover

### ISSUE THREAD

**Issue by imp1sh** [mailcow/mailcow-dockerized#1723] opened 2018-08-29 08:06 UTC
We want the users to use specific hostnames for the mail client depending on what domain name they use for Email. That means we can migrate the users of that domain in the future more easily, without changing the hostnames in all the clients.

The corresponding DNS records are there already. When the client tries to autoconfigure in Thunderbird it fetches something like this:
https://autoconfig.domain.name/mail/config-v1.1.xml and extracts the hostname from that xml file, right?
The hostnames in that xml files are the default hostname though. Can we somehow specify other names?

What about other clients that do ActiveSync? Do they also fetch that xml or do they auto configure differently? Can we use specific names here instead of the default hostname?
Thank you

**Comment by mkuron** [comment] 2018-08-29 11:38
Duplicate of #528. This is not supported.

**Closed as completed by mkuron** 2018-08-29 11:38 UTC
Labels: enhancement

**Comment by imp1sh** [comment] 2018-08-30 13:19
Can you please consider this a feature request.

**Comment by andryyy** [comment] 2018-08-30 13:20
Si

**Comment by RedFoxy** [comment] 2021-04-27 22:34
Any update about that? I prefer to have domain specific dns for imap/pop/smtp too
