### ISSUE TITLE
Differents Subdomains 

### ISSUE THREAD

**Issue by jose123455587** [mailcow/mailcow-dockerized#2581] opened 2019-05-07 21:17 UTC
Hi,
Can I have for example one subdomain for postfix/dovecot and roundcube (mail.example.com) and for control panel other (control.example.com for example)?If yes how can I do it?

**Comment by mkuron** [comment] 2019-05-08 05:26
Duplicate of #393 (well, that one is about subdirectories, but the problem is the same). it is not supported, but you can do it with some custom nginx configuration.

**Closed as completed by mkuron** 2019-05-08 05:26 UTC
