### ISSUE TITLE
Broadcast Message to All Accounts

### ISSUE THREAD

**Issue by andreas-git** [mailcow/mailcow-dockerized#1212] opened 2018-03-28 15:14 UTC
Hallo,

is there a way to setup a broadcast message to all accounts and domains ?
For example: The server will go down for maintaince or update etc....

Best Regards

Andreas

**Comment by mkuron** [comment] 2018-03-28 16:08
Duplicate of #842

**Closed as completed by mkuron** 2018-03-28 16:08 UTC
