### ISSUE TITLE
Send postscreen to quarantine

### ISSUE THREAD

**Issue by guidtz** [mailcow/mailcow-dockerized#3031] opened 2019-10-11 13:17 UTC
Hello,

**Is your feature request related to a problem? Please describe.**
Some domains (for example free.fr) are blocked because of registred blacklist :
`NOQUEUE: reject: RCPT from [212.27.42.5]:20826: 550 5.7.1 Service unavailable; client [212.27.42.5] blocked using hostkarma.junkemailfilter.com`

**Describe the solution you'd like**
I would like no to bloc them but to pass them to quarantine.

How I could change this ?

Regards

**Comment by mkuron** [comment] 2019-10-11 18:10
Duplicate of #2829.

**Closed as completed by mkuron** 2019-10-11 18:10 UTC
