### ISSUE TITLE
SOGo SSO

### ISSUE THREAD

**Issue by VPaulV** [mailcow/mailcow-dockerized#5222] opened 2023-05-04 04:22 UTC
### Summary

Hello everyone,

I was wondering if it's possible to implement Single Sign-On (SSO) for SOGo? It doesn't seem necessary to log in twice - once for the mailcow interface and again for SOGo - especially since they use the same login and password. We already have the ALLOW_ADMIN_EMAIL_LOGIN functionality, perhaps we could reuse it for this purpose?

Thank you for considering my idea!

### Motivation

I think it is redundant to have to log in twice with the same credentials when SOGo is already integrated into the mailcow web interface

**Comment by MAGICCC** [comment] 2023-05-04 08:42
Dupe of https://github.com/mailcow/mailcow-dockerized/issues/2316
There will be a SSO soon

**Closed as completed by MAGICCC** 2023-05-04 08:42 UTC
Labels: enhancement
