### ISSUE TITLE
Let's Encrypt cert issue problem.

### ISSUE THREAD

**Issue by 80kk** [mailcow/mailcow-dockerized#2797] opened 2019-07-20 18:36 UTC
Hi, I am new to mailcow. I actually just installed it. I am trying to issue Let's Encrypt cert for my domain but wit no luck:

I have IPv6 tunnel from HE and all required ports are opened on firewall:
    
    /opt/mailcow-dockerized# ip6tables -nL
    Chain INPUT (policy DROP)
    target     prot opt source               destination         
    MAILCOW    all      ::/0                 ::/0                
    ACCEPT     all      ::/0                 ::/0                
    ACCEPT     all      ::/0                 ::/0                 state RELATED,ESTABLISHED
    DROP       all      ::/0                 ::/0                 rt type:0
    ACCEPT     all      fe80::/10            ::/0                
    ACCEPT     all      ::/0                 ff00::/8            
    ACCEPT     icmpv6    ::/0                 ::/0                
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:25
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:80
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:110
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:143
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:443
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:465
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:587
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:993
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:995
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:4190
    ACCEPT     tcp      ::/0                 ::/0                 tcp dpt:65000
    LOG        all      ::/0                 ::/0                 LOG flags 0 level 4
    DROP       all      ::/0                 ::/0                
    
    Chain FORWARD (policy DROP)
    target     prot opt source               destination         
    DOCKER-ISOLATION  all      ::/0                 ::/0                
    DOCKER     all      ::/0                 ::/0                
    ACCEPT     all      ::/0                 ::/0                 ctstate RELATED,ESTABLISHED
    ACCEPT     all      ::/0                 ::/0                
    ACCEPT     all      ::/0                 ::/0                
    MAILCOW    all      ::/0                 ::/0                
    DROP       all      ::/0                 ::/0                 rt type:0
    
    Chain OUTPUT (policy DROP)
    target     prot opt source               destination         
    ACCEPT     all      ::/0                 ::/0                
    ACCEPT     all      ::/0                 ::/0                 state NEW,RELATED,ESTABLISHED
    DROP       all      ::/0                 ::/0                 rt type:0
    ACCEPT     all      fe80::/10            ::/0                
    ACCEPT     all      ::/0                 ff00::/8            
    ACCEPT     icmpv6    ::/0                 ::/0                
    
    Chain DOCKER (1 references)
    target     prot opt source               destination         
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:443
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::11  tcp dpt:80
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::c  tcp dpt:110
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::c  tcp dpt:143
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::c  tcp dpt:4190
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::c  tcp dpt:993
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::c  tcp dpt:995
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::3  tcp dpt:25
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::3  tcp dpt:465
    ACCEPT     tcp      ::/0                 fd4d:6169:6c63:6f77::3  tcp dpt:587
    
    Chain DOCKER-ISOLATION (1 references)
    target     prot opt source               destination         
    RETURN     all      ::/0                 ::/0                
    
    Chain MAILCOW (2 references)
    target     prot opt source               destination         
    

I have tried:

    
    /opt/mailcow-dockerized# mv data/assets/ssl data/assets/ssl_backup
        /opt/mailcow-dockerized# cp -rp data/assets/ssl-example/ data/assets/ssl
    /opt/mailcow-dockerized# docker-compose restart acme-mailcow
    WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
    Restarting mailcowdockerized_acme-mailcow_1 ... done
    /opt/mailcow-dockerized# docker-compose logs --tail=200 -f acme-mailcow
    WARNING: The WATCHDOG_NOTIFY_EMAIL variable is not set. Defaulting to a blank string.
    Attaching to mailcowdockerized_acme-mailcow_1
    acme-mailcow_1       | Sat Jul 20 19:19:19 CEST 2019 - Waiting for Docker API...OK
    acme-mailcow_1       | Sat Jul 20 19:19:19 CEST 2019 - Waiting for database... Uptime: 11  Threads: 35  Questions: 327  Slow queries: 0  Opens: 45  Flush tables: 1  Open tables: 37  Queries per second avg: 29.727
    acme-mailcow_1       | OK
    acme-mailcow_1       | Sat Jul 20 19:19:19 CEST 2019 - Waiting for Nginx... OK
    acme-mailcow_1       | Sat Jul 20 19:19:19 CEST 2019 - Waiting for domain table... OK
    acme-mailcow_1       | Sat Jul 20 19:19:20 CEST 2019 - Initializing, please wait... 
    acme-mailcow_1       | Sat Jul 20 19:19:20 CEST 2019 - Using existing domain key /var/lib/acme/acme/key.pem
    acme-mailcow_1       | Sat Jul 20 19:19:20 CEST 2019 - Using existing Lets Encrypt account key /var/lib/acme/acme/account.pem
    acme-mailcow_1       | Sat Jul 20 19:19:20 CEST 2019 - Detecting IP addresses... OK
    acme-mailcow_1       | Validated CAA for parent domain domain.pl
    acme-mailcow_1       | Sat Jul 20 19:19:56 CEST 2019 - Found AAAA record for autodiscover.domain.pl: 2001:470:71:12e::4 - skipping A record check
    acme-mailcow_1       | Sat Jul 20 19:19:56 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname autodiscover.domain.pl (2001:1234:4567:012e:0000:0000:0000:0004)
    acme-mailcow_1       | Sat Jul 20 19:19:56 CEST 2019 - Found AAAA record for autoconfig.domain.pl: 2001:470:71:12e::4 - skipping A record check
    acme-mailcow_1       | Sat Jul 20 19:19:57 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname autoconfig.domain.pl (2001:1234:4567:012e:0000:0000:0000:0004)
    acme-mailcow_1       | Sat Jul 20 19:19:57 CEST 2019 - Found AAAA record for mail.domain.pl: 2001:470:71:12e::4 - skipping A record check
    acme-mailcow_1       | Sat Jul 20 19:19:57 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname mail.domain.pl (DNS returned 2001:1234:4567:012e:0000:0000:0000:0004)
    acme-mailcow_1       | Sat Jul 20 19:19:57 CEST 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
    acme-mailcow_1       | Sat Jul 20 19:19:57 CEST 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
    acme-mailcow_1       | OK
    acme-mailcow_1       | Sat Jul 20 20:15:13 CEST 2019 - Waiting for Docker API...OK
    acme-mailcow_1       | Sat Jul 20 20:15:13 CEST 2019 - Waiting for database... Uptime: 3365  Threads: 32  Questions: 7056  Slow queries: 0  Opens: 60  Flush tables: 1  Open tables: 52  Queries per second avg: 2.096
    acme-mailcow_1       | OK
    acme-mailcow_1       | Sat Jul 20 20:15:13 CEST 2019 - Waiting for Nginx... OK
    acme-mailcow_1       | Sat Jul 20 20:15:13 CEST 2019 - Waiting for domain table... OK
    acme-mailcow_1       | Sat Jul 20 20:15:13 CEST 2019 - Initializing, please wait... 
    acme-mailcow_1       | Sat Jul 20 20:15:13 CEST 2019 - Generating missing domain private key...
    acme-mailcow_1       | Generating RSA private key, 4096 bit long modulus (2 primes)
    acme-mailcow_1       | .....++++
    acme-mailcow_1       | ..........................................................................................................++++
    acme-mailcow_1       | e is 65537 (0x010001)
    acme-mailcow_1       | Sat Jul 20 20:15:14 CEST 2019 - Generating missing Lets Encrypt account key...
    acme-mailcow_1       | Generating RSA private key, 4096 bit long modulus (2 primes)
    acme-mailcow_1       | ............................++++
    acme-mailcow_1       | ...................................++++
    acme-mailcow_1       | e is 65537 (0x010001)
    acme-mailcow_1       | Sat Jul 20 20:15:15 CEST 2019 - Detecting IP addresses... OK
    acme-mailcow_1       | Validated CAA for parent domain domain.pl
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Found AAAA record for autodiscover.domain.pl: 2001:470:71:12e::4 - skipping A record check
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname autodiscover.domain.pl (2001:1234:4567:012e:0000:0000:0000:0004)
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Found AAAA record for autoconfig.domain.pl: 2001:470:71:12e::4 - skipping A record check
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname autoconfig.domain.pl (2001:1234:4567:012e:0000:0000:0000:0004)
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Found AAAA record for mail.domain.pl: 2001:470:71:12e::4 - skipping A record check
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Cannot match your IP NO_IPV6_LINK against hostname mail.domain.pl (DNS returned 2001:1234:4567:012e:0000:0000:0000:0004)
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Cannot validate hostnames, skipping Let's Encrypt for 1 hour.
    acme-mailcow_1       | Sat Jul 20 20:15:51 CEST 2019 - Use SKIP_LETS_ENCRYPT=y in mailcow.conf to skip it permanently.
    acme-mailcow_1       | OK
    
Any ideas?

**Comment by liquidat** [comment] 2019-07-21 23:44
Sounds like a duplicate of #1737. Can you please follow the troubleshooting in that and all other related issues and let us know of the outcome?

**Comment by andryyy** [comment] 2019-07-22 04:53
RA could indeed be the issue here.

**Closed as completed** 2019-09-27 06:28 UTC
