### ISSUE TITLE
Sync Jobs with own parameter and space in them

### ISSUE THREAD

**Issue by sh-hilden** [mailcow/mailcow-dockerized#2534] opened 2019-04-15 09:08 UTC
I want to add an Sync Job which only download the inbox folder of my external mail account.
If I add 
`--folder "INBOX"` or `--folder INBOX` 
to the custom parameters I get the error: Unknown option: folder "inbox"
I have also tried 
`--include "^INBOX$"` 
with an empty exclude field but their I get the same error.
If  I enter commands without an space they work. Like `--dry`

**Comment by jlelse** [comment] 2019-04-15 11:26
I got the same error yesterday with regextrans2, when I tried a regex to move all mails to one folder. Gave up in the end.

**Comment by markus-seidl** [comment] 2019-05-02 17:21
Exactly the same problem, imapsync states, there may be a quoting issue. But without seeing the actual command line we can only guess.

**Comment by andryyy** [comment] 2019-05-02 20:09
https://github.com/mailcow/mailcow-dockerized/issues/2017

@hunter-nl may help

**Comment by andryyy** [comment] 2019-05-02 20:20
I mean ... we could get rid of that Perl stuff. :-D I don't know why we keep fixing it.

**Comment by hunter-nl** [comment] 2019-05-02 22:32
You should not use any quotes. The field in the web interface is just 1 string. This gets split on the -- characters (not on any spaces). Then each parameter will be added in quotes when the sync job command is executed. The = character behind the parameter is needed if parameter has a value 
Example:
`--addheader --domino1 --resyncflags --f1f2=Deleted Messages=Trash --f1f2=Sent Messages=Sent`
`--f1f2` is the parameter, `Deleted Messages=Trash` the value.

@sh-hilden Try `--folder=INBOX`

@andryyy imapsync script version 1.937 has been released (https://imapsync.lamiral.info There is also a docker image available https://hub.docker.com/r/gilleslamiral/imapsync/
imapsync script download location and other perl module requirements can be found in the dockerfile). It provides some useful fixes. However, It does not "fix" the issue above. The issue above caused by the way the shell command is combined and is executed. Maybe this part can get some improvement by doing this differently.

**Comment by andryyy** [comment] 2019-05-02 22:39
Oh, I will try to update asap. Please remind me if I forget. 

Id gladly donate to you for fixing this issue. :)

**Comment by hunter-nl** [comment] 2019-05-02 22:45
When I got back from my business travel, I'll have a look to try to fix the "issue" ;-)

**Comment by andryyy** [comment] 2019-05-03 07:50
@hunter-nl That would be amazing!

**Comment by markus-seidl** [comment] 2019-05-03 08:51
For completeness using `--folder=INBOX` works for me. If this is the "default" use case, maybe a simple reference in the docs would be helpful. (I've searched in them ;) )

And much thanks to you for the quick response!

**Comment by andryyy** [comment] 2019-05-03 08:52
Doc updates are so, so, so welcome. Please update the docs, guys. :-(

**Comment by hunter-nl** [comment] 2019-05-04 12:50
@andryyy I've created a pull request #2576 to fix it (including some other bugs fixed with imapsync jobs).
Documentation is also updated https://github.com/mailcow/mailcow-dockerized-docs/pull/146

**Comment by andryyy** [comment] 2019-05-04 21:04
Oh, damn, that's really dangerous what you did there. 

It breaks every single sync job that contains special chars in excludes. Even the default exclude will break!

I also think I can inject code. You just use "\`\`" to run the command, stuff like the exclude is not at all escaped. O_O

**Closed as completed** 2019-07-10 22:46 UTC
