### ISSUE TITLE
U2F authentication has stopped working

### ISSUE THREAD

**Issue by asirinelli** [mailcow/mailcow-dockerized#937] opened 2018-01-18 20:49 UTC
Hi,

Recent changes have made 2FA method U2F non-functionnal anymore. While mailcow UI shows the pop-up requiring the U2F key to be triggered, the browser is not initiating the authentication request. I have tried with Firefox and Chromium.

In the same way, I cannot register anymore a new U2F key with the same symptoms: when I am supposed to enroll the key, the browser seems not to receive the request.

For those stuck, here is the way to disable the 2FA for a given user:

```
$ source mailcow.conf
$ docker-compose exec mysql-mailcow mysql -u${DBUSER} -p${DBPASS} ${DBNAME}
MariaDB [mailcow]> delete from tfa where username = "user";
```

**Comment by Braintelligence** [comment] 2018-01-18 20:58
Thanks for the heads-up, though this is a duplicate of #936

**Comment by andryyy** [comment] 2018-01-18 21:13
Shame on me, shame, shame, shame...

Fixed.

**Closed as completed by andryyy** 2018-01-18 21:13 UTC

**Comment by Braintelligence** [comment] 2018-01-18 21:18
Perfect! Even Firefox works now out of the box 👍 .
