### ISSUE TITLE
SOGo's search "Entire message" is only the body

### ISSUE THREAD

**Issue by jhesketh** [mailcow/mailcow-dockerized#2336] opened 2019-02-15 14:07 UTC
This is more likely a bug for SOGo, but when using "entire message" in the search option, it appears to only be searching the body of the message. Is it possible to configure which fields solr searches by default? If so, I would suggest we include all fields.

**Comment by andryyy** [comment] 2019-02-16 00:21
Please test with the new Sorl image. Run a fts rescan -A before. please.

**Comment by andryyy** [comment] 2019-02-16 00:25
Okay, forget it. It searches the body:

```
path=/select params={q={!lucene+q.op%3DAND}body:entire\-message&fl=uid,score&sort=uid+asc&fq=%2Bbox:6e8fe9038614575cb0580000a52c1685+%2Buser:andre@develcow.de&rows=77&wt=xml}
```

If you want to change this, submit a PR to SOGo. :) A lang update would probably do it, too. Or just a bug report.

I will close this, as it is "working as intended".

**Closed as completed by andryyy** 2019-02-16 00:25 UTC
