### ISSUE TITLE
SOGo autoreply messages doesn't go through relay host

### ISSUE THREAD

**Issue by proea** [mailcow/mailcow-dockerized#1473] opened 2018-06-10 15:07 UTC
Hi,

SOGo autoreply messages doesn't go through relay host

(domain is configured to send emails via relay host)

**Comment by mkuron** [comment] 2018-06-10 15:13
Duplicate of #1189. Sieve rules (and the autoreply is one) don‘t currently go through the relayhost.

**Closed as completed by mkuron** 2018-06-10 15:13 UTC

**Comment by andryyy** [comment] 2018-06-10 16:14
You can use a workaround for sieve autoreplies.

Set...
```
plugin {
  blabla
  sieve_vacation_send_from_recipient = yes
  blabla
}
```
in data/conf/dovecot/dovecot.conf and restart dovecot-mailcow.

Read more about the side effects => https://wiki2.dovecot.org/Pigeonhole/Sieve/Extensions/Vacation
