### ISSUE TITLE
Any way to use Proxmox Mail Gateway with Mailcow?

### ISSUE THREAD

**Issue by marrobHD** [mailcow/mailcow-dockerized#2727] opened 2019-06-26 12:52 UTC
Any way to use Proxmox Mail Gateway with Mailcow. What I have to configure?
Thanks
~Marlon

**Comment by Adorfer** [comment] 2019-06-26 14:47
What do you want to accomplish? "Some way": Certainly. 
What is the setup you have in mind? How are roles split and does the additional benefit outperforms the more compliated maintenance of 2 systems which have to be kept in sync in some of the other way.

**Comment by andryyy** [comment] 2019-06-26 15:13
Yep. Would be hard to maintain. But could work somehow.

**Comment by mkuron** [comment] 2019-06-26 16:13
Duplicate of #1172.

**Closed as completed by mkuron** 2019-06-26 16:13 UTC
