### ISSUE TITLE
Multiple outgoing IP

### ISSUE THREAD

**Issue by feldsam** [mailcow/mailcow-dockerized#1784] opened 2018-09-20 08:44 UTC
Hello, is there a simple solution to send emails from multiple IPv4 and IPv6? I have single IPv4 and IPv6 and google rate limit me. On old infra (ispconfig) I have multiple outgoing IPs.. Thank you for reply

**Comment by mkuron** [comment] 2018-09-20 11:12
Duplicate of #1273 and no, that is not supported. If Google is rate-limiting you, you are probably sending way too much email.

**Closed as completed by mkuron** 2018-09-20 11:12 UTC

**Comment by feldsam** [comment] 2018-09-20 19:44
looks like that mailauth-reports@google.com have set standard limit of receiving messages according to this https://support.google.com/a/answer/1366776

Probably, at same time others also send reports and it is limited to 60 per minute...

```
<mailauth-reports@google.com>: host aspmx.l.google.com[64.233.166.26] said:
   550-5.2.1 The user you are trying to contact is receiving mail at a rate
   that 550-5.2.1 prevents additional messages from being delivered. For more
   550-5.2.1 information, please visit 550 5.2.1
   https://support.google.com/mail/?p=ReceivingRatePerm
   t17-v6si10692513wru.207 - gsmtp (in reply to RCPT TO command)
Reporting-MTA: dns; mail.feldhost.cz
X-Postfix-Queue-ID: 240951EE76C9
X-Postfix-Sender: rfc822; admin@feldhost.cz
Arrival-Date: Tue, 18 Sep 2018 10:41:31 +0200 (CEST)

Final-Recipient: rfc822; mailauth-reports@google.com
Original-Recipient: rfc822;mailauth-reports@google.com
Action: failed
Status: 5.2.1
Remote-MTA: dns; aspmx.l.google.com
Diagnostic-Code: smtp; 550-5.2.1 The user you are trying to contact is
   receiving mail at a rate that 550-5.2.1 prevents additional messages from
   being delivered. For more 550-5.2.1 information, please visit 550 5.2.1
   https://support.google.com/mail/?p=ReceivingRatePerm
   t17-v6si10692513wru.207 - gsmtp

From: "Rspamd" <admin@feldhost.cz>
Subject: Report Domain: gmail.com Submitter: feldhost.cz Report-ID: <gmail.com.1537142400.1537228800>
Date: 18 September 2018 at 10:41:31 CEST
To: mailauth-reports@google.com
```

**Comment by mkuron** [comment] 2018-09-20 20:29
Is that it a DMARC report? I don't think we send reports by default; did you configure it as described on https://www.rspamd.com/doc/modules/dmarc.html ? if you are only getting rate-limited due to that, just disable the reports.

**Comment by feldsam** [comment] 2018-09-20 20:32
Yes, I configure it by rspamd manual. I figure out that I am actualy not rate limited, that inbox mailauth-reports@google.com has rate limit, so it is not on sender side....
