### ISSUE TITLE
Show SOGo on mail.mydomain.com and mailcow login on mydomain.com/admin

### ISSUE THREAD

**Issue by mostym** [mailcow/mailcow-dockerized#2352] opened 2019-02-21 07:49 UTC
Hi all, let me start by saying I love mailcow!  Setup is a breeze;  it's well documented and is just beautifully developed.

I don't know if anyone has requested this before, but I would like to have the SOGo groupware app show up first when I go to mail.mydomain.com instead of showing the mailcow login first.  Then, I would like the mailcow login to show on mail.mydomain.com/admin

Thanks for all your hardwork!

**Comment by mkuron** [comment] 2019-02-21 07:55
Duplicate of #393. please check existing issues before opening a new one.

**Closed as completed by mkuron** 2019-02-21 07:55 UTC

**Comment by mostym** [comment] 2019-02-21 08:15
@mkuron The listed issue requires modifications to the core of mailcow, I am asking that this modification be enabled during install or with a simple switch.

**Comment by mkuron** [comment] 2019-02-21 08:16
One of the other duplicates of #393 asked precisely for that.

**Comment by mostym** [comment] 2019-02-21 08:17
Soooo many words... lol.  How close is that to being implemented, if at all. :)

**Comment by andryyy** [comment] 2019-02-21 11:37
Not close, but someone could add it to the docs (tm).
