### ISSUE TITLE
Use Roundcube instead of SOGo

### ISSUE THREAD

**Issue by jm3west** [mailcow/mailcow-dockerized#2375] opened 2019-02-28 08:42 UTC
If I had a free wish ....

A question on generate_config.sh "want you install sogo or roundcube"

In other words without sogo then with roundcube

**Comment by hachre** [comment] 2019-02-28 13:55
SOGo is required for much of the functionality, like the ActiveSync, support for CalDAV and CardDAV and so on. 

Roundcube is quite easy to install. Just download it from them, extract it into `data/web/rc` or another folder name of your choice, besides `rc` and configure it as it is described here:
https://mailcow.github.io/mailcow-dockerized-docs/third_party-roundcube/

**Comment by christianbur** [comment] 2019-02-28 16:59
or use the docker image for roundcube, I prefer this variant because I don't have to touch mailcow.
I use haproxy before mailcow and roundcube, so both are reachable under separate urls. In roundcube I use the official IMAP and SMTP domains of mailcow. 

https://github.com/roundcube/roundcubemail-docker
https://hub.docker.com/r/roundcube/roundcubemail

**Comment by Adorfer** [comment] 2019-04-29 23:13
is this a general thread for all type of wishes/suggestions or is it specific to the first one here? in this case the subject should be less Clickbait.

**Comment by mkuron** [comment] 2019-04-30 05:22
Duplicate of #13 and #120.

**Closed as completed by mkuron** 2019-04-30 05:22 UTC

**Comment by gentoosys** [comment] 2024-11-26 09:05
I also want roundcube instead of sogo. Because of this I use iredmail, but I like mailcow
