### ISSUE TITLE
Wishlist: integrate Roundcube Calendar

### ISSUE THREAD

**Issue by Miyamoto72** [mailcow/mailcow-dockerized#3187] opened 2019-12-03 09:14 UTC
I'd really love to work with Roundcube, because it fits my needs better, but so far the RC integration (as explained in the mailcow dockerized docs) lacks integration for the calendar plugin.

Maybe this could be integrated, too?

**Comment by andryyy** [comment] 2019-12-03 10:50
Hi,

You can create a PR with these changes. :)

**Comment by Miyamoto72** [comment] 2019-12-03 11:47
Well, so far my knowledge about data structures in both Roundcube and SOGo, SQL and PHP are excessively limited, if not to say non-existent. Otherwise I'd be happy to help out on this - my strengths are more at translating stuff.

**Comment by mkuron** [comment] 2019-12-03 12:26
Duplicate of #3056

**Closed as completed** 2020-02-08 14:32 UTC
