### ISSUE TITLE
SOGo stops suddenly

### ISSUE THREAD

**Issue by axd** [mailcow/mailcow-dockerized#538] opened 2017-08-29 05:02 UTC
Hi,

I've been using Mailcow for a while, I've noticed that after a few days (1 week or so) SOGo stops working, keeps running but sometimes the web interface loads but I can't log into my email accounts, and other times it returns a 404 error.

I have configured Exchange email account in my phone, and I am not able to receive emails (the account don't sync) I have to restart SOGO container manually to make it work again, not sure what is the reason of this issue.

Any ideas?

Regards.

**Comment by mkuron** [comment] 2017-08-29 05:23
Is there anything in the logs at the time it breaks? `docker-compose logs sogo-mailcow`

**Comment by axd** [comment] 2017-08-29 05:59
@mkuron Well I can't find an error in specific, but I'm pasting the entries where I think everything begin, it only repeats the same stuff:

```
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19231]: 100.0.0.1 "POST /SOGo/Microsoft-Server-ActiveSync?Cmd=Ping&User=user%40domain.com&DeviceId=androidc1234567890&DeviceType=Android HTTP/1.0" 200 13/225 279.291 - - 256K // Last query without errors...
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b215e1d0[WOWatchDogChild]> sending terminate signal to pid 19231
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21551f0[WOWatchDogChild]> child 19229 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c 2017-08-26 12:49:20.472 sogod[19231:19231] Forcing termination of EAS loop.
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b22bcf90[WOWatchDogChild]> child 19223 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b214d150[WOWatchDogChild]> child 19226 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b2177980[WOWatchDogChild]> child 19234 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b213cf20[WOWatchDogChild]> child 19221 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b213c8e0[WOWatchDogChild]> child 19219 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b2154bb0[WOWatchDogChild]> child 19228 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b215e420[WOWatchDogChild]> child 19232 exited
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b21859d0[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Aug 26 12:49:20 5eccb62b1f9c sogod [19214]: <0x0x7f42b2122740[WOWatchDogChild]> child 19215 exited
so

#and so on... 
```

**Comment by cklabautermann** [comment] 2017-08-29 06:32
Hello,
I have had a similar problem, too. Sogo stopped running suddenly after 1-3 days. No logfile entries which would explain the reason.
However Sogo wasn´t running anymore at all, nginx showed an error page.
After updating mailcow via the update script last wednesday or thursday (I think) I have not had SOGo crashes anymore.
Best regards,
Claudio

**Comment by axd** [comment] 2017-08-30 03:40
UPDATE:

Today happen again, but today I tried to restart SOGo from admin web panel and this error appears:

![image](https://user-images.githubusercontent.com/205403/29854355-9e21fc66-8d02-11e7-873d-276630c9e1c7.png)

And I had to restart the container manually.

**Comment by afzalarsalan** [comment] 2017-08-31 08:40
In an attempt to triage this issue, do both of you happen to use reverse proxies in front of your docker containers? I have experienced this issue as well and I'm presuming this has something to do with it

**Comment by andryyy** [comment] 2017-08-31 08:48
I think I have fixed it in dev. But it would help a lot if someone can run the following commands when the issue happens:
```
docker-compose exec sogo-mailcow apt-get update
docker-compose exec sogo-mailcow apt-get install -y procps
docker-compose exec sogo-mailcow ps aux
```

**Comment by afzalarsalan** [comment] 2017-08-31 08:49
Sounds good, will try such when the issue arrives. Just curious, any specifics on what's causing the issue?

**Comment by andryyy** [comment] 2017-08-31 08:50
Thanks! :)

**Comment by axd** [comment] 2017-09-02 18:50
@afzalarsalan I am not using reverse proxy. 

@andryyy Just happen again, but I will try your commands on the next time. Thanks.

**Comment by cklabautermann** [comment] 2017-09-05 07:20
@afzalarsalan I don´t use a reverse proxy, too. Just basic mailcow.
@andryyy I will use your command when the problem appears and I am in front of a computer.
Thanks :-)!

**Comment by ChessSpider** [comment] 2017-09-05 11:36
```
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | 2017-09-05 13:27:34,960 INFO waiting for sogo to stop
sogo-mailcow_1       | Sep  5 13:27:34 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:35 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:35 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | Sep  5 13:27:36 efb11f539fef sogod [26]: <0x0x55bf06daf910[WOWatchDog]> Terminating with SIGINT or SIGTERM
sogo-mailcow_1       | 2017-09-05 13:27:36,947 WARN killing 'sogo' (26) with SIGKILL
sogo-mailcow_1       | 2017-09-05 13:27:36,951 INFO stopped: sogo (terminated by SIGKILL)
sogo-mailcow_1       | 2017-09-05 13:27:36,972 INFO spawned: 'sogo' with pid 16367
sogo-mailcow_1       | Sep  5 13:27:37 efb11f539fef sogod [16367]: version 3.2.10 (build pbuilder@sleipnir 201707052222) -- starting
sogo-mailcow_1       | Sep  5 13:27:37 efb11f539fef sogod [16367]: vmem size check enabled: shutting down app when vmem > 512 MB. Currently at 205 MB
sogo-mailcow_1       | Sep  5 13:27:37 efb11f539fef sogod [16367]: <0x0x5575497d5d00[SOGoProductLoader]> SOGo products loaded from '/usr/lib/GNUstep/SOGo':
sogo-mailcow_1       | Sep  5 13:27:37 efb11f539fef sogod [16367]: <0x0x5575497d5d00[SOGoProductLoader]>   Mailer.SOGo, ActiveSync.SOGo, MainUI.SOGo, Appointments.SOGo, SchedulerUI.SOGo, Contacts.SOGo, PreferencesUI.SOGo, MailPartViewers.SOGo, MailerUI.SOGo, CommonUI.SOGo, AdministrationUI.SOGo, ContactsUI.SOGo
sogo-mailcow_1       | Sep  5 13:27:37 efb11f539fef sogod [16367]: All products loaded - current memory usage at 273 MB
sogo-mailcow_1       | Sep  5 13:27:37 efb11f539fef sogod [16367]: [WARN] <0x0x5575498d3080[WOWatchDog]> listening socket: attempt 1 failed
sogo-mailcow_1       | Sep  5 13:27:38 efb11f539fef sogod [16367]: [WARN] <0x0x5575498d3080[WOWatchDog]> listening socket: attempt 2 failed
sogo-mailcow_1       | 2017-09-05 13:27:38,131 INFO success: sogo entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
sogo-mailcow_1       | sogo: stopped
sogo-mailcow_1       | sogo: started
sogo-mailcow_1       | Sep  5 13:27:39 efb11f539fef sogod [16367]: [WARN] <0x0x5575498d3080[WOWatchDog]> listening socket: attempt 3 failed
sogo-mailcow_1       | Sep  5 13:27:40 efb11f539fef sogod [16367]: [WARN] <0x0x5575498d3080[WOWatchDog]> listening socket: attempt 4 failed
sogo-mailcow_1       | Sep  5 13:27:41 efb11f539fef sogod [16367]: [WARN] <0x0x5575498d3080[WOWatchDog]> listening socket: attempt 5 failed
sogo-mailcow_1       | Sep  5 13:27:42 efb11f539fef sogod [16367]: [ERROR] <0x0x5575498d3080[WOWatchDog]> unable to listen on specified port, check that no other process is already using it
sogo-mailcow_1       | 2017-09-05 13:27:42,140 INFO exited: sogo (exit status 0; expected)
```` 

😭

**Comment by andryyy** [comment] 2017-09-05 18:01
Did you run the commands from above?

**Comment by ChessSpider** [comment] 2017-09-05 18:48
unfortunately no  ~ will do next time
you do see in the logs docker tries to restart but can't due to port reuse and then finally gives up

**Comment by andryyy** [comment] 2017-09-05 18:50
I will implement a further change in dev. But I am almost sure (tm) I fixed it already.

**Comment by MrJacK67** [comment] 2017-09-11 07:26
Same problem here, output of ps :

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND

root         1  0.0  0.2  58432 20784 ?        Ss   Sep06   3:07 /usr/bin/python
root         9  0.0  0.0 513100  7988 ?        Sl   Sep06   0:38 /usr/sbin/syslo
root        10  0.0  0.0  27992  2396 ?        S    Sep06   0:04 /usr/sbin/cron 
root        11  0.0  0.0  18020  2944 ?        S    Sep06   0:00 /bin/bash /reco
sogo        12  0.0  0.1  38500 13112 ?        S    Sep06   1:37 /usr/bin/python
root      3442  0.0  0.0  36628  2824 pts/0    Rs+  09:20   0:00 ps aux
sogo     18449  0.0  0.6 307368 49548 ?        Ss   Sep07   0:21 /usr/sbin/sogod
root     31549  0.0  0.0   4196   660 ?        S    00:40   0:00 sleep 99999

**Comment by andryyy** [comment] 2017-09-11 09:40
Should be fixed with the new code merge.

**Comment by axd** [comment] 2017-09-12 02:19
@andryyy I'm pasting the output from the commands that you mentioned:

Hope it helps:

```
root@server:~/# docker-compose exec sogo-mailcow ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.3  58536 15948 ?        Ss   Sep02   3:36 /usr/bin/python
root        10  0.0  0.1 365628  4292 ?        Sl   Sep02   1:31 /usr/sbin/syslo
root        11  0.0  0.0  27988  1144 ?        S    Sep02   0:04 /usr/sbin/cron 
sogo        13  0.0  0.2  38544  9480 ?        S    Sep02   1:40 /usr/bin/python
root      2309  0.0  0.0  36624  1548 ?        Rs+  20:17   0:00 ps aux
sogo     18054  0.0  0.8 306196 33540 ?        Ss   Sep10   0:08 /usr/sbin/sogod
root     29865  0.0  0.0  18008  1648 ?        S    10:46   0:00 /bin/bash /reco
root     29877  0.0  0.0   4192   360 ?        S    10:46   0:00 sleep 99999

```

**Comment by andryyy** [comment] 2017-09-12 05:51
Thanks, should be fixed now. 👍

**Comment by MrJacK67** [comment] 2017-09-21 07:31
I launched the update on 12/09, same problem this morning :

```
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.0  0.1  58400 15444 ?        Ss   Sep12   5:10 /usr/bin/python /usr/bin/supervisord -c /etc/supervisor/supervisord.conf
root         9  0.0  0.0 513100  7396 ?        Sl   Sep12   1:12 /usr/sbin/syslog-ng --foreground --no-caps
root        10  0.0  0.0  27992  2308 ?        S    Sep12   0:06 /usr/sbin/cron -f
sogo        12  0.0  0.1  38500  9660 ?        S    Sep12   2:33 /usr/bin/python -u -m SimpleHTTPServer 9192
root        19  0.0  0.0  18020  2844 ?        S    Sep12   0:00 /bin/bash /reconf-domains.sh
root     22392  0.0  0.0   4196   760 ?        S    Sep20   0:00 sleep 99999
sogo     23746  0.0  0.5 304140 46060 ?        Ss   Sep18   0:14 /usr/sbin/sogod
root     31981  0.0  0.0  18184  3240 pts/0    Ss   09:29   0:00 bash
root     32295  0.0  0.0  36628  2800 pts/0    R+   09:29   0:00 ps aux
```

**Comment by ChessSpider** [comment] 2017-09-21 08:53
I closed https://github.com/mailcow/mailcow-dockerized/issues/624 as it was a duplicate of this issue.

@MrJacK67 I got a comment in #624 that reconf-domains.sh is old and thus maybe you're not running the latest version. 

I too was running an outdated version of SOGo it seems. In any case, I really need this to be fixed asap. We recently migrated to Mailcow and I am getting a lot of complaints from my employees about problems.  This is caused by SOGo crashing as they all connect either through the webmail or through ActiveSync.  I hope the update really fixes the problem  👍

**Comment by PhoenixPeca** [comment] 2017-09-22 09:29
Hi @ChessSpider and @axd!

I have personally experienced the same issue a few weeks ago while provisioning a mailcow instance in a low ram development vps. (In my case) I suppose the random crashes of SOGo was caused by a [memory leak](https://sogo.nu/bugs/view.php?id=3120) or quite possibly SOGo ran out of memory. My solution to the random SOGo crashes was to set `SxVMemLimit` into a lower value (ex. 300 or 350) in the "[data/conf/sogo/sogo.conf](https://github.com/mailcow/mailcow-dockerized/blob/master/data/conf/sogo/sogo.conf#L39)" file. Thereafter, SOGo no longer stops suddenly. This solution might not work for you though.

**Closed as completed** 2018-10-13 15:37 UTC
