### ISSUE TITLE
iptables firewall

### ISSUE THREAD

**Issue by bloomcake** [mailcow/mailcow-dockerized#1332] opened 2018-04-27 10:34 UTC
Hello,

I have my own iptables script and if I enable this mailcow will not work anymore.
I think I'll override mailcow's rules, but I can not figure out what rules that will be so I can add them to my script.
Or can I solve it somehow differently?

Thank you!

**Comment by mkuron** [comment] 2018-04-27 11:54
Duplicate of #908.

**Closed as completed by mkuron** 2018-04-27 11:54 UTC
