### ISSUE TITLE
Converse.js

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#4071] opened 2021-04-25 10:28 UTC
Hello, 

I put in a feature-request for a Webclient for ejabberd:
https://m.conversejs.org/

Thanks in advance.

**Comment by mritzmann** [comment] 2021-05-20 07:54
duplicate of https://github.com/mailcow/mailcow-dockerized/issues/3990

**Comment by omexlu** [comment] 2021-05-20 07:57
Nice, but does not help anyone 😂

**Comment by mritzmann** [comment] 2021-05-20 08:01
Then you have not understood how issue tracking and open source works.

**Comment by andryyy** [comment] 2021-05-20 08:08
Why did you open two FR?

**Closed as completed by andryyy** 2021-05-20 08:08 UTC
Labels: enhancement

**Comment by omexlu** [comment] 2021-05-20 08:12
Because I wanted to draw attention to it again but is not considered anyway, so can actually both be closed 🙈😬

Thanks in advance.

**Comment by andryyy** [comment] 2021-05-20 08:23
Please don't do that.
