### ISSUE TITLE
[Enhancement] DNS server integration

### ISSUE THREAD

**Issue by Adorfer** [mailcow/mailcow-dockerized#1763] opened 2018-09-13 14:24 UTC
having a "full blown" dns server inside mailcow would be really great. 

1. the mailserversetup already requires a lot of dns setup, so it would make things easier, 
2. DNSsec/DANE would be a piece of cake
3. since there is already a usermanagament and webui, stuff like "dyndns" would be easy to bundle on top. 
4. a good dns-webui would bring in a lot of users... frusted by the "local webui" of their registrar's "free dns"  
(e.g i can not set any service-records to signalzie imap-fqdn etc at mine... but i do not want to do this "manual" either. And DNSsec would be a real pain.)

I am totally aware that
- a DNS has a large attack surface or/and or very attractive target
- a secondary DNS (he.net...) would be strongly advised
- increasing the complexity of mailcow is a risk 

But on the other hand, such a DNS (i an suppose it would be a quite capable one) would attract totally new groups of users.

**Comment by extremeshok** [comment] 2018-09-13 15:05
I am completely against having a full blown dns on the mailserver.

It would be a far better idea to integrate the admin with the powerdns api, this would also allow support for dns validation for acme certs.

https://doc.powerdns.com/md/httpapi/README/

After configuring the settings (dns api url + api key), the admin / user could push the records directly to the dns servers via the admin management interface of mailcow.

**Comment by andryyy** [comment] 2018-09-13 16:14
Only PowerDNS? I could start implementing the Servercow API and you can use it as example for other systems. 

But... do we need this? :-/ I am not convinced.

**Comment by mkuron** [comment] 2018-09-13 17:36
Duplicate of #438

**Closed as completed by mkuron** 2018-09-13 17:36 UTC
