### ISSUE TITLE
[Feature-Request] Allow different DNS domains than SMTP welcome message domains

### ISSUE THREAD

**Issue by Preisschild** [mailcow/mailcow-dockerized#2954] opened 2019-09-18 13:42 UTC
**Is your feature request related to a problem? Please describe.**
It's a bit annoying to get errors in the dns lookup feature, when you have a different MAILCOW_HOSTNAME than the dns entries set at your nameserver. I do this, because I want the SMTP welcome message to show a different domain (the reverse hostname) than my mail-domain is set at.

Basically I have set it up like this:
RDNS = home.example.org
MAIL DOMAIN SET IN CLOUDFLARE = mail.example.org

and I currently use the RDNS domain as MAILCOW_HOSTNAME so that it shows in the smtp welcome message, as it should be. 
But my RDNS differs from my domain I want to use to access SMTP.

**Describe the solution you'd like**
A separate config option only for the smtp welcome message.

**Comment by andryyy** [comment] 2019-09-18 13:43
Your mail domain is not related to your mailcows hostname. It can be anything.

**Comment by Preisschild** [comment] 2019-09-18 13:45
@andryyy Yes. But it is giving errors in the DNS Lookup in the Mailcow Webinterface, as this one is using the mailcow_hostname.

Everything else works. So this is a pretty low priority for me.

**Comment by mkuron** [comment] 2019-09-18 15:23
Duplicate of #528. We don't currently support using multiple different domains for the mail server.

**Closed as completed by mkuron** 2019-09-18 15:23 UTC
