### ISSUE TITLE
Cloudflare SSL - IMAP not working

### ISSUE THREAD

**Issue by DrTrills** [mailcow/mailcow-dockerized#1546] opened 2018-07-05 22:32 UTC
Hi all, I changed from Letsenrypt to Cloudflare issued SSL. I am able to access everything on the web fine, but unable to connect via Outlook, apple mail etc. When I disabled Coudflare on a DNS level the SSL isn't valid but I am able to connect. If anyone can point me in the right direction of using Cloudflare and Mailcow via IMAP that would be great. Thanks!

**Comment by mkuron** [comment] 2018-07-06 04:04
Duplicate of #873. Cloudflare only supports web traffic, so you need to disable it for Mailcow.

**Closed as completed by mkuron** 2018-07-06 04:04 UTC

**Comment by DrTrills** [comment] 2018-07-06 15:57
Thanks @mkuron

**Comment by DrTrills** [comment] 2018-07-09 18:56
@mkuron do you know how to I can re-install Acme/Letsencrypt? I did Docker compose restart acme-mailcow and it didnt do anything. Checking the logs, it seems to see the cloudflare SSL is still registering and not letting ACME do it's thing. If there is a force command you reccomend i'd be very keen to learn more.

Thanks!
```

acme-mailcow_1       | Fri Jul  6 18:36:08 EDT 2018 - Waiting for Docker API...OK
acme-mailcow_1       | Fri Jul  6 18:36:08 EDT 2018 - Found certificate with issuer other than mailcow snake-oil CA and Let's Encrypt, skipping ACME client...
acme-mailcow_1       | Sun Jul  8 23:52:18 EDT 2018 - Waiting for Docker API...OK
acme-mailcow_1       | Sun Jul  8 23:52:19 EDT 2018 - Found certificate with issuer other than mailcow snake-oil CA and Let's Encrypt, skipping ACME client...
acme-mailcow_1       | Mon Jul  9 00:21:08 EDT 2018 - Waiting for Docker API...OK
acme-mailcow_1       | Mon Jul  9 00:21:09 EDT 2018 - Found certificate with issuer other than mailcow snake-oil CA and Let's Encrypt, skipping ACME client...
acme-mailcow_1       | Mon Jul  9 00:25:30 EDT 2018 - Waiting for Docker API...OK
acme-mailcow_1       | Mon Jul  9 00:25:30 EDT 2018 - Found certificate with issuer other than mailcow snake-oil CA and Let's Encrypt, skipping ACME client...
```

**Comment by hachre** [comment] 2018-07-09 19:05
Did you try doing a full `docker-compose down` and `docker-compose up -d`? Seems like the DNS is cached somewhere?

**Comment by andryyy** [comment] 2018-07-09 19:07
Or `down`, `rm -rf data/assets/ssl`, `up -d`.

**Comment by DrTrills** [comment] 2018-07-10 20:07
@hachre I did that with no luck, same with your suggestion @andryyy .

Interesting indeed. I wonder if the network error has anything to do with it. Any other ideas are warmly welcome 👍 Thanks for everyones support so far, I really appreciate it!

```
/mailcow-dockerized# docker-compose down
Stopping mailcowdockerized_acme-mailcow_1      ... done
Stopping mailcowdockerized_rspamd-mailcow_1    ... done
Stopping mailcowdockerized_netfilter-mailcow_1 ... done
Stopping mailcowdockerized_nginx-mailcow_1     ... done
Stopping mailcowdockerized_php-fpm-mailcow_1   ... done
Stopping mailcowdockerized_dovecot-mailcow_1   ... done
Stopping mailcowdockerized_ipv6nat_1           ... done
Stopping mailcowdockerized_sogo-mailcow_1      ... done
Stopping mailcowdockerized_unbound-mailcow_1   ... done
Stopping mailcowdockerized_watchdog-mailcow_1  ... done
Stopping mailcowdockerized_memcached-mailcow_1 ... done
Stopping mailcowdockerized_dockerapi-mailcow_1 ... done
Stopping mailcowdockerized_mysql-mailcow_1     ... done
Stopping mailcowdockerized_clamd-mailcow_1     ... done
Stopping mailcowdockerized_redis-mailcow_1     ... done
Stopping mailcowdockerized_postfix-mailcow_1   ... done
Removing mailcowdockerized_acme-mailcow_1      ... done
Removing mailcowdockerized_rspamd-mailcow_1    ... done
Removing mailcowdockerized_netfilter-mailcow_1 ... done
Removing mailcowdockerized_nginx-mailcow_1     ... done
Removing mailcowdockerized_php-fpm-mailcow_1   ... done
Removing mailcowdockerized_dovecot-mailcow_1   ... done
Removing mailcowdockerized_ipv6nat_1           ... done
Removing mailcowdockerized_sogo-mailcow_1      ... done
Removing mailcowdockerized_unbound-mailcow_1   ... done
Removing mailcowdockerized_watchdog-mailcow_1  ... done
Removing mailcowdockerized_memcached-mailcow_1 ... done
Removing mailcowdockerized_dockerapi-mailcow_1 ... done
Removing mailcowdockerized_mysql-mailcow_1     ... done
Removing mailcowdockerized_clamd-mailcow_1     ... done
Removing mailcowdockerized_redis-mailcow_1     ... done
Removing mailcowdockerized_postfix-mailcow_1   ... done
Removing network mailcowdockerized_mailcow-network
ERROR: network mailcowdockerized_mailcow-network id 081fe43a787fdfb1b5dd8d85351e30dcfd0294c035c926743f1d091a53024d46 has active endpoints
```

**Comment by andryyy** [comment] 2018-07-10 20:11
You should post the logs of acme-mailcow now that you recreated the containers and deleted the ssl folder.
