### ISSUE TITLE
multi ips

### ISSUE THREAD

**Issue by masihfathi** [mailcow/mailcow-dockerized#1273] opened 2018-04-16 10:41 UTC
Hi
Is it possible use it like MTA for sending with multi ips and ip rotating?
I want to create a email marketing service and use mailcow as a mail server,  is it a right a choice?

**Comment by mkuron** [comment] 2018-04-16 11:01
Duplicate of https://github.com/mailcow/mailcow-dockerized/pull/727#issuecomment-369778058. We won't support multiple IPs, but there is a variable in mailcow.conf you can set to specify which one to use.

Since you probably only need outgoing messages, Mailcow is needlessly complex for your purpose. Just set up a plain Postfix.

**Closed as completed by mkuron** 2018-04-16 11:01 UTC

**Comment by feldsam** [comment] 2018-09-20 11:14
hmm, it is not good. when your clients have setuped mail forwardings to gmail, them you will be rate limited and there is no other solution that rotating IPs

**Comment by mkuron** [comment] 2018-09-20 16:18
How do ISPs solve that issue? Often they don't have more than a few dozen/hundred IPs for millions of customers. I guess Gmail has some kind of reputation score. You could sign up for Google Postmaster Tools and see if that recommends anything to inprove your reputation so that you don't need multiple IPs.

**Comment by DipenduDas73** [comment] 2023-07-21 05:19
But Multiple IPs are needed if one ISP is down then we can't send email from that IP, in my server I am using multi wan switch, but if one of my ISP is off, I can't send email, so please support multiple IPs, it's needed for actual server to work without server downtime
