### ISSUE TITLE
Allow choice of tag/alias character

### ISSUE THREAD

**Issue by the-solipsist** [mailcow/mailcow-dockerized#3083] opened 2019-10-23 10:36 UTC
**Is your feature request related to a problem? Please describe.**
Many input forms do not comply with RFC [5322](https://tools.ietf.org/html/rfc5322) and [3696](https://tools.ietf.org/html/rfc3696), and do not accept `+` characters in email addresses, but do accept `.`,`-`, and `_` because those are common.  This makes it difficult to use sub-addressing/tagged addressing if `+` is hard-coded.  RFC [5233](https://tools.ietf.org/html/rfc5233) on sub-addressing allows other characters to be used as a "separator character sequence" (and even gives the example of `5551212#123@example.com`.

**Describe the solution you'd like**
Allowing users to configure their own tag delimiter either through a check box (containing `.`, `-`, and `_`), or through a free-form field.

**Comment by mkuron** [comment] 2019-10-23 11:19
Duplicate of #1146 and #1352. 

Common characters like . or - won't work because it would be ambiguous whether something is part of the address or the tag.

**Closed as completed by mkuron** 2019-10-23 11:19 UTC

**Comment by ralfbergs** [comment] 2024-11-08 17:03
> Duplicate of #1146 and #1352.
> 
> Common characters like . or - won't work because it would be ambiguous whether something is part of the address or the tag.

I don't understand this rationale. Maybe you could elaborate, please?

According to the email format RFC, all these characters, `.`, `-`, and `+`, are "normal" characters to be used in a local-part **unquotedly**. So none of them is "special".

So why is `+` better than `-`? If an organization decides to use `-`, they should stay clear of using it in the mailbox address, and there would not be a problem.

As explained by the requester, the `+` is very problematic as a character in a local-part when you try to enter such an address in web forms, even those operated by big, well-known companies. They reject such email addresses as "invalid". :-(

For `-` I've never seen such a problem, and I'm using this since >20 years now.

**Comment by immanuelfodor** [comment] 2024-11-08 17:28
I can confirm, many forms filter out `+` as invalid, but `.` (for me) works fine and it would be great to have it as an alias option (eg. both `+` and `.` could co-exist for my setup, using `+` wherever I can and falling back to `.` when needed).

**Comment by ralfbergs** [comment] 2024-11-08 18:40
I'm now using `recipient_delimiter = +-~%!/` in the config for Postfix and Dovecot, and it works for the minimal functionality of receiving email (which is my "must-have" functionality, otherwise I would be unable to migrate to mailcow).

"Tagging" in the subject doesn't work for anything apart from `+`, and subfolders I haven't even tested. But that's fine for me.
