### ISSUE TITLE
Docker replacement request for PodMan

### ISSUE THREAD

**Issue by ycMia** [mailcow/mailcow-dockerized#6119] opened 2024-10-19 13:42 UTC
### Summary

Hi, I'd like to request the feature for Podman adaptation for this project.

### Motivation

I Experienced a strict docker version check at this [line](https://github.com/mailcow/mailcow-dockerized/blob/37beed6ad93f259b97cad41877982bce95295629/generate_config.sh#L29) :
```shell
docker_version=$(docker -v | grep -oP '\d+\.\d+\.\d+' | cut -d '.' -f 1)
```
It turns out that auto install will break in a result of 

```Text
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
Cannot find Docker with a Version higher or equals 24.0.0
mailcow needs a newer Docker version to work properly...
Please update your Docker installation... exiting
```

I use Rocky Linux 9.1, on my VPS running. Thanks for any Idea or help.

### Additional context

Using the last edition 37beed6ad93f259b97cad41877982bce95295629 at Github.

**Comment by DerLinkman** [comment] 2024-10-21 07:48
Duplicate of https://github.com/mailcow/mailcow-dockerized/pull/4982

**Closed as not planned by DerLinkman** 2024-10-21 07:48 UTC
Labels: enhancement
