### ISSUE TITLE
INFO: docker-compose.yml: "version" -> obsolete

### ISSUE THREAD

**Issue by omexlu** [mailcow/mailcow-dockerized#5823] opened 2024-04-04 10:25 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

```plain text
Hi,

I just want to let you know that a WARN message appears in the update-script that says the following:
docker-compose.yml: "version" -> obsolete

I don't know to what extent this has an influence now, but the variable "version" seems to be obsolete now.

It's not really a bug report but just a hint :)

Thanks in advance.
```

### Logs:

```plain text
NOT NEEDED
```

### Steps to reproduce:

```plain text
1. Just run the update script with actual system.
```

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Ubuntu 20.04 LTS

### Server/VM specifications:

VM

### Is Apparmor, SELinux or similar active?

no

### Virtualization technology:

KVM

### Docker version:

actual one for 20.04 LTS

### docker-compose version or docker compose version:

v2.10.2 / v2.25.0

### mailcow version:

actual version

### Reverse proxy:

NO

### Logs of git diff:

```plain text
NOT NEEDED
```

### Logs of iptables -L -vn:

```plain text
NOT NEEDED
```

### Logs of ip6tables -L -vn:

```plain text
NOT NEEDED
```

### Logs of iptables -L -vn -t nat:

```plain text
NOT NEEDED
```

### Logs of ip6tables -L -vn -t nat:

```plain text
NOT NEEDED
```

### DNS check:

```plain text
NOT NEEDED
```

**Comment by MaxXor** [comment] 2024-04-04 15:04
Duplicate of https://github.com/mailcow/mailcow-dockerized/issues/5797

**Comment by omexlu** [comment] 2024-04-04 15:11
@DerLinkman this get fixed on your end maybe?

**Comment by milkmaker** [comment] 2024-06-03 17:22
This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs.

**Comment by kovacs-andras** [comment] 2024-06-07 17:17
Docker is just docker. Don't care about it. While you can remove that line beacuse it doesn't necessary anymore imho it could break backward-compatibility.

**Comment by DerLinkman** [comment] 2024-06-10 10:11
> Docker is just docker. Don't care about it. While you can remove that line beacuse it doesn't necessary anymore imho it could break backward-compatibility.

It does not at least if you use Compose v2 which we require to operate mailcow. Even in the first 2.X Version the version section of a compose file is optional and not needed anymore.

**Comment by DerLinkman** [comment] 2024-06-10 10:12
This issue will be fixed with the June patch.

**Closed as completed by DerLinkman** 2024-06-10 10:12 UTC
Labels: bug

**Comment by omexlu** [comment] 2024-06-28 08:43
> This issue will be fixed with the June patch.

@DerLinkman 

Hello,

I received the message again during the update for "docker-compose.yml".

Is it possible that the message appears again with the first update and not with the next update?

Thanks in advance.

**Comment by DerLinkman** [comment] 2024-06-28 13:42
Hi,
no it does not appear again but if you use a docker-compose.override.yml you need to remove it there manually.
