### ISSUE TITLE
google apps > mailcow imapsync

### ISSUE THREAD

**Issue by cxyb** [mailcow/mailcow-dockerized#2476] opened 2019-03-28 14:08 UTC
I'm trying to run away from google apps and been setting up mailcow dockerized.
Seems to me that every account is taking 2x more space on mailcow. server than on google apps, what could be the problem?

**Comment by evilstiefel** [comment] 2019-03-29 07:16
Seems like a vague question, since we do not know how Google calculates their space requirements (since I assume you cannot access Google servers to find out how much space they actually use).

They might not be counting certain attachments (e.g. photos) or exclude folders like Spam etc.

As long as you don't see something factually wrong like a duplicate of every message, it's impossible to say there is anything wrong.

**Comment by andryyy** [comment] 2019-03-29 07:56
Make sure to set `Skip duplicate messages across folders (first come, first serve) (--skipcrossduplicates)`

**Comment by mkuron** [comment] 2019-03-29 08:36
If you copied the "All Mails" folder, all messages from all other folders are duplicated in "All Mails".

**Comment by apintocr** [comment] 2019-03-29 13:28
The issue here (specially using IMAP that Gmail does not support natively) is almost certainly the TAGS feature of Gmail.

Gmail does not use folders, it tags emails, so the same email can be in multiple TAGS.
IMAP uses folders.
Gmail converts tags to folders in order to support some sort of compatibility with IMAP folders.
That causes the same message to be retrieved multiple times if it has multiple TAGS (and it almost certainly has multiple tags).

You can replicate the same issue if you sync with Outlook or Thunderbird.

**Comment by cxyb** [comment] 2019-03-29 14:06
Is there any way to remove duplicates?

**Comment by apintocr** [comment] 2019-03-29 17:06
Check the comment above:
> @andryyy https://github.com/mailcow/mailcow-dockerized/issues/2476#issuecomment-477903936
Make sure to set `Skip duplicate messages across folders (first come, first serve) (--skipcrossduplicates)`

**Comment by cxyb** [comment] 2019-03-29 17:53
I've used option to skip duplicates  plus i run doveadm deduplicate but
neither resulted in data usage reduction.

**Comment by apintocr** [comment] 2019-03-29 18:31
Maybe it's all ok :)
Tomorrow I will test a sync with a small gmail account I have.

**Comment by cxyb** [comment] 2019-03-30 12:10
It might be, as Steffe said, we can't know how are they calculating space
usage, they might store attachments on google drive or smh.

**Comment by apintocr** [comment] 2019-03-30 20:08
@cxyb I was not able to test today.
I will try tomorrow.

**Closed as completed** 2019-06-05 20:49 UTC
