### ISSUE TITLE
Bug: When using alias goto-adresses with tag (e.g. test+news@example.com) tag filters do not apply

### ISSUE THREAD

**Issue by BjarneRest** [mailcow/mailcow-dockerized#1299] opened 2018-04-20 14:24 UTC
Heyho,

I would like to point a catch-all alias to user+CatchAll@domain.com because I'd like to have them in my CatchAll folder.
However, the tagging filters don't apply to emails routed through an alias adress.

Thank you so far,
Bjarne Rest

**Comment by mkuron** [comment] 2018-04-20 20:40
Duplicate of #408

**Closed as completed by mkuron** 2018-04-20 20:40 UTC
