### ISSUE TITLE
Rspamd: cannot add rule "clamav"

### ISSUE THREAD

**Issue by mrclschstr** [mailcow/mailcow-dockerized#5738] opened 2024-02-12 00:02 UTC
### Contribution guidelines

- [X] I've read the [contribution guidelines](https://github.com/mailcow/mailcow-dockerized/blob/master/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug and checked that ...

- [X] ... I understand that not following the below instructions will result in immediate closure and/or deletion of my issue.
- [X] ... I have understood that this bug report is dedicated for bugs, and not for support-related inquiries.
- [X] ... I have understood that answers are voluntary and community-driven, and not commercial support.
- [X] ... I have verified that my issue has not been already answered in the past. I also checked previous [issues](https://github.com/mailcow/mailcow-dockerized/issues).

### Description

I ran a few tests with the EICAR test virus (using https://dont.panic.at/index.php?content=Send_EICAR) and I noticed that some of the "infected" emails sent were not filtered out by rspamd and no `VIRUS_FOUND` symbol was assigned to them.

Long story short: I was able to find out that the problem is related to the start of the containers and is therefore not deterministic. If the ClamAV container takes a little longer to start, rspamd seems to be unable to establish a connection and does not load the ClamAV rules. The following logs can be found:

```
mailcowdockerized-rspamd-mailcow-1  | 2024-02-11 21:16:05 #1(main) <ac13b2>; upstreams; rspamd_resolve_addrs: address resolution for clamd failed: Name or service not known
mailcowdockerized-rspamd-mailcow-1  | 2024-02-11 21:16:05 #1(main) <7q9uze>; lua; clamav.lua:77: cannot parse servers clamd:3310
mailcowdockerized-rspamd-mailcow-1  | 2024-02-11 21:16:05 #1(main) <7q9uze>; lua; antivirus.lua:206: cannot add rule: "clamav"
```

My current workaround is:
1. Start all containers `docker compose up -d`
2. Wait briefly until everything has settled down
3. Restart rspamd container `docker compose restart rspamd-mailcow`
4. Check rspamd logs `docker compose logs rspamd-mailcow | grep -i "antivirus.lua"`. If rspamd was able to successfully establish a connection to ClamAV, the following should be found in the logs:

```
mailcowdockerized-rspamd-mailcow-1  | 2024-02-11 22:53:04 #1(main) <pm43sj>; lua; antivirus.lua:209: added antivirus engine clamav -> CLAM_VIRUS
```

### Logs:

See description above.

### Steps to reproduce:

1. Stop all containers: `docker compose down`
2. Start all containers: `docker compose up -d`
3. Check if antivirus rules could be loaded by rspamd: `docker compose logs rspamd-mailcow | grep -i "antivirus.lua"`

Unfortunately, this is not deterministic and cannot always be reproduced

### Which branch are you using?

master

### Which architecture are you using?

x86

### Operating System:

Ubuntu 22.04.3 LTS

### Server/VM specifications:

4 vCPU, 8 GB RAM

### Is Apparmor, SELinux or similar active?

No

### Virtualization technology:

KVM

### Docker version:

24.0.7

### docker-compose version or docker compose version:

v2.21.0

### mailcow version:

2024-01e

### Reverse proxy:

No

### Logs of git diff:

```plain text
[Omitted cert.pem and key.pem]

diff --git a/data/conf/postfix/main.cf b/data/conf/postfix/main.cf
index 572300db..2158fecc 100644
--- a/data/conf/postfix/main.cf
+++ b/data/conf/postfix/main.cf
@@ -173,3 +173,36 @@ parent_domain_matches_subdomains = debug_peer_list,fast_flush_domains,mynetworks

 # DO NOT EDIT ANYTHING BELOW #
 # Overrides #
+
+postscreen_dnsbl_sites = wl.mailspike.net=127.0.0.[18;19;20]*-2
+  hostkarma.junkemailfilter.com=127.0.0.1*-2
+  list.dnswl.org=127.0.[0..255].0*-2
+  list.dnswl.org=127.0.[0..255].1*-4
+  list.dnswl.org=127.0.[0..255].2*-6
+  list.dnswl.org=127.0.[0..255].3*-8
+  ix.dnsbl.manitu.net*2
+  bl.spamcop.net*2
+  bl.suomispam.net*2
+  hostkarma.junkemailfilter.com=127.0.0.2*3
+  hostkarma.junkemailfilter.com=127.0.0.4*2
+  hostkarma.junkemailfilter.com=127.0.1.2*1
+  backscatter.spameatingmonkey.net*2
+  bl.ipv6.spameatingmonkey.net*2
+  bl.spameatingmonkey.net*2
+  b.barracudacentral.org=127.0.0.2*7
+  bl.mailspike.net=127.0.0.2*5
+  bl.mailspike.net=127.0.0.[10;11;12]*4
+  dnsbl.sorbs.net=127.0.0.10*8
+  dnsbl.sorbs.net=127.0.0.5*6
+  dnsbl.sorbs.net=127.0.0.7*3
+  dnsbl.sorbs.net=127.0.0.8*2
+  dnsbl.sorbs.net=127.0.0.6*2
+  dnsbl.sorbs.net=127.0.0.9*2
+  zen.spamhaus.org=127.0.0.[10;11]*8
+  zen.spamhaus.org=127.0.0.[4..7]*6
+  zen.spamhaus.org=127.0.0.3*4
+  zen.spamhaus.org=127.0.0.2*3
+
+# User Overrides
+myhostname = mail.[XXX].com
```

### Logs of iptables -L -vn:

```plain text
Relevant? I can provide more information if it is important.
```

### Logs of ip6tables -L -vn:

```plain text
Relevant? I can provide more information if it is important.
```

### Logs of iptables -L -vn -t nat:

```plain text
Relevant? I can provide more information if it is important.
```

### Logs of ip6tables -L -vn -t nat:

```plain text
Relevant? I can provide more information if it is important.
```

### DNS check:

```plain text
104.18.32.7
172.64.155.249
```

**Comment by DerLinkman** [comment] 2024-02-14 08:54
You disabled clamav in your mailcow.conf right?

**Comment by mrclschstr** [comment] 2024-02-14 09:08
No, it's enabled.

For ClamAV to work together with Rspamd, I have to wait a bit after starting the containers and then restart the Rspamd container (as described in my current workaround).

**Comment by mrclschstr** [comment] 2024-02-25 20:48
Issue is still present in version `2024-02`.

**Comment by milkmaker** [comment] 2024-02-26 09:12
**THIS IS A AUTOMATED MESSAGE!**

It seems your issue is not a bug.
Therefore we highly advise you to get support!

You can get support either by:
- ordering a paid [support contract at Servercow](https://www.servercow.de/mailcow?lang=en#support/) (Directly from the developers) or
- using the [community forum](https://community.mailcow.email) (**Based on volunteers! NO guaranteed answer**) or
- using the [Telegram support channel](https://t.me/mailcow) (**Based on volunteers! NO guaranteed answer**)

This issue will be closed. If you think your reported issue is not a support case feel free to comment above and if so the issue will reopened.

**Comment by KaiserN** [comment] 2024-03-20 10:46
Hi,

hitted the same issue right now, latest mailcow version.
after restart mailcow (os updates) i found same messages in rspamd log/webui

`cannot add rule: \"clamav\"
cannot parse servers clamd:3310
`

ICAR Test

![grafik](https://github.com/mailcow/mailcow-dockerized/assets/47419452/6bcc20ee-795b-46b8-a8e3-d7d3fa96db31)

after

docker compose restart clamd-mailcow
docker compose restart rspamd-mailcow

no entry in logs as described above

and ICAR Test

![grafik](https://github.com/mailcow/mailcow-dockerized/assets/47419452/ca4ec9e4-7bfa-4343-8cec-79c90af367ff)

workerd again as expected


i think there is a problem in the start sequence or the waiting time is too short for the following service.

@DerLinkman please check again, thank you! <3

**Comment by cjwalsh** [comment] 2024-09-03 21:35
I just had the same issue with the latest 2024-08a version, see these lines in the rspamd logs:

```
2024-09-03 21:14:44 #1(main) <993184>; upstreams; rspamd_resolve_addrs: address resolution for clamd failed: Name or service not known
2024-09-03 21:14:44 #1(main) <zgwzyi>; lua; clamav.lua:77: cannot parse servers clamd:3310
2024-09-03 21:14:44 #1(main) <zgwzyi>; lua; antivirus.lua:206: cannot add rule: "clamav"
```

I agree with the suggestion that this is non-deterministic, since it depends on the timing of the startup of the rspamd and clamd services, which currently have no explicit startup dependencies defined, nor does the `docker-entrypoint.sh` script check for clamd in the way that it does check for other dependencies like phpfpm, Dovecot, and Redis.

I suspect this can be resolved by adding an entry to the `depends_on` section in the `rspamd-mailcow` service entry in `docker-compose.yml` so that it depends on the `clamd-mailcow` service in addition to the current entry for `dovecot-mailcow`.

```

....

    rspamd-mailcow:
      image: mailcow/rspamd:1.96
      stop_grace_period: 30s
      depends_on:
        - dovecot-mailcow
        - clamd-mailcow
      environment:
        - TZ=${TZ}
        <..etc..>
....

```

This could also be added to the configuration via a `docker-compose.override.yml` file to supplement the default configuration, and this will be the approach I'll use since I already use this method for adding my reverse proxy configurations. With this approach you just need to specify the additional settings for the service in the override file.

```

....

    rspamd-mailcow:
      depends_on:
        - clamd-mailcow

....

```

This approach is flexible and caters for those users who decide to disable `clamd`, which would potentially cause the `rspamd` startup to hang waiting for `clamd` if it was specified in the main `docker-compose.yml` file. For users who keep `clamd` enabled, this startup dependency can be added via the `docker-compose.override.yml` file.

There may also be an approach where the long form of the `depends_on` attribute could use the `SKIP_CLAMD` environment variable to dynamically set `required` to true or false accordingly, which would allow this to be added to the main `docker-compose.yml` file for everyone.

Of course there may be a more subtle dependency which depends on the state of `clamd` and it having completed its startup, however the error messages in the logs above imply it's simply the host name resolution which is failing, which probably means that we just need the `clamd` service to have started its network stack.

**Comment by DerLinkman** [comment] 2024-09-04 12:33
> There may also be an approach where the long form of the `depends_on` attribute could use the `SKIP_CLAMD` environment variable to dynamically set `required` to true or false accordingly, which would allow this to be added to the main `docker-compose.yml` file for everyone.

No we won't make a dynamic decision about this as this will most likely break more then it helps...

But a new depends_on option might be a better approach. AFAIK it should work with or without clamd enabled as the clamd healthcheck is returning healthy even if the service has been deactivated by the user.

**Closed as completed** 2024-09-04 12:42 UTC
Labels: support, unconfirmed
