### ISSUE TITLE
autoconfig always points to the MAILCOW_HOSTNAME

### ISSUE THREAD

**Issue by kunago** [mailcow/mailcow-dockerized#533] opened 2017-08-25 10:09 UTC
As the title says, whenever I try to set an email address in Thunderbird, autoconfig always sets the MAILCOW_HOSTNAME as the server for incoming and outgoing emails.

Do you have an idea what could be wrong?

**Comment by chriscroome** [comment] 2017-08-25 10:15
Doesn't that illustrate that it is working correctly, or am I misunderstanding something?

Thunderbird should be getting the settings from the `http://example.com/.well-known/autoconfig/mail/config-v1.1.xml` file on your server.

 What would you expect Thunderbird to do?

**Comment by kunago** [comment] 2017-08-25 10:20
I would expect Thunderbird g.e. for domain **example.com** to output **mail.example.com**, therefore to stick with the same domain. Now it is sub1.server.com.

If I happen to switch servers and create a server sub2.server.com, I cannot migrate emails to it flawlessly.

**Comment by mkuron** [comment] 2017-08-25 10:27
@chriscroome is right, that is expected behavior. Users from all domains should access the server via MAILCOW_HOSTNAME.

Duplicate of #528.

**Comment by JiiPee74** [comment] 2017-09-03 21:42
There is another issue related to this if you are using redirect proxy setting.
Example I have in my box apache set to serve just usual stuff:
```
ServerName www.example.com
ServerAlias example.com
```

Then I have vhost for:
```
ServerName mail.example.com
ServerAlias autodiscovery.example.com
ServerAlias autoconfig.example.com
```

Now there is email clients what does autodiscovery based on your email address and simply use domain directly for autodiscovery. Example is windows 10 buildin email client what fails to do autodiscovery.

I had to add this to my usual stuff vhost
`RedirectMatch  ^/.well-known/autoconfig/mail/config-v1.1.xml https://mail.example.com/.well-known/autoconfig/mail/config-v1.1.xml`

Now win 10 email client does autodiscovery just fine.

**Closed as completed** 2017-09-09 08:42 UTC

**Comment by SoftCreatR** [comment] 2017-10-28 03:27
What i've done was simply adding this in `vars.inc.php` directly under `$mailcow_hostname = getenv('MAILCOW_HOSTNAME');`:

```
$autoconfig_hostname = dns_get_record($_SERVER['HTTP_HOST'], DNS_CNAME);

if (!empty($autoconfig_hostname[0]['target'])) {
	$mailcow_hostname = $autoconfig_hostname[0]['target'];
}
```

I know, that this is an overhead and there are way better alternatives, but for me, it does the job.

**Comment by kunago** [comment] 2017-10-28 09:47
@SoftCreatR Greate tip, thanks a lot!

**Comment by paulmarc** [comment] 2022-10-21 08:08
I solved it by creating `data/web/inc/vars.local.inc.php` (which is near `vars.inc.php`), based on an astutely placed hint  and placed my overriding variables:
```php
$mailcow_domain = "army.gov.lb";
$autodiscover_config = array(
'autodiscoverType' => 'activesync',
'useEASforOutlook' => 'no',
'imap' => array(
'server' => 'imap.' . $mailcow_domain,
'port' => (int)filter_var(substr(getenv('IMAPS_PORT'), strrpos(getenv('IMAPS_PORT'), ':')), FILTER_SANITIZE_NUMBER_INT),
'tlsport' => (int)filter_var(substr(getenv('IMAP_PORT'), strrpos(getenv('IMAP_PORT'), ':')), FILTER_SANITIZE_NUMBER_INT)
),
'pop3' => array(
'server' => 'pop.' . $mailcow_domain,
'port' => (int)filter_var(substr(getenv('POPS_PORT'), strrpos(getenv('POPS_PORT'), ':')), FILTER_SANITIZE_NUMBER_INT),
'tlsport' => (int)filter_var(substr(getenv('POP_PORT'), strrpos(getenv('POP_PORT'), ':')), FILTER_SANITIZE_NUMBER_INT)
),
'smtp' => array(
'server' => 'smtp.' . $mailcow_domain,
'port' => (int)filter_var(substr(getenv('SMTPS_PORT'), strrpos(getenv('SMTPS_PORT'), ':')), FILTER_SANITIZE_NUMBER_INT),
'tlsport' => (int)filter_var(substr(getenv('SUBMISSION_PORT'), strrpos(getenv('SUBMISSION_PORT'), ':')), FILTER_SANITIZE_NUMBER_INT)
),
'activesync' => array(
'url' => 'https://' . $mailcow_hostname . ($https_port == 443 ? '' : ':' . $https_port) . '/Microsoft-Server-ActiveSync',
),
'caldav' => array(
'server' => $mailcow_hostname,
'port' => $https_port,
),
'carddav' => array(
'server' => $mailcow_hostname,
'port' => $https_port,
),
);
```
